### PR TITLE
Updated french language, added somes emojies

### PR DESCRIPTION
**Pull request by NEVARLeVrai**
Updated french language, added somes emojies

also missing translate
image

### CODE REVIEW

**Comment by fast4x** [comment]
wow you’re doing great

**Comment by NEVARLeVrai** [comment]
image
image

could u add this later in translation file ?

**Comment by fast4x** [comment]
Yep, add merge request.

**Comment by NEVARLeVrai** [comment]
> Owner

naah i mean its missing in translation file oi think u missunderstood

**Comment by ikanakova** [comment]
Done - see #124.

**Comment by NEVARLeVrai** [comment]
> > naah i mean its missing in translation file i think u missunderstood what I circled in orange
> 
> Done - see #124.
> 
> PureBlack and ModernBlack are names so they should remain untranslated.

oh ok

**Pull request merged**
