### PR TITLE
20% Dark shade for blurred background, Transparent action bar and next songs bar when transparent action bar is chosen & Fixed 'Disable' button

### PR DESCRIPTION
**Pull request by aneesh1122**
1. Dark shade
Screenshot_20240611_173823

I found 20% to be the sweet spot. Taken the code from bbyeen's pull.

2. Transparent action bar and next songs bar when transparent action bar is chosen
......................Transparent background : off....................................................................................Transparent Background : on
before

3. Right now both 'Disabled' and 'Default' button have the same play button. This fixes that.
.........................Default.....................................................................................................................................................Disabled
Screenshot_20240611_201809

### CODE REVIEW

**Comment by fast4x** [comment]
I'll check it soon, thanks

**Comment by fast4x** [comment]
I have applied your improvements, but can't merge directly from this merge request because code in my local repo it's much different and will be commit on next version.
Your solution worked, feature will be available from version 0.6.39

**Comment by NikunjKhangwal** [comment]
I think either me or someone else suggested transparent action bar before. Cool
Would it be possible to make system navigation bar follow the fluid theme as well? Then it would be truly seamless.
IMG_20240615_163924

**Comment by fast4x** [comment]
action bar transparent it's just implemented, find in settings appearance

**Comment by NikunjKhangwal** [comment]
I know. I was saying if Android allow to change system navigation bar background in real time too?

**Comment by fast4x** [comment]
i need to see

**Pull request closed without merging**
