### PR TITLE
new adaptive icon

### PR DESCRIPTION
**Pull request by ikanakova**

### CODE REVIEW

**Comment by fast4x** [comment]
Screenshot_20240121_102611

icon launcher is ok but on splashscreen not

**Comment by ikanakova** [comment]
I'll take a look at it.

**Comment by fast4x** [comment]
In high resolution display the icon is ok

**Comment by fast4x** [comment]
Maybe

**Comment by fast4x** [comment]
Can update this https://github.com/fast4x/RiMusic/blob/master/app/src/main/res/drawable-nodpi/app_icon.xml
Is general icon used internally on settings, background player etc...

**Comment by ikanakova** [comment]
> Can update this https://github.com/fast4x/RiMusic/blob/master/app/src/main/res/drawable-nodpi/app_icon.xml
> Is general icon used internally on settings, background player etc...

I'll update it tonight

**Comment by ikanakova** [comment]
Done - #471

**Pull request merged**
