### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by Mickael81**
I have improved the french translation.

### CODE REVIEW

**Comment by fast4x** [comment]
Hi, you must update it in Crowdin.

**Comment by fast4x** [comment]
Thanks

**Comment by Mickael81** [comment]
No problem. I was trying to help you.
I noticed that Crowdin doesn't always save the translation correctly. I don't know why.
So, I offered you this alternative.
Sorry, if you don't want it.

**Comment by Mickael81** [comment]
As you can see on this screenshot, some elements are not translated and still appear in English on RiMusic.
I have proposed a translation using and saving it on Crowdin. It is clear that it was not taken into account.
Screenshot_20241208_014208
Screenshot_20241208_015303

**Pull request closed without merging**
