### PR TITLE
minor changes

### PR DESCRIPTION
**Pull request by aneesh1122**
1) fixed placeholder and artist name alignment problem
2) fixed wrong spelling of 'carousel'
3) Improved carousel

### CODE REVIEW

**Comment by fast4x** [comment]
Crash androidx.media3.common.IllegalSeekPositionException
in
it.fast4x.rimusic.ui.screens.player.PlayerModernKt$PlayerModern$29$6$2$3$2$2$1.invokeSuspend(**PlayerModern.kt:2250**) 

mediaItems size is less than index passed...

**Comment by aneesh1122** [comment]
> Crash androidx.media3.common.IllegalSeekPositionException
> in
> it.fast4x.rimusic.ui.screens.player.PlayerModernKt$PlayerModern$29$6$2$3$2$2$1.invokeSuspend(**PlayerModern.kt:2250**) 
> 
> mediaItems size is less than index passed...
> 

That's strange. I'm not getting any errors. I'll see what's wrong

**Comment by aneesh1122** [comment]
> Crash androidx.media3.common.IllegalSeekPositionException
> in
> it.fast4x.rimusic.ui.screens.player.PlayerModernKt$PlayerModern$29$6$2$3$2$2$1.invokeSuspend(**PlayerModern.kt:2250**) 
> 
> mediaItems size is less than index passed...
> 

When do you get this crash?

**Comment by fast4x** [comment]
When scroll vertical carousel

**Comment by aneesh1122** [comment]
> When scroll vertical carousel

I never had this issue. The index of pager is also taken from queue media count so that shouldn't happen. does it happen often? Please look into this.

**Comment by fast4x** [comment]
look
https://github.com/user-attachments/assets/81f4f7bf-e425-4529-b687-ada66bee7c38

Log
**2024-07-23T16:58:18.090:	androidx.media3.common.IllegalSeekPositionException**
	 androidx.media3.exoplayer.ExoPlayerImpl.setMediaSourcesInternal(ExoPlayerImpl.java:2329) 
	 androidx.media3.exoplayer.ExoPlayerImpl.setMediaSources(ExoPlayerImpl.java:634) 
	 androidx.media3.exoplayer.ExoPlayerImpl.setMediaItems(ExoPlayerImpl.java:592) 
	 **it.fast4x.rimusic.utils.PlayerKt.forcePlayAtIndex(Player.kt:76)** 
	 **it.fast4x.rimusic.ui.screens.player.PlayerModernKt$PlayerModern$29$6$2$3$2$2.emit(PlayerModern.kt:2247) 
	 it.fast4x.rimusic.ui.screens.player.PlayerModernKt$PlayerModern$29$6$2$3$2$2.emit(PlayerModern.kt:2245)** 
	 kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:11) 
	 kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:11) 
	 kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:113) 
	 kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:82) 
	 androidx.compose.runtime.SnapshotStateKt__SnapshotFlowKt$snapshotFlow$1.invokeSuspend(SnapshotFlow.kt:172) 
	 kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
	 kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) 
	 androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81) 
	 androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41) 
	 androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57) 
	 android.os.Handler.handleCallback(Handler.java:883) 
	 android.os.Handler.dispatchMessage(Handler.java:100) 
	 android.os.Looper.loop(Looper.java:224) 
	 android.app.ActivityThread.main(ActivityThread.java:7590) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by aneesh1122** [comment]
> look
> https://github.com/user-attachments/assets/81f4f7bf-e425-4529-b687-ada66bee7c38
> 
> Log
> **2024-07-23T16:58:18.090:	androidx.media3.common.IllegalSeekPositionException**
> 	 androidx.media3.exoplayer.ExoPlayerImpl.setMediaSourcesInternal(ExoPlayerImpl.java:2329) 
> 	 androidx.media3.exoplayer.ExoPlayerImpl.setMediaSources(ExoPlayerImpl.java:634) 
> 	 androidx.media3.exoplayer.ExoPlayerImpl.setMediaItems(ExoPlayerImpl.java:592) 
> 	 **it.fast4x.rimusic.utils.PlayerKt.forcePlayAtIndex(Player.kt:76)** 
> 	 **it.fast4x.rimusic.ui.screens.player.PlayerModernKt$PlayerModern$29$6$2$3$2$2.emit(PlayerModern.kt:2247) 
> 	 it.fast4x.rimusic.ui.screens.player.PlayerModernKt$PlayerModern$29$6$2$3$2$2.emit(PlayerModern.kt:2245)** 
> 	 kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:11) 
> 	 kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:11) 
> 	 kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:113) 
> 	 kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:82) 
> 	 androidx.compose.runtime.SnapshotStateKt__SnapshotFlowKt$snapshotFlow$1.invokeSuspend(SnapshotFlow.kt:172) 
> 	 kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
> 	 kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) 
> 	 androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81) 
> 	 androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41) 
> 	 androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57) 
> 	 android.os.Handler.handleCallback(Handler.java:883) 
> 	 android.os.Handler.dispatchMessage(Handler.java:100) 
> 	 android.os.Looper.loop(Looper.java:224) 
> 	 android.app.ActivityThread.main(ActivityThread.java:7590) 
> 	 java.lang.reflect.Method.invoke(Native Method) 
> 	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
> 	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 

You're using radio. I already told you that modern players don't work with radio.

**Comment by fast4x** [comment]
ahhhhhhhhhhhhhh you are right... 
sorry I forgot, my work is keeping me very busy.

**Comment by fast4x** [comment]
Tonight I watch why it doesn’t work with the radio

**Comment by aneesh1122** [comment]
> ahhhhhhhhhhhhhh you are right... 
> sorry I forgot, my work is keeping me very busy.

These are all the problems I've found

Problems:
1) You can't align first page with alignment/arrangement commands. You have to provide padding amount for the first page. I tried to find out thumbnail dimensions to give padding values suitable for every device but I was not able to. Therefore I added a custom slider which controls padding. everyone can set the padding according to their wish.

https://github.com/user-attachments/assets/93ed4dab-e124-4838-b338-31ff68e7bc76

2) play a song and put the app in background or turn off the display. wait for the next song to play and let it play for 10-15 secs. Open the player directly now. The song starts from the beginning.

https://github.com/user-attachments/assets/efbb79a1-70e8-4b64-878c-1fcf52a428af



3) It has problem with radio. It crashes when a song's radio is started. Start radio and change to the next song. Crash. Works fine from quick picks.

https://github.com/user-attachments/assets/0a49d593-b934-4bb4-a936-25818c544491



4) previous song starts playing when exit from lyrics in landscape mode

https://github.com/user-attachments/assets/9346349d-a839-45b2-8948-f16ebfa7a66d

**Comment by aneesh1122** [comment]
> Tonight I watch why it doesn’t work with the radio

Pls try to look at other problems too

**Comment by fast4x** [comment]
Fixed 3

**Comment by fast4x** [comment]
2, not reproduced

**Comment by aneesh1122** [comment]
> 2, not reproduced

Song is not playing from start?

Do these steps exactly

1) play a song and skip to last 10 seconds
2) minimize the app to background and wait for the next song to play.
3) let the next song be played for 5-10 seconds.
4) open app by tapping on notification bar

https://github.com/user-attachments/assets/b3b9ce0f-7596-4dae-9f45-27eb1cb4d0e4

Turn on the volume

**Comment by fast4x** [comment]
Fixed 4

**Comment by aneesh1122** [comment]
> Fixed 4

That's great. Thanks man.

Were you able to reproduce 2?

**Comment by fast4x** [comment]
Yes reproduced, but it's complicated to solve

**Comment by aneesh1122** [comment]
> Yes reproduced, but it's complicated to solve 

http://github.com/fast4x/RiMusic/pull/2873#issuecomment-2244626732

See this. Maybe it will give you some ideas

**Pull request merged**
