### PR TITLE
DEMO | Transaction and Query reworks | Offload database handle to background threads

### PR DESCRIPTION
**Pull request by knighthat**
# How `query` and `transaction` were previously used

In previous updates, `query` and `transaction` are called loosely. For example:

```kotlin
query {
    Database.insert(...)
}
```

And

```kotlin
query {
    transaction {
        // Code here
    }
}
```

`query` isn't designed to write records to database because there's no safe guard in place to protect the integrity of records.

However, there's a solution. `transaction` is introduced for this purpose.  `Transaction` will reverse changes if something goes wrong during write operation. And it offers async right from the bat. The code can be re-write as:

```kotlin
Database.transaction {
    insert(...)
}
```

> Notice how `insert()` doesn't require `Database` at the front? That is because `Database.transaction` provides instance of `Database` to any code within the `block` parameter. Checkout [Database.kt](https://github.com/fast4x/RiMusic/pull/4466/files#diff-9b74361fdb9520d6303e0ce42b6ce070be655392a1059559ed6aca0446b4f6cb) for more.

# A class that represents a table

Before, [Database.kt](https://github.com/fast4x/RiMusic/blob/master/composeApp/src/androidMain/kotlin/it/fast4x/rimusic/Database.kt) is about 1,700+ lines. This makes parsing and indexing, not to mention how hard it is to navigate, make changes, and update since it's so cluttered

The problem is there not because of coder's fault, but as long as the complexity of the program grows, it'll only get more and more harder to read/maintain.

To reduce this problem. I introduced classes that represent tables from the database, for example, `SongTable` represents `Song` table. On top of that, an abstract class was also introduced to reduced duplicate codes. Please take a look at [Table<E, K>](https://github.com/fast4x/RiMusic/pull/4466/files#diff-67346c22f684153b507087b6f0be6c49722912472c6417ab2cfc2063f30677a5).

# Offload database queries to background threads

In the beginning, I mentioned that `query` and `transaction` were used loosely, but that's not the only problem. Some of the queries were called directly on Main thread with `runBlocking`. It is not inherently bad, but it will suspend the thread to wait to data from database.

Waiting is relatively small for average size database **<2s**, but it temporary freezes the UI, which leads to bad UX.

During this migration, I actively moved data retrieval from Main thread to IO thread. Effectively, the UI thread is no longer freezes during this operation.

# A little touch on [SortOrder.kt](https://github.com/fast4x/RiMusic/blob/master/composeApp/src/androidMain/kotlin/it/fast4x/rimusic/enums/SortOrder.kt)

### From

```kotlin
@Query("""
    SELECT Artist.* 
    FROM Song 
    JOIN SongArtistMap ON Song.id = SongArtistMap.songId 
    JOIN Event ON Song.id = Event.songId 
    JOIN Artist ON Artist.id = SongArtistMap.artistId 
    WHERE (:to - Event.timestamp) <= :from 
    GROUP BY Artist.id 
    ORDER BY SUM(Event.playTime) DESC 
    LIMIT :limit
""")
fun flowMostPlayedBetween( from: Long, to: Long, limit: Long ): Flow<List<Artist>>

@Query("""
    SELECT Artist.* 
    FROM Song 
    JOIN SongArtistMap ON Song.id = SongArtistMap.songId 
    JOIN Event ON Song.id = Event.songId 
    JOIN Artist ON Artist.id = SongArtistMap.artistId 
    WHERE (:to - Event.timestamp) <= :from 
    GROUP BY Artist.id 
    ORDER BY SUM(Event.playTime) DESC 
    LIMIT :limit DESC
""")
fun flowMostPlayedBetweenDesc( from: Long, to: Long, limit: Long ): Flow<List<Artist>>
```

### To

```kotlin
@Query("""
    SELECT Artist.* 
    FROM Song 
    JOIN SongArtistMap ON Song.id = SongArtistMap.songId 
    JOIN Event ON Song.id = Event.songId 
    JOIN Artist ON Artist.id = SongArtistMap.artistId 
    WHERE (:to - Event.timestamp) <= :from 
    GROUP BY Artist.id 
    ORDER BY SUM(Event.playTime) DESC 
    LIMIT :limit
""")
fun flowMostPlayedBetween( from: Long, to: Long, limit: Long ): Flow<List<Artist>>
```

```kotlin
val ascending = flowMostPlayedBetween( from, now, 1 )
val descending = flowMostPlayedBetween( from, now, 1 ).map { it.reversed() }
```

This cuts the number of sorting functions in half, resulting is less point of failure.

Performance impact is very negligible, unless you have >7 digit number of records, which I highly doubt.

# Minor changes in `@Query` syntax

### From

```kotlin
@Query("SELECT Song.* FROM Event JOIN Song ON Song.id = songId WHERE " +
            "CAST(strftime('%m',timestamp / 1000,'unixepoch') AS INTEGER) = :month AND CAST(strftime('%Y',timestamp / 1000,'unixepoch') as INTEGER) = :year " +
            "GROUP BY songId  ORDER BY timestamp LIMIT :limit")
```

### To

```kotlin
@Query("""
    SELECT Song.* 
    FROM Event 
    JOIN Song ON Song.id = songId 
    WHERE 
        CAST(strftime('%m',timestamp / 1000,'unixepoch') AS INTEGER) = :month 
        AND 
        CAST(strftime('%Y',timestamp / 1000,'unixepoch') as INTEGER) = :year
    GROUP BY songId 
    ORDER BY timestamp 
    LIMIT :limit
""")
```

# What's next

As you can see, this is a work in progress, more tuning is required. A sizeable calls to the database are duplicated, meaning, more point of failure.

I working on a simple function called **_procedure_**. TL; DR - It is steps to manipulate data inside database, with fail-safe actions baked into this function. You already have **_procedure_**, check out [Database.insert( mediaItem, (Song) -> Song)](https://github.com/fast4x/RiMusic/blob/51e4c51ce53001a3c15b7ffd1fef677ab0b434ab/composeApp/src/androidMain/kotlin/it/fast4x/rimusic/Database.kt#L1405-L1438).

Documentation is on the list for sure, can't write code without it, because nobody is gonna understand complex-looking code

> That's all I can think of, comment suggestion if you have any.

### CODE REVIEW

**Comment by fast4x** [comment]
This work is very impressive, i fear only the arrival of unanticipated bugs, given the amount of changes made.

**Comment by knighthat** [comment]
technically, I didn't change anything to create bug. In fact, I added [Table#safeUpsert()](https://github.com/knighthat/RiMusic/blob/06944e4c1114a5822af1299307d5374f0b35b201/composeApp/src/androidMain/kotlin/me/knighthat/database/table/Table.kt#L57-L62) which is supposed to be safer since it ignores error and preserves data integrity

**Comment by knighthat** [comment]
> In my opinion you add complexity to the code

Can you give me an example? 

1. I cut the number of sorting functions in half by leveraging built-in `List#reversed()`. It decreases points of failure by half. 
2. I moved workload to other threads by using your `Flow#collect( CoroutineScope() ) {}` function. Located [HERE](https://github.com/fast4x/RiMusic/blob/master/composeApp/src/androidMain/kotlin/it/fast4x/rimusic/utils/CoroutineExtensions.kt)
3. I replaced tradition `@Upsert` which throws error if anything happens with a [safer approach](https://github.com/knighthat/RiMusic/blob/06944e4c1114a5822af1299307d5374f0b35b201/composeApp/src/androidMain/kotlin/me/knighthat/database/table/Table.kt#L57-L62)

Up until this point, nothing I've made add complexity if not decrease it. 

> If your goal is to fix transactions and queries, fix them without complicating the code.

I did, which is mentioned in the first section

If you still only want the rework on `transaction` and `query`, you can **cherry-pick** commits before [converted to Database#transaction](https://github.com/fast4x/RiMusic/pull/4466/commits/15c92d8379df391fd82af59d75e63dbc82408f80) and resolve all conflicts

**Comment by fast4x** [comment]
SongTable etc... database.migrator...

**Comment by knighthat** [comment]
> SongTable etc... database.migrator...

They are all code from [Database.kt](https://github.com/fast4x/RiMusic/blob/master/composeApp/src/androidMain/kotlin/it/fast4x/rimusic/Database.kt). I just copied/pasted them. Explained in "**_A class that represents a table_**" section.

I get where you're coming from, but I like to think that programming is like building Lego, you don't want to glue all of them together or make specific block for 1 purpose but rather reusing/arranging what you already have to create the shape you want.

Again, I'll keep it because it's going to my [KBuild](https://github.com/knighthat/RiMusic/tree/kbuild) - my personal build. If you still want the `transaction` and `query` fix, feel free to pick it from this PR. I am happy guide you to do so.

**Comment by knighthat** [comment]
You know what @fast4x, I'll open another PR just for the `query` and `transaction` some time tomorrow. Let me know if you want other features to be pushed. For example, switching to `List#reversed` instead of having another `@Query` just to add `DESC`

**Comment by fast4x** [comment]
As I said, you don’t need to "rewrite" the code.

**Pull request closed without merging**
