### PR TITLE
Remove navigation bar in Playlist & Album screens

### PR DESCRIPTION
**Pull request by knighthat**
# Description

Having a navigation bar at the bottom only adds obstruction to the FOV.

I have a shorter screen (LG K40) that still has the bottom bar acts like buttons (back, home, tasks) instead of the screen so that one, and bottom navigation bar and the player together take up about 1/3 of the screen in portrait mode and almost half of the screen in landscape mode

# Solution 

Moving core components outside of Scaffold will fix this issue

# Note

1. Let me know if you need me to add a toggle in the settings
2. I'm planning to do some makeover to the Scaffold to make it more modular (current design is kinda bloated). If you're interested, I'll open a draft and we'll go from there

# Visual representation

<p align="center">
Before
After
</p>

### CODE REVIEW

**Comment by fast4x** [comment]
- No, toggle not required  
- Ok but be very careful that changing the scaffold, the menu move on the 4 sides and the ViMusic mode remain intact.

**Comment by knighthat** [comment]
@fast4x I'm looking for a way atm because the code is heavily nested. I may need to open another branch so we can test it while maintaining the old structure

**Comment by fast4x** [comment]
Ok

**Comment by knighthat** [comment]
Is this ready to merge?

**Comment by aneesh1122** [comment]
this is great. have you removed navigation bar for online playlists too?

**Comment by fast4x** [comment]
> this is great. have you removed navigation bar for online playlists too?

not yet

**Comment by fast4x** [comment]
i like that you have created a separated files... nice this is correct...

**Pull request merged**
