### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by siggi1984**
Improved some translations.

### CODE REVIEW

**Comment by fast4x** [comment]
Merged :)

**Comment by fast4x** [comment]
German Is your native language?
I add your name in the info page of RiMusic

**Comment by siggi1984** [comment]
> German Is your native language? I add your name in the info page of RiMusic

My native language is Russian but I live in Germany. If you want I can also add the Russian language. Would possibly increase the user audience of the app.

**Comment by fast4x** [comment]
I would say it would be nice to include Russian since it is also your language.

**Pull request merged**
