### PR TITLE
Bug fixes with bitmap provider

### PR DESCRIPTION
**Pull request by Abhinavreddy-B**
This mainly solves the problem on thumbnail not visible in widgets.

It might also solve issues where thumbnails are being fetched using `binder.bitmap` (though I couldn't find any such places from what I understood). 

The reason was binder is never being loaded with new bitmap. so, I added the binder bitmap update logic in `onMediaItemTransition` in `Player`

### CODE REVIEW

**Comment by twistios** [comment]
I am testing your changes and I can confirm that the image loads in the widget. But only once the "play-button" is selected. So if the song is changed only, then the old thumbnail remains.

**Comment by Abhinavreddy-B** [comment]
Ohh, ok, will make sure it works.

**Comment by Abhinavreddy-B** [comment]
Now it should be working

**Comment by fast4x** [comment]
Nice

**Pull request merged**
