### PR TITLE
added swipe to see next thumbnail in full screen cover mode

### LINKED ISSUE #2667: Swipe to see the thumbnail of the next song
### Description

https://github.com/fast4x/RiMusic/assets/45353488/29b9778d-e520-4c2b-8fc6-5039bfb7a08b

These are only screenshots. Just to give you an idea.
Since we have swipe gestures now, is it possible to implement something similar for thumbnail?

### Suggested Solution

Swipe a little bit to see the next song's cover and swipe completely to go to the next song

### Alternatives

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by aneesh1122**
fixes #2667

### CODE REVIEW

**Comment by aneesh1122** [comment]
@fast4x I was trying to implement https://github.com/fast4x/RiMusic/issues/1321 but I'm not able to. The app is crashing. Need to change thing in database.

Please try to implement this. I've requested it 4 months ago

**Comment by fast4x** [comment]
Database not must change at least for now

**Comment by aneesh1122** [comment]
> Database not must change at least for now

I'm not sure if it require changing database. could you look at it once?

```
filteredSongs = songs
                .filter {
                    it.title.contains(filterCharSequence,true) ?: false
                            || it.artistsText?.contains(filterCharSequence,true) ?: false
```

this is the code which filters songs.

**Comment by fast4x** [comment]
thi not require database

**Comment by aneesh1122** [comment]
> this not require database

that's what I thought. I just assumed it will require database. will you look at it?

**Comment by fast4x** [comment]
I'll check it

**Comment by aneesh1122** [comment]
> I'll check it

Okay. Thanks

**Pull request merged**
