### PR TITLE
Changes in 'Disabled' Player button, added 'Play button' also for 'Modern' Controls type and fixed multiple or no like button for both essential and modern types

### PR DESCRIPTION
**Pull request by aneesh1122**
1) Now the 'Disabled' player button in essential controls type has only play/pause button without background square. Those who want play/pause button with square can choose 'Default' button.

2) added 'Play button' options also for 'Modern' Controls type

3) There will be only one like button always no matter which info type of control you choose.
i. Modern Info + Essential Controls
Modern Info + Essential Controls

ii. Essential info + Modern controls
Essential Info + Modern Controls

Look at 3rd,4th and 5th files for new changes

### CODE REVIEW

**Comment by aneesh1122** [comment]
Hey @fast4x this pull has some new additions. Please check it out once.

**Comment by aneesh1122** [comment]
Hey @fast4x this pull has some new additions. Please check it out once

**Comment by fast4x** [comment]
Hi, remove old commit please, and how look with info modern + controls modern?

**Comment by aneesh1122** [comment]
> remove old commit please

I don't know how to do that. I'm still learning 😅

btw here is modern info + modern controls

**Comment by fast4x** [comment]
I have added your code but i can't merge it for same reason before this merge.
Not to do other implementation until next release, much code isn't the same.
I'll add your name in the developer collaborator, thanks.

**Comment by fast4x** [comment]
Available from version 0.6.39

**Comment by aneesh1122** [comment]
Hey @fast4x , I won't create a new pull request now, just wanted to show you something

https://github.com/fast4x/RiMusic/assets/45353488/a9965000-a2fb-4466-b3e5-3fed2869e562

**Pull request closed without merging**
