### PR TITLE
Right swipe is 'Play next' and left swipe is 'delete' in queue and 'like' everywhere else

### LINKED ISSUE #2664: next in line
### Description

Just in this update they brought actions very similar to Spotify (which we love)

### Suggested Solution

but I feel it would be better if:

If the list buttons were swapped, the heart button, put it next in the queue, and next in the queue heart/like

Picsart_24-07-06_14-44-11-535
Picsart_24-07-06_14-44-33-503

and the tail ones also changed from left to right, and from right to left.

Picsart_24-07-06_14-44-53-010

### Alternatives

That's more or less how we at Spotify are used to it, and personally I think it's the best way to accommodate it.  It is personal belief.  or make a button to choose actions.  anyway THANKS FOR THE UPDATE

### Additional Context

_No response_

### LINKED ISSUE #2699: [Feature]: Possible to choose actions when swiping left or right?
### Description

This is a feature request to have the option to customize the swipe left or swipe right actions for songs in the current queue.

### Suggested Solution

I am so glad to see swiping back!

Maybe this is a feature request, or maybe it's just a question, but is there a way to choose the action when swiping left or right? 

Currently, swiping left removes from the queue, and swiping right adds to favorites. For me, the swipe left action is just fine, but I would love an option to swipe right and add to next in the queue.

Maybe the ability to do this is already in the settings and I'm not seeing it. If it's not, then choosing the actions when swiping left/right is a feature request.

Thanks for all your work!

### Alternatives

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by aneesh1122**
Fixes #2699 
Fixes #2664

### CODE REVIEW

**Comment by aneesh1122** [comment]
I also tried to implement "swipe left to remove from playlist" and I was able to implement it for local playlists but for piped playlists songs are not deleting through left swipe. 

I have not uploaded that code in github. will you look at the code?

**Comment by fast4x** [comment]
yes

**Comment by EricAykays** [comment]
Hey, can you please set Right swipe as add to queue? Or could you just add an option to select the action upon swipe.

**Comment by aneesh1122** [comment]
> Hey, can you please set Right swipe as add to queue? Or could you just add an option to select the action upon swipe.

Maybe in the future. It will require a lot of time since swipe options differ with places like the queue has different set of options compared to search results.

**Comment by EricAykays** [comment]
> > Hey, can you please set Right swipe as add to queue? Or could you just add an option to select the action upon swipe.
> 
> Maybe in the future. It will require a lot of time since swipe options differ with places like the queue has different set of options compared to search results.

Oh okay, hopefully we'll see it in the future

**Pull request merged**
