### PR TITLE
reorder > clickable area improvement

### PR DESCRIPTION
**Pull request by martkol**
Clickable area difficult to reach > Better solution to the last one > Icon size is again the same as others in the project > Box which moves the clickable area in front of the IconButton created.

There are no visible changes, the clickable area is now directly behind the icon.

### CODE REVIEW

**Comment by martkol** [comment]
@aneesh1122 @fast4x can you check if the long press function works fine? in my emulator it works only when song playback is stopped. 
Even if I emulate the status before my changes of today, this is still the case.

**Comment by fast4x** [comment]
@aneesh1122 yes ot work nice
@martkol nice work

**Comment by aneesh1122** [comment]
> @aneesh1122 @fast4x can you check if the long press function works fine? in my emulator it works only when song playback is stopped.

ever since swipeable gestures and discover were implemented there have been some problems with long press. will look into it later

**Comment by fast4x** [comment]
I prepare new release...

**Pull request merged**
