### PR TITLE
Disabled codes for Discover. too buggy for release

### PR DESCRIPTION
**Pull request by aneesh1122**
1) queue discover is working but it's interfering with swipe.

2) Player discover is deleting next 2 songs instead of one. I tried different ways to access database without crashing but the results were same.

### CODE REVIEW

**Comment by fast4x** [comment]
Ok, good idea, i haven't time for now to resolve this bug.

**Comment by aneesh1122** [comment]
> Ok, good idea, i haven't time for now to resolve this bug.

Pls try to resolve this bug whenever you get time. No unofficial Youtube streaming app has this option to exclude liked and playlists songs. if this gets implemented it will make RiMusic unique.

**Comment by aneesh1122** [comment]
> If I can get free, I promise I’ll work on it.

I'm getting this error sometimes when songs are getting deleted in queue after activating 'discovery'. Could you pls tell me what's the problem

2024-07-18T01:07:33.224:	java.lang.IllegalArgumentException: measure is called on a deactivated node
	 v8.d.T(SourceFile:3) 
	 H0.K.s0(SourceFile:208) 
	 H0.K.b(SourceFile:91) 
	 E.V.b(SourceFile:56) 
	 C.r.b(SourceFile:21) 
	 f6.a.Z(SourceFile:11) 
	 C.s.j(SourceFile:593) 
	 B.x.j(SourceFile:954) 
	 F0.E.g(SourceFile:74) 
	 H0.u.b(SourceFile:38) 
	 p0.W.i(SourceFile:1) 
	 H0.A.b(SourceFile:15) 
	 A0.b.a(SourceFile:381) 
	 c7.c.z(SourceFile:114) 
	 g0.t.a(SourceFile:52) 
	 g0.u.c(SourceFile:140) 
	 H0.m0.a(SourceFile:3) 
	 H0.K.s0(SourceFile:133) 
	 H0.F.M(SourceFile:17) 
	 H0.T.c(SourceFile:3) 
	 H0.T.k(SourceFile:102) 
	 I0.y.y(SourceFile:8) 
	 H0.F.k(SourceFile:41) 
	 B0.J.b(SourceFile:1659) 
	 y.r.a(SourceFile:17) 
	 y.J0.a(SourceFile:65) 
	 w.n.b(SourceFile:248) 
	 y.E0.a(SourceFile:42) 
	 E.T.b(SourceFile:50) 
	 v.d.k(SourceFile:55) 
	 F6.y.b(SourceFile:41) 
	 i.b(SourceFile:18) 
	 V.g.c(SourceFile:39) 
	 V.p0.b(SourceFile:28) 
	 I0.e0.doFrame(SourceFile:7) 
	 I0.c0.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1503) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1513) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1128) 
	 android.view.Choreographer.doFrame(Choreographer.java:1037) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1481) 
	 android.os.Handler.handleCallback(Handler.java:942) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:211) 
	 android.os.Looper.loop(Looper.java:300) 
	 android.app.ActivityThread.main(ActivityThread.java:8503) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by fast4x** [comment]
I took a look, I’m working on it tomorrow.

**Comment by aneesh1122** [comment]
> I took a look, I’m working on it tomorrow.

Okay. btw the last time I was using .Distinct() which was giving errors.

The correct code is .distinct() but it's still not working.

**Comment by fast4x** [comment]
Implemented, it can be turned on/off from the action bar of the player, the queue, or the settings. The setting has been moved to the ui section because it is not about appearance, it is a feature.

As soon as it is activated it removes in real time the favorite songs and those present in the playlists.

Available from version 0.6.44

**Comment by aneesh1122** [comment]
> Implemented, it can be turned on/off from the action bar of the player, the queue, or the settings. The setting has been moved to the ui section because it is not about appearance, it is a feature.
> 
> As soon as it is activated it removes in real time the favorite songs and those present in the playlists.
> 
> Available from version 0.6.44

you actually implemented it? dude you're the best. any chance I can get the debug apk or custom apk?

**Comment by fast4x** [comment]
Please download custom version

**Comment by fast4x** [comment]
> > Implemented, it can be turned on/off from the action bar of the player, the queue, or the settings. The setting has been moved to the ui section because it is not about appearance, it is a feature.
> > 
> > As soon as it is activated it removes in real time the favorite songs and those present in the playlists.
> > 
> > Available from version 0.6.44
> 
> you actually implemented it? dude you're the best. Thanks.
> 
> will it work everytime or only if you're using radio?

it work on queue so with all functions included radio..

**Comment by fast4x** [comment]
Add pull request

**Comment by aneesh1122** [comment]
> Yes blur it's nice... 😂

why do you want to blur the thumbnail when there is no thumbnail? 😂

Should I add an option to not blur the thumbnail when lyrics are not enabled?


> Add pull request for player.currentMediaItemIndex
okay

**Pull request merged**
