### PR TITLE
Add shuffle button to Android Auto player UI

### PR DESCRIPTION
**Pull request by ov1d1u**
This PR adds a shuffle button to the Android Auto UI. It appears instead of the download button, which is now moved at the end of the action buttons.

Also added an icon based on the shuffle.xml asset to indicate when the shuffle feature is active:

Screenshot 2024-05-28 at 14 02 46

### CODE REVIEW

**Comment by fast4x** [comment]
Hi thanks for your times, i have some questions:

1. why have replaced download button with it?
2. you want show shuffle only if download/like buttons are disabled in settings?
3. why you have used a new icon if it exixts (shuffle.xml)
4. why you intend a shuffle action in selected state? (shuffle is a one click action...)

**Comment by fast4x** [comment]
Remember that changing icons before android auto will be visible in the background player... 
This will change actual order icon... default visible action are download and like... 
I think is good if you add shuffle after play radio, will be available also in android auto in three dots menu.

**Comment by ov1d1u** [comment]
1. In a car environment, I find it more useful to have a shuffle button than a download button. Personally, and I think this also applies for multiple users (#1172), I'm more interested in not having a predictable queue of songs (e.g. when playing a playlist) than to download songs while I'm driving.
2. This implementation doesn't depend on any settings related to download/like buttons. Disabling these buttons have no impact on the availability of the shuffle button. I'm not sure how the shuffle button should be affected by those settings.
3. So you can know if the function is active or not. YouTube Music does this by adjusting the transparency of the button, but I couldn't achieve that since I'm not very experienced with Android development. Any help here would be appreciated.
4. You can enable or disable shuffling (`player.shuffleModeEnabled`), and the button wants to illustrate that.

I don't mind adding it after the play radio button, but I still find a download button in the Android Auto UI a bit inappropriate.

**Comment by fast4x** [comment]
Great, I like your answers, I do a couple of tests and merge. Thanks.

**Comment by fast4x** [comment]
I have extended your code to make it compatible with all versions of android and android auto supported by the app. 
Now I merge, I’ll let you know as soon as I complete the process

**Comment by fast4x** [comment]
Merged, available from version 0.6.37

**Pull request merged**
