### PR TITLE
Customise swipe actions

### PR DESCRIPTION
**Pull request by Abhinavreddy-B**
Issue #4849

### CODE REVIEW

**Comment by Abhinavreddy-B** [comment]
I need suggestions on what icon can we put for No Action.

**Comment by aneesh1122** [comment]
Have you implemented it only for queue?

Also, there are different pages like local playlists, online playlists, albums, songs tab.

I've set the right swipe to play next everywhere and for local playlists and queue left swipe deletes the songs and where ever it's not possible to delete the song it unlikes the song(like albums, online playlists)

Would be nice if there were separate options for 

1)Right swipe(local playlists and queue) :-
Can add delete here

2)Right swipe(everywhere else) :-
Can't add delete here

3)Left swipe(local playlists and queue)
Can add delete here

4)Left swipe(everywhere else)
Can't add delete here

I know it's too much hard work that's why I didn't add these options and went with what most people would use for swipe.

**Comment by fast4x** [comment]
I think that customized actions in swipeable content must be not specific for queue but also for others swipeable content component.
I think also that isn't a priority... :)

**Comment by fast4x** [comment]
Yes I agree, for now let's not do refactoring, too dangerous. I would tie the swipe in the queue to the lock, when the lock is open the swipe works.

**Comment by fast4x** [comment]
At this point I would say to add it, maybe this merge we will do after the release. I recommend not to "rewrite the wheel", only essential changes no code re-engineering.

**Comment by Abhinavreddy-B** [comment]
These are the final options i am thinking of:

For Queue and Local playlist:
1. NoAction,
2. PlayNext,
3. Download,
4. Favourite,
5. RemoveFromQueue

For Online playlists, albums, individual songs etc (al the online ones):
1. NoAction
2. PlayNext
3. Download
4. Favourite
5. Enqueue

For Album (when searching ig):
1. NoAction
2. PlayNext
3. Bookmark
4. Enqueue


do tell me if I am missing anything.

@aneesh1122 @fast4x

**Comment by aneesh1122** [comment]
I think it's perfect but since you are adding enqueue as an option, for the consistency sake can you add enqueue option also to local playlists options?

**Comment by Abhinavreddy-B** [comment]
> I think it's perfect but since you are adding enqueue as an option, for the consistency sake can you add enqueue option also to local playlists options?

I thought of it, but the problem is same component is being used for queue and for local playlist. so adding that option only for local playlist will have to split into 2 components, and also add 2 new settings for customizing them.

**Comment by Abhinavreddy-B** [comment]
Or maybe we can use the 2nd component for local playlist also. in that case delete option wont be there for local playlist. Only Queue will have delete action. 

if that is fine, I can do that

**Comment by fast4x** [comment]
Use two components, it's better in debug...

**Comment by aneesh1122** [comment]
> Or maybe we can use the 2nd component for local playlist also. in that case delete option wont be there for local playlist. Only Queue will have delete action. 
> 
> if that is fine, I can do that

When I asked about adding it in local playlists I included the queue too since both of them are using the same component.

Right now the queue doesn't have the 'enqueue' option in the long tap bottom sheet but I can see enqueue as an option for the queue too. It's not important though so leave it for now.

Please go ahead with your plans.

**Comment by aneesh1122** [comment]
> Use two components, it's better in debug...

You mean total 2 components? It won't be possible man.

Albums have entirely different actions so it needs a component of its own.

If you mean different components for queue and local playlists then I don't think it's worth  it. Either add enqueue option to the component which is used by both local playlists and queue so that both of them end up having the enqueue option or just drop the idea and let him continue with his plan.

**Comment by Abhinavreddy-B** [comment]
> If you add enqueue to local playlists the queue will end up having that too. Right now the queue doesn't have the 'enqueue' option in the long tap bottom sheet but I can see enqueue as an option for the queue too. It's not important though so leave it for now.

enqueue option in queue sounds a bit weird, but ya people can use it to enqueue already played songs from the queue. that sounds fine for me. 
Will add enqueue option for Queue and local playlists as well

**Comment by Abhinavreddy-B** [comment]
> Use two components, it's better in debug...

I agree with aneesh, its not worth it to just have 2 separate components with almost same functionality. this will require separate settings option for each, separate enums, separate preference keys. 
For now I will just add enqueue for both and use the same for both. in case really there is a need for separation in future, we can do it at that time.

**Comment by fast4x** [comment]
If only enqueue is valid for both, ok

**Comment by Abhinavreddy-B** [comment]
Wanted a suggestion on the setting entry for 2nd category, (i.e everything except queue and local playlist) 

currently it is named as playlist swipe action, but it is not just for playlist, it for for anywhere a list of songs appear, like in album, search results, artist page, playlist, podcast, etc. so we need a better name

**Comment by aneesh1122** [comment]
> everything except queue and local playlist

This will do. Just use this

And try to add 'all' padding to decrease the icon's size.

**Pull request merged**
