### PR TITLE
Added an option to show both original and translated lyrics at the same time

### LINKED ISSUE #1357: [Feature]: Dual lyrics translation
### Description

Now you can't manually scroll on the lyrics page, and when translating lyrics, the original language display cannot be retained.

### Suggested Solution

Add dual-language display for lyrics, restore manual scrolling on the lyrics page.

### Alternatives

_No response_

### Additional Context

_No response_

### LINKED ISSUE #3359: [Feature]: Lyrics with translated lyrics
### Description

SimpMusic provides [this](https://github.com/maxrave-dev/SimpMusic/blob/jetpack_compose/asset/screenshot/4.png?raw=true) useful feature where you can read both the lyrics of the song that you are listening and the translated lyrics. I find this extremely useful to learn new words.

### Suggested Solution

Basically the same solution that SimpMusic already provides, when reading the lyrics of the song, the translated lyrics under them.

### Alternatives

I'm not sure if this feature is already implemented, but I tried searching it on the app settings and if there's some issue already requesting this feature and I couldn't find anything.

### Additional Context

Thank you so much for creating RiMusic.

### PR DESCRIPTION
**Pull request by aneesh1122**
Closes #3359
Closes #1357

### CODE REVIEW

**Comment by aneesh1122** [comment]
https://github.com/user-attachments/assets/7246d1eb-1705-42b9-b1cb-0c19ac5821b7

**Comment by fast4x** [comment]
maybe you are crazy more then me 🤣 
Thanks

**Comment by Terkyz** [comment]
Is this already merged in the latest release? And it would be useful is this feature can be automatically applied without going to activating it each time.

**Comment by aneesh1122** [comment]
> Is this already merged in the latest release?

sigh
when was the latest version released? 3 days ago
when was this pull request accepted? a few hours ago.

how possibly can it be merged in the latest release? do you think I have a time machine?



> And it would be useful is this feature can be automatically applied without going to activating it each time.

well, you will just have to wait to find out.

**Pull request merged**
