### PR TITLE
added statsfornerds for no thumbnail condition, disabled numbers from sliders

### LINKED ISSUE #2742: Quick option to change song quality
### Description

Additional quick option under seek bar for bitrate and audio quality.

### Suggested Solution

It should show song quality and bitrate in full screen player under seek bar like in image(edited). As in full screen we can't get song information, taping the quality/bitrate under seek bar can act as multipurpose option e.g. 1.single click to change audio quality.
2. Tap and hold to get additional info like Id,tag,bitrate,size,cached and Loudness etc.
IMG_20240713_234150

### Alternatives

_No response_

### Additional Context

_No response_

### LINKED ISSUE #2745: Pitch and tempo button
### Description

Pitch and tempo controls text are barely readable
Screenshot_20240714-135243_Pixel Launcher

### Suggested Solution

Make the text color to white

### Alternatives

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by aneesh1122**
Fixes #2742 

https://github.com/user-attachments/assets/993fba0d-75bb-41f2-8685-9eed965a7250

Fixes #2745

### CODE REVIEW

**Comment by aneesh1122** [comment]
@fast4x I'm trying to delete playlist songs from queue and this is my code. 
studio64_wudaYAmyqj

apk is created without any errors but when I open the app and open queue, this happens

**Comment by fast4x** [comment]
Ok thanks for notice, now check it

**Comment by aneesh1122** [comment]
> Ok thanks for notice, now check it

This code is not in the app. I added this code this morning. I'm trying to remove playlist songs from the queue.

Please tell me what I'm doing wrong.

**Comment by fast4x** [comment]
So it's not present in this merge, correct? This merge it's ok..?

**Comment by aneesh1122** [comment]
> So it's not present in this merge, correct? This merge it's ok..?

This merge is perfect. There is no problem in this merge.

**Comment by fast4x** [comment]
> @fast4x I'm trying to delete playlist songs from queue and this is my code. studio64_wudaYAmyqj
> 
> apk is created without any errors but when I open the app and open queue, this happens
> 
>  Screenrecorder-2024-07-15-12-44-48-738.mp4

code is wrong, for delete item from queue you must search window with mediaId, songPlaylist contain only count in how much playlist contain song...

**Comment by aneesh1122** [comment]
> > @fast4x I'm trying to delete playlist songs from queue and this is my code. studio64_wudaYAmyqj
> > apk is created without any errors but when I open the app and open queue, this happens
> > Screenrecorder-2024-07-15-12-44-48-738.mp4
> 
> code is wrong, for delete item from queue you must search window with mediaId, songPlaylist contain only count in how much playlist contain song...

can you tell me the correct code? I'm trying this because It's very important to me. Most of the recommended songs in radio are from my playlists and favorites and I want to discover new songs.

**Comment by aneesh1122** [comment]
> > @fast4x I'm trying to delete playlist songs from queue and this is my code. studio64_wudaYAmyqj
> > apk is created without any errors but when I open the app and open queue, this happens
> > Screenrecorder-2024-07-15-12-44-48-738.mp4
> 
> code is wrong, for delete item from queue you must search window with mediaId, songPlaylist contain only count in how much playlist contain song...

I've finally done it. I used this code
```
if (songPlaylist > 0) {
                            player.removeMediaItem(currentItem.firstPeriodIndex)
                        }
```

How can I do the same with liked songs?

**Comment by fast4x** [comment]
use similar func Database.songliked(songId)

**Comment by aneesh1122** [comment]
> use similar func Database.songliked(songId)

is there any way I can deleted repeated songs in queue? Like if a song is already there then the same song shouldn't reappear in queue

**Comment by fast4x** [comment]
it's just managed when you add somthing to queue...

**Comment by aneesh1122** [comment]
> it's just managed when you add somthing to queue...

while playling radio the songs are repeated. After 49th song in radio queue you can find many repeated songs.

**Comment by fast4x** [comment]
2024-07-15_11h44_21
it's managed in addnext...not in enqueue...
look at utils > Player

**Comment by aneesh1122** [comment]
> it's managed in addnext...not in enqueue

Okay I'll try to add this. one last thing. How can I exclude the first queue song from removing? I'm having some problems when I start queue with a song which is already in my playlist.

**Comment by fast4x** [comment]
if (indexOfSong) > 0 delete...

p.s. next release, i've added a special thanks for you in Acknowledgments

**Comment by aneesh1122** [comment]
> next release, i've added a special thanks for you in Acknowledgments

Thanks man :)



> it's managed in addnext...not in enqueue

I tried but it's complicated. Let's leave it for some other day



> (indexOfSong)

This variable doesn't exist. I tried with `mediaItemIndex` but that also isn't working. Is there an index specifically for Queue?

**Comment by fast4x** [comment]
indexOfSong is an example...

**Comment by aneesh1122** [comment]
> indexOfSong

I understood that. At first I thought it's actually a pre-defined variable. So please tell me how I can exclude the first song from getting deleted?

**Comment by aneesh1122** [comment]
Solved this problem

The code
```
if (discover && currentItem.firstPeriodIndex > 1 && (songPlaylist > 0 || songLiked > 0)) {
                            player.removeMediaItem(currentItem.firstPeriodIndex)
                        }
```

**Comment by aneesh1122** [comment]
Now @fast4x , the most important and the most complicated thing, how can I make this 'Discover' thing work only with radio? Right now it's also applying to playlist queue songs.

**Comment by aneesh1122** [comment]
I'm having a problem and I've spent hours fixing this but I'm not able to fix


https://github.com/user-attachments/assets/c65b27da-121d-4ed3-9a2d-a2f4462c0e08

When I Play "Payphone" only "Blank Space" should be deleted but it is also deleting "Just the way you are"

Here is the code
```
var songPlaylist1 by remember {
            mutableStateOf(0)
        }
        LaunchedEffect(Unit, nextMediaItem.mediaId) {
            withContext(Dispatchers.IO) {
                songPlaylist1 = Database.songUsedInPlaylists(nextMediaItem.mediaId)
            }
        }

        var songLiked by remember {
            mutableStateOf(0)
        }
        LaunchedEffect(Unit, nextMediaItem.mediaId) {
            withContext(Dispatchers.IO) {
                songLiked = Database.songliked(nextMediaItem.mediaId)
            }
        }
        var discover by rememberPreference(discoverKey, false)

        if (discover && (songPlaylist1 > 0 || songLiked > 0)) {
            binder.player.removeMediaItem(nextMediaItemIndex)
        }
```

What am I doing wrong?

**Comment by aneesh1122** [comment]
**What's working?**

https://github.com/user-attachments/assets/2c0ab7ff-4016-4a4c-85ec-3cd396afd0a9

as soon as you open the queue, all the songs inside the queue window will be deleted which is in your playlist or liked 

**What's not working?**
1) You need to scroll down the whole queue for the songs to get deleted. Notice the number of songs in the queue in the above video. only the songs visible in the window are getting deleted

2) You need to open the queue to delete the songs. I tried to implement deleting the songs without opening the queue but I'm having this problem. Look at this comment https://github.com/fast4x/RiMusic/pull/2752#issuecomment-2230122524

3) I'm not able to delete repeated songs in queue. I tried this code but it's not working
```
fun findMediaItemIndexById(mediaId: String): Int {
                            for (i in 0 until binder.player.mediaItemCount) {
                                if (binder.player.getMediaItemAt(i).mediaId == mediaId) {
                                    return i
                                }
                            }
                            return -1
                        }
                        val itemIndex = findMediaItemIndexById(window.mediaItem.mediaId)

if (discover && currentItem.firstPeriodIndex > 0 && (songPlaylist > 0 || songLiked > 0)) {
 if (itemIndex > 0) player.removeMediaItem(itemIndex)
                        }
```

4) After adding songs deleting code the swipe and longclick is having some problems

@fast4x I can't do anything more without your help.

**Comment by fast4x** [comment]
Instead of deleting the double, make sure you don’t add doubles. Go to the code when adds the songs in queue like player.addNext, enqueue etc....  and add  .Distinct()

**Comment by aneesh1122** [comment]
> Instead of deleting the double, make sure you don’t add doubles. Go to the code when adds the songs in queue like player.addNext, enqueue etc.... and add .Distinct()

`kotlin/it/fast4x/rimusic/utils/YoutubeRadio.kt` is responsible for adding radio songs. How can I add the .Distinct() code there so that songs in my playlists, likes and queue are not added?

**Comment by aneesh1122** [comment]
studio64_tnAXQVXJnx

This is where radio adds songs if you are listening to 3rd song from bottom. How do I add .Distinct() here?

**Comment by fast4x** [comment]
try 
radio.process().Distinct()
or 
in same logic add it inside func addMediaItems()

**Comment by fast4x** [comment]
> I'm having a problem and I've spent hours fixing this but I'm not able to fix
> 
>  RiMusic.mp4 
> When I Play "Payphone" only "Blank Space" should be deleted but it is also deleting "Just the way you are"
> 
> Here is the code
> 
> ```
> var songPlaylist1 by remember {
>             mutableStateOf(0)
>         }
>         LaunchedEffect(Unit, nextMediaItem.mediaId) {
>             withContext(Dispatchers.IO) {
>                 songPlaylist1 = Database.songUsedInPlaylists(nextMediaItem.mediaId)
>             }
>         }
> 
>         var songLiked by remember {
>             mutableStateOf(0)
>         }
>         LaunchedEffect(Unit, nextMediaItem.mediaId) {
>             withContext(Dispatchers.IO) {
>                 songLiked = Database.songliked(nextMediaItem.mediaId)
>             }
>         }
>         var discover by rememberPreference(discoverKey, false)
> 
>         if (discover && (songPlaylist1 > 0 || songLiked > 0)) {
>             binder.player.removeMediaItem(nextMediaItemIndex)
>         }
> ```
> 
> What am I doing wrong?

delete alway from big index to small...
delete one item, cause index renumber of entire list...

**Comment by aneesh1122** [comment]
> radio.process().Distinct()
studio64_Kfu8Qrt9fz

> in same logic add it inside func addMediaItems()
addMediaItems() belongs to a read-only file. It's also not an item
studio64_QSFyARrFNm

**Comment by fast4x** [comment]
inside... func.... where are items...

**Comment by aneesh1122** [comment]
> inside... func.... where are items...



> inside... func.... where are items...

addMediaItems are used only like 3-4 places and .Distinct() is not working anywhere. It's always throwing errors.

**Comment by aneesh1122** [comment]
> delete one item, cause index renumber of entire list...

I only want to delete one item. It's actually deleting 2 songs I don't know why

**Comment by fast4x** [comment]
@aneesh1122 I'll look on it

**Comment by aneesh1122** [comment]
I've deleted the code of removing double songs from queue. should I do the pull request of whatever I have done?

**Comment by fast4x** [comment]
if it work, ok...

**Comment by aneesh1122** [comment]
> if it work, ok...

It's working fine in queue window. The problem is there in player as I showed you in https://github.com/fast4x/RiMusic/pull/2752#issuecomment-2230122524

**Comment by fast4x** [comment]
> > if it work, ok...
> 
> It's working fine in queue window. The problem is there in player as I showed you in https://github.com/fast4x/RiMusic/pull/2752#issuecomment-2230122524

explain better what's problem exactly... sorry

**Comment by aneesh1122** [comment]
> > > if it work, ok...
> > 
> > 
> > It's working fine in queue window. The problem is there in player as I showed you in [#2752 (comment)](https://github.com/fast4x/RiMusic/pull/2752#issuecomment-2230122524)
> 
> explain better what's problem exactly... sorry

This is the code
```
var songPlaylist1 by remember {
            mutableStateOf(0)
        }
        LaunchedEffect(Unit, nextMediaItem.mediaId) {
            withContext(Dispatchers.IO) {
                songPlaylist1 = Database.songUsedInPlaylists(nextMediaItem.mediaId)
            }
        }

        var songLiked by remember {
            mutableStateOf(0)
        }
        LaunchedEffect(Unit, nextMediaItem.mediaId) {
            withContext(Dispatchers.IO) {
                songLiked = Database.songliked(nextMediaItem.mediaId)
            }
        }
        var discover by rememberPreference(discoverKey, false)

        if (discover && (songPlaylist1 > 0 || songLiked > 0)) {
            binder.player.removeMediaItem(nextMediaItemIndex)
        }
```

What I'm trying to do is when you enter the player, the next song in queue will be deleted automatically if the song is present in your liked or playlist. The problem is that instead of deleting 1 song next in queue it's deleting 2 songs next in queue(2nd song is not in your liked or playlist so it should not be deleted)


https://github.com/user-attachments/assets/58f1e1f8-8e0c-4569-9eb2-a9afe14cf54f

**Comment by aneesh1122** [comment]
https://github.com/user-attachments/assets/35392902-b9a5-402e-af4f-2288e72fd50f

pay attention at the bottom. see, the songs are getting deleted automatically

**Comment by aneesh1122** [comment]
> WsaClient_JRJ8l2jQrg.mp4 
> pay attention at the bottom. see, the songs are getting deleted automatically. It should work like that but instead of deleting 1 song it's deleting 2 songs next in queue

**Comment by aneesh1122** [comment]
For example, If I'm playing nth song then (n+1)th song should only get deleted. Right now it's deleting (n+1)th song and (n+2)th song.

(n+2)th song should not be deleted because this song is not in my playlist and liked.

Also, if (n+1)th and (n+2)th songs are in my playlist but (n+3)th song is not in my playlist. app is deleting all the 3 songs [n+1,n+2,n+3]. only (n+1) & (n+2) should be deleted.

**Comment by fast4x** [comment]
in order
delete n+2
delete n+1

start delete always from biggest index .. in this case index numbers remains the same...

**Comment by aneesh1122** [comment]
> in order delete n+2 delete n+1
> 
> start delete always from biggest index .. in this case index numbers remains the same...

but I only want to delete n+1. I also used `binder.player.currentMediaItemIndex + 1` but I am getting the same problem

**Comment by fast4x** [comment]
ok... I'll look on it

**Comment by aneesh1122** [comment]
> ok... I'll look on it

okay. I'm doing the pull request

**Pull request merged**
