### PR TITLE
added playlist indicator (with a bug) and swipe improvements

### PR DESCRIPTION
**Pull request by aneesh1122**
1st problem:

https://github.com/user-attachments/assets/1f9ac7e3-e883-4034-9342-c20b4b2e6231

2nd problem:

https://github.com/user-attachments/assets/be8e9c1f-55d8-4d68-b41c-5b6c6ea9a114

SWIPE IMPROVEMENTS:
1) PopUp when a song is deleted from playlists

https://github.com/user-attachments/assets/dd489971-c4ac-4bec-a24b-0cfa430c7894

2) Swipe will trigger only when swiped horizontally

**Before** 

https://github.com/user-attachments/assets/bdbcc2d3-2ba1-4bed-841d-0016333206a1

**After**

https://github.com/user-attachments/assets/93d28d4a-5353-408f-9d74-162912f0ba03

### CODE REVIEW

**Comment by fast4x** [comment]
What's icon with checkmark green?

**Comment by fast4x** [comment]
Its famous playlist indicator?

**Comment by aneesh1122** [comment]
> What's icon with checkmark green?

It indicates that the song is already present in one of the playlists

**Comment by aneesh1122** [comment]
> Its famous playlist indicator?
> 

It's also used in Spotify so I think yeah you could say it's famous

**Comment by fast4x** [comment]
Ok, but use another icon like Playlist... checkmark seem to selectable...

**Comment by fast4x** [comment]
> > Its famous playlist indicator?
> > 
> 
> It's also used in Spotify so I think yeah you could say it's famous

Also if it's used by Spotify, maybe it's good idea use another... LOL

**Comment by fast4x** [comment]
Remember... RiMusic have a identity...

**Comment by fast4x** [comment]
> > Ok, but use another icon like Playlist... checkmark seem to selectable...
> 
> I didn't think about that. Yeah that's an issue.
> 
> I'll change the icon. If I use the playlist logo it will not look good with the song list. I'll think of something.

Yes, use another icon that you like

**Comment by aneesh1122** [comment]
> > > Ok, but use another icon like Playlist... checkmark seem to selectable...
> > 
> > 
> > I didn't think about that. Yeah that's an issue.
> > I'll change the icon. If I use the playlist logo it will not look good with the song list. I'll think of something.
> 
> Yes, use another icon that you like

Is this okay?

WsaClient_HLaKJ9ZYG0

**Comment by fast4x** [comment]
No, it seem to be clicked... try to use playlist icon... with accent color...

**Comment by fast4x** [comment]
And add tooltip on icon with long tap...

**Comment by aneesh1122** [comment]
> try to use playlist icon... with accent color

I tried. It was not looking good with list of songs. If you want that I can add it. I don't have any problems with that.

> tooltip

smarttoast? I'll try

**Comment by fast4x** [comment]
this?
https://www.flaticon.com/free-icon/add-to-playlist_9194943?term=playlist&page=1&position=12&origin=search&related_id=9194943

**Comment by aneesh1122** [comment]
> this?
> https://www.flaticon.com/free-icon/add-to-playlist_9194943?term=playlist&page=1&position=12&origin=search&related_id=9194943

You are already using a similar icon for lyrics

**Comment by fast4x** [comment]
Yes you are right, try to find another...

**Comment by fast4x** [comment]
Use icon library sane used for playlists in home section...
It's a good idea... if song are in any playlist, sign icon will be Library...

**Comment by aneesh1122** [comment]
https://github.com/user-attachments/assets/902b1539-7ea6-4af9-9114-8a443f31f7b1

Playlist icon is looking better. See

> Use icon library sane used for playlists in home section... It's a good idea... if song are in any playlist, sign icon will be Library...
> 
>

**Comment by fast4x** [comment]
But color green?

**Comment by aneesh1122** [comment]
> But color green?

green is used for something positive. Red is for negative. what color do you think I should use?

**Comment by fast4x** [comment]
Green it's a general color, you can use text, accent, must be a color present inside app and dynamic...

**Comment by aneesh1122** [comment]
> Green it's a general color, you can use text, accent, must be a color present inside app and dynamic...

I'll use accent then. It will look weird in action bar since action bar is also accent color

**Comment by aneesh1122** [comment]
> Background of items not use accent color...

WsaClient_oPQPZGVn5l
this okay?

**Comment by fast4x** [comment]
But why in player, you talk about playlist items... not player action bar

**Comment by aneesh1122** [comment]
> But why in player, you talk about playlist items... not player action bar

I wanted Indicator to be in the player too. I want to know if the song I'm listening to is in a playlist or not. The idea started with player then I added to items too.

**Comment by fast4x** [comment]
Ok

**Comment by aneesh1122** [comment]
> Ok

I can add different color to player action bar if you want. Any color will work for me as long as it's properly visible

**Comment by aneesh1122** [comment]
https://github.com/user-attachments/assets/f5f57250-f299-4f59-9d45-3ef00aa5e916

**Comment by fast4x** [comment]
Ok, nice, add tooltip and it's ok

**Comment by aneesh1122** [comment]
> add tooltip

Done already



> > Use icon library sane used for playlists in home section... It's a good idea... if song are in any playlist, sign icon will be Library...
> > 
> 
>  WsaClient_9CxOwS5rn0.mp4 
> Playlist icon is looking better. See

**Comment by aneesh1122** [comment]
> add tooltip

I've added that already

https://github.com/user-attachments/assets/82c56a15-5ad7-4807-9b08-49ec4cdc3cea

**Comment by fast4x** [comment]
Thanks for patience

**Comment by aneesh1122** [comment]
> Thanks for patience

Thanks man. Please try to fix the bug before release.

**Comment by fast4x** [comment]
If i can yes

**Pull request merged**
