### PR TITLE
New translations strings.xml (Malayalam)

### PR DESCRIPTION
**Pull request by XDreamist**

### CODE REVIEW

**Comment by fast4x** [comment]
Why not translated via Crowdin?

**Comment by XDreamist** [comment]
@fast4x Ooops! I didn't notice that. I was working on another feat and thought I'll probably do a PR instead. Anyways! I'll update it through Crowdin.

**Comment by fast4x** [comment]
Thanks for translation btw

**Comment by fast4x** [comment]
I'll add your account to translators list

**Pull request closed without merging**
