### PR TITLE
Imports optimization | A place to store unrelated files | Unused be gone

### PR DESCRIPTION
**Pull request by knighthat**
# Invidious extension be back

> As requested

# Imports optimization

Just remove/rearrange imports

# A place to store unrelated files

I've added a folder named `.ignored.d/` to `.gitignore` to store files that's not a required to compile/run the project. Please move your `*.cmd` and `*.bat` files to this folder. You're going to expose your credentials someday.

# Standardize value retrieval from enum classes

### `toInt()` & `toLong()`

Enum represents a value such as [DurationInMinutes](https://github.com/fast4x/RiMusic/blob/master/composeApp/src/androidMain/kotlin/it/fast4x/rimusic/enums/Durations.kt) should use `toInt()` and/or `toLong()` to declare intention while keeping it as close to built-in Kotlin function as possible

> `number` is too broad because it's abstract class of both `Int` and `Long

### `megaBytes` & `bytes`

For values that represent storage capacity, we should use technical terms. I love that it already has `bytes`, but enum allows you to store default values (constants) so why don't leverage it instead of using **switch-case**

### `asMinute`, `asSeconds` & `asMillis`

Let's pick [DurationInMinutes](https://github.com/fast4x/RiMusic/blob/master/composeApp/src/androidMain/kotlin/it/fast4x/rimusic/enums/Durations.kt) as an example again. Its values represent duration in form of minute, and for quick conversion to milliseconds, `asMillis` was introduced.

### Default values in constructor

This is a minor change. Instead of using **switch-case**, I just put values to constructor. Make it a standard practice of using enums

### Setting texts

To make it easier to display text form of enum value. `TextView` interface is born, main functionality is to make each value of enum return string resource ID so it can display the text with `TextView#text`

### Enum icon

Similarly, enum values that have icons can now use `Drawable` to shorten the process. No more remembering what icon goes with what enum, any enum class extends `Drawable` will benefits of `Drawable.icon`, allows them to render respected icon

# New strings

2 more new strings `playing_song_not_found` and `no_song_to_shuffle` were added. 1 is for when user try to shuffle song list with not song on display, the other is when locator can't find playing song on displaying list

# Tidy up unused code

Code that are not used (no longer in effect) were removed, making space for new code to come

### CODE REVIEW

**Comment by knighthat** [comment]
You said you like the idea of putting [isCurrent](https://github.com/fast4x/RiMusic/blob/25f0e58fcb61cbec186af9af7d3d7b8959e58ae0/composeApp/src/androidMain/kotlin/it/fast4x/rimusic/enums/NavigationBarPosition.kt#L20) to enum so I'm thinking of making the same for other enums, sounds good?

**Comment by fast4x** [comment]
Thank you for your great contribution, but why keep rewriting the code? It’s not a priority! : )

**Comment by knighthat** [comment]
OCD took over LOL

Secondly, having 1 block of code in multiple places is really hard to maintain and troubleshoot problem (from my own experience). When you notice a bug at some place, you can fix it, but now you don't know whether this bug exists in other places because you probably copied this to somewhere else.

Finally, I work in QA, I'm not that good at making new stuff (that's why I do bug fixing most of the time). Besides, I see that we already have multiple people working on new features already, somebody must strengthen the base right?

**Comment by fast4x** [comment]
The problem is that such massive changes may open new bugs that are not immediately visible. That’s why I think it is more interesting to fix bugs first.

**Comment by fast4x** [comment]
Example, can look inside player and find a way to fix repeating songs... in modern player type...
It's an example...

**Comment by knighthat** [comment]
Whatever I guess. I only want people to have easier time to maintain this awesome piece of work in the future.

Bug or not it's still a work in progress, so bugs are expected. But whether you want to fix this once or multiple times because the bug was copied to other places (which was mentioned in my second point)

Anyways, it's up to you.

**Pull request closed without merging**
