### PR TITLE
fixes #2913.

### LINKED ISSUE #2913: java.lang.VerifyError: Verifier rejected class it.fast4x.rimusic.ui.screens.player.PlayerModernKt
### Steps to reproduce the bug

1. Start the app
2. Play a song

### Expected behavior

The song plays.

### Actual behavior

The app crashes with java.lang.VerifyError.

### Screenshots/Screen recordings

_No response_

### Logs

<details><summary>Details</summary>
<p>

````
Process: it.fast4x.rimusic.debug, PID: 29728
                                                                                                    java.lang.VerifyError: Verifier rejected class it.fast4x.rimusic.ui.screens.player.PlayerModernKt: void it.fast4x.rimusic.ui.screens.player.PlayerModernKt.PlayerModern(androidx.navigation.NavController, it.fast4x.rimusic.ui.screens.player.PlayerSheetState, androidx.compose.material3.SheetState, androidx.compose.ui.Modifier, androidx.compose.foundation.shape.RoundedCornerShape, kotlin.jvm.functions.Function0, androidx.compose.runtime.Composer, int, int) failed to verify: void it.fast4x.rimusic.ui.screens.player.PlayerModernKt.PlayerModern(androidx.navigation.NavController, it.fast4x.rimusic.ui.screens.player.PlayerSheetState, androidx.compose.material3.SheetState, androidx.compose.ui.Modifier, androidx.compose.foundation.shape.RoundedCornerShape, kotlin.jvm.functions.Function0, androidx.compose.runtime.Composer, int, int): [0x1F8B] copy1 v233<-v48 type=Imprecise Constant: 127 cat=3 (declaration of 'it.fast4x.rimusic.ui.screens.player.PlayerModernKt' appears in /data/data/it.fast4x.rimusic.debug/code_cache/.overlay/base.apk/classes18.dex)
                                                                                                    	at it.fast4x.rimusic.MainActivity$startApp$5$4$1$4.invoke(MainActivity.kt:925)
                                                                                                    	at it.fast4x.rimusic.MainActivity$startApp$5$4$1$4.invoke(MainActivity.kt:924)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:118)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at it.fast4x.rimusic.ui.components.CustomModalBottomSheetKt$CustomModalBottomSheet$2.invoke(CustomModalBottomSheet.kt:61)
                                                                                                    	at it.fast4x.rimusic.ui.components.CustomModalBottomSheetKt$CustomModalBottomSheet$2.invoke(CustomModalBottomSheet.kt:59)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:118)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.material3.ModalBottomSheetKt$ModalBottomSheetContent$7.invoke(ModalBottomSheet.kt:336)
                                                                                                    	at androidx.compose.material3.ModalBottomSheetKt$ModalBottomSheetContent$7.invoke(ModalBottomSheet.kt:284)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:126)
                                                                                                    	at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:380)
                                                                                                    	at androidx.compose.material3.SurfaceKt.Surface-T9BRK9s(Surface.kt:105)
                                                                                                    	at androidx.compose.material3.ModalBottomSheetKt.ModalBottomSheetContent-IQkwcL4(ModalBottomSheet.kt:216)
                                                                                                    	at androidx.compose.material3.ModalBottomSheetKt$ModalBottomSheet$3.invoke(ModalBottomSheet.kt:173)
                                                                                                    	at androidx.compose.material3.ModalBottomSheetKt$ModalBottomSheet$3.invoke(ModalBottomSheet.kt:166)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.material3.ModalBottomSheet_androidKt$ModalBottomSheetDialog$dialog$1$1$1.invoke(ModalBottomSheet.android.kt:300)
                                                                                                    	at androidx.compose.material3.ModalBottomSheet_androidKt$ModalBottomSheetDialog$dialog$1$1$1.invoke(ModalBottomSheet.android.kt:296)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.material3.ModalBottomSheetDialogLayout.Content(ModalBottomSheet.android.kt:354)
                                                                                                    	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:259)
2024-07-25 00:10:22.716 29728-29728 AndroidRuntime          it.fast4x.rimusic.debug              E  	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:258)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:380)
                                                                                                    	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:216)
                                                                                                    	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:132)
                                                                                                    	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:131)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:380)
                                                                                                    	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:121)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:155)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:154)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:401)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:154)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:133)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:97)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3593)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3520)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:743)
                                                                                                    	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1114)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3874)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3874)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:649)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:635)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:133)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:124)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1597)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:124)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:180)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.jvm.kt:320)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.jvm.kt:198)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:124)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1678)
                                                                                                    	at android.view.View.dispatchAttachedToWindow(View.java:23227)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3698)
2024-07-25 00:10:22.718 29728-29728 AndroidRuntime          it.fast4x.rimusic.debug              E  	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3705)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3705)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3705)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3705)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3901)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3288)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11344)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1689)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:1079)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8919)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
````

</p>
</details> 

### RiMusic version

master branch on commit 9ae01df20d88ef0d7fc7

### Android version

14

### Additional information

I was able to track down the bad (i.e. broken) commit: c9de5a4333726573f27ec4d195bd1148c529712a.
The previous commit a24bbd3fb5b0c86080a43b20bd1300c8d2783607 is still good.

### PR DESCRIPTION
**Pull request by twistios**
I don't know why it helps but it does. This seems to be the minimal fix.

### CODE REVIEW

**Comment by twistios** [comment]
This was a really cursed issue, but all errors go away at once by using this change.

**Comment by aneesh1122** [comment]
@fast4x what does this do exactly? Neither of us faced any issues while playing songs.

Debug apk crashes often but release apk was working fine except for some problems I told you before.

**Comment by fast4x** [comment]
I don't now, try if do anything I'll remove

**Comment by aneesh1122** [comment]
@twistios where were you getting errors?

**Comment by aneesh1122** [comment]
> I don't now, try if do anything I'll remove

Radio is still crashing. I don't know what it fixes.

**Comment by fast4x** [comment]
tryed, it fix anything... removed

**Comment by twistios** [comment]
> @twistios where were you getting errors?

I was getting this error in DEBUG build and it prevents me from doing any debugging related to player. Using git bisect I was able to find on which commit it was not throwing this error and on which one it started happening. 

It could be that I have some version of some software installed, which is different than both of you have. VerifyError can be thrown (for example) if parts of the code are compiled with serval different versions. This is something the case with external libraries. Also sometimes there are problems when there is an update with the verifier that does more strict tests. For example when one was using Dalvik and then switched to Android ART https://developer.android.com/guide/practices/verifying-apps-art

It could also be any other problem. But if you think that there is no problem with the app, please help me fix it for me.

It could also be a bug in proguard or any other related tool used for creating the DEBUG apk.

About radio: this issue was never about radio, so it can not fix anything about it.

**Comment by aneesh1122** [comment]
I also had problems with debug apk and it was frustrating to create release apk after every changes because it takes a lot of time. Having said that, adding your code did not fix debug apk crash.

**Comment by fast4x** [comment]
I have reverted commit, sorry twistios but it not solve anything

**Comment by twistios** [comment]
It did fix the crash on DEBUG apk that I experienced. The radio issue did not happen for me but I also did not test this yet.

**Comment by twistios** [comment]
Do you mean this radio?

https://github.com/user-attachments/assets/64e32383-2443-47f1-841d-cef7259179f2

I think this video requires a bit explanation.

In the video I use my custom debug build on my phone (were the VerfifyError is fixed).
As it can be seen, I am using modern player (can also be seen for a very short time at the end when I am able to move the thumbnail).

**Comment by twistios** [comment]
I was able to reproduce something similar. It does not crash if you use the queue, but by doing 1-song steps with the button. On first tab the song restarts, on the second tab to moves and crashes.

https://github.com/user-attachments/assets/10d2df6b-9591-4b87-b5fe-12828c0c01ca

**Comment by aneesh1122** [comment]
> I was able to reproduce something similar. It does not crash if you use the queue, but by doing 1-song steps with the button. On first tab the song restarts, on the second tab to moves and crashes.
> 
> https://github.com/user-attachments/assets/10d2df6b-9591-4b87-b5fe-12828c0c01ca
> 
> 

Yeah if you use the queue to change songs it won't crash.

Anyways, fast4x has already fixed it

**Comment by twistios** [comment]
It seems like the issue for me has been resolved in commit 27a174c61fa3e92fdaa6d8629b1d8a57af95c626 (or probably actually 5cb61ad2fedae5b5e91fc3f3c7307dc32eeac484), so the issue can now be really considered resolved I guess except that it is still weird.

I did not have these commits in my branch because I was not aware of it.

**Comment by twistios** [comment]
I guess this is has the same effect on the issue as my change @fast4x, so this is why the commit fixed the problem for me.
https://github.com/aneesh1122/RiMusic/blob/5cb61ad2fedae5b5e91fc3f3c7307dc32eeac484/app/src/main/kotlin/it/fast4x/rimusic/ui/screens/player/PlayerModern.kt#L650-L651

**Comment by aneesh1122** [comment]
> I guess this is has the same effect on the issue as my change @fast4x, so this is why the commit fixed the problem for me.
> https://github.com/aneesh1122/RiMusic/blob/5cb61ad2fedae5b5e91fc3f3c7307dc32eeac484/app/src/main/kotlin/it/fast4x/rimusic/ui/screens/player/PlayerModern.kt#L650-L651
> 

Nope. These lines were present in the code since I implemented modern player. This isn't a recent change.

**Comment by twistios** [comment]
https://github.com/fast4x/RiMusic/pull/2924/commits/5cb61ad2fedae5b5e91fc3f3c7307dc32eeac484#diff-f839261b5830c529a7dd9529316e8d1cda98467d6677413f93a28f2266113521

You have moved the code to the top level in the commit.

**Pull request merged**
