### PR TITLE
❌ Removed unused translation 


### PR DESCRIPTION
**Pull request by NEVARLeVrai**
**What removed :**

For all languages i removed unused translation 

- string name="offline"
- string name="play_next"
- string name="next_playing"
- string name="now_playing"

**What change :**

- Fix somes emojis on French 
- Fix spaces between string on German

### CODE REVIEW

**Comment by NEVARLeVrai** [comment]
I think I did well and removed in all translation 😅

**Comment by NEVARLeVrai** [comment]
Done u can merge

**Comment by fast4x** [comment]
play_next are used, other ok
i have re added string but will be to translate

**Comment by ikanakova** [comment]
@NEVARLeVrai Strings can't just be removed, there are dependencies on them elsewhere in the application code. They don't have to be visible in the application itself.

**Comment by NEVARLeVrai** [comment]
> @NEVARLeVrai Strings can't just be removed, there are dependencies on them elsewhere in the application code. They don't have to be visible in the application itself.

But other that I removed it's worked ?

**Comment by fast4x** [comment]
Yes,  have re added strings play_next

**Pull request merged**
