### PR TITLE
fixed crash caused by using different favorite buttons

### LINKED ISSUE #3185: App se cierra al intentar reproducir una canción
### Steps to reproduce the bug

1. Primero entro a la aplicación 
2. Le doy click a la canción que deseo escuchar 
3. La app no la reproduce y se cierra al instante 

### Expected behavior

Que se pueda reproducir cualquier canción sin que la app se cierre

### Actual behavior

La app se cierra al intentar reproducir cualquier canción 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/5c3b56a1-5405-40fe-81ca-b0f8b6dd7ae3

### Logs

2024-08-09T16:24:16.340:	android.content.res.Resources$NotFoundException: File res/Dg.webp from xml type xml resource ID #0x7f0700d4
	 android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1291) 
	 android.content.res.Resources.loadXmlResourceParser(Resources.java:2426) 
	 android.content.res.Resources.loadXmlResourceParser(Resources.java:2402) 
	 android.content.res.Resources.getXml(Resources.java:1303) 
	 a.a.f0(SourceFile:59) 
	 B3.a.i(SourceFile:631) 
	 s7.o.n(SourceFile:717) 
	 a6.b.c(SourceFile:267) 
	 N6.j1.e(SourceFile:236) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 s7.o.t(SourceFile:1345) 
	 E6.l.e(SourceFile:255) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 A6.i.e(SourceFile:198) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 F6.d.g(SourceFile:442) 
	 e0.a.g(SourceFile:52) 
	 O.U.g(SourceFile:170) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 T.R1.a(SourceFile:113) 
	 T.S0.b(SourceFile:56) 
	 T.G0.g(SourceFile:214) 
	 e0.a.g(SourceFile:52) 
	 T.U0.g(SourceFile:258) 
	 e0.a.g(SourceFile:52) 
	 T.A0.a(SourceFile:52) 
	 A6.z.g(SourceFile:1206) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.p0.a(SourceFile:395) 
	 A6.X.g(SourceFile:1216) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.T.a(SourceFile:627) 
	 J0.x1.g(SourceFile:250) 
	 e0.a.g(SourceFile:52) 
	 W.c.a(SourceFile:233) 
	 J0.x1.g(SourceFile:213) 
	 e0.a.g(SourceFile:52) 
	 W.c.O(SourceFile:15) 
	 W.q.p(SourceFile:203) 
	 W.u.k(SourceFile:32) 
	 W.u0.a(SourceFile:43) 
	 W.n.a(SourceFile:5) 
	 W.n.a(SourceFile:5) 
	 W.u.l(SourceFile:9) 
	 W.u.c(SourceFile:3) 
	 B.j0.b(SourceFile:529) 
	 J0.w.setOnViewTreeOwnersAvailable(SourceFile:7) 
	 J0.y1.c(SourceFile:10) 
	 J0.y1.m(SourceFile:19) 
	 androidx.lifecycle.w.a(SourceFile:23) 
	 androidx.lifecycle.x.a(SourceFile:217) 
	 B.j0.b(SourceFile:498) 
	 J0.w.onAttachedToWindow(SourceFile:120) 
	 android.view.View.dispatchAttachedToWindow(View.java:20563) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3577) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3584) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3584) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3584) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3584) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2611) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2141) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8568) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1030) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:840) 
	 android.view.Choreographer.doFrame(Choreographer.java:772) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1002) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loop(Looper.java:268) 
	 android.app.ActivityThread.main(ActivityThread.java:8019) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997) 
Caused by:	java.io.FileNotFoundException: Corrupt XML binary file
	 android.content.res.AssetManager.nativeOpenXmlAsset(Native Method) 
	 android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:1127) 
	 android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1275) 
	 android.content.res.Resources.loadXmlResourceParser(Resources.java:2426) 
	 android.content.res.Resources.loadXmlResourceParser(Resources.java:2402) 
	 android.content.res.Resources.getXml(Resources.java:1303) 
	 a.a.f0(SourceFile:59) 
	 B3.a.i(SourceFile:631) 
	 s7.o.n(SourceFile:717) 
	 a6.b.c(SourceFile:267) 
	 N6.j1.e(SourceFile:236) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 s7.o.t(SourceFile:1345) 
	 E6.l.e(SourceFile:255) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 A6.i.e(SourceFile:198) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 F6.d.g(SourceFile:442) 
	 e0.a.g(SourceFile:52) 
	 O.U.g(SourceFile:170) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 T.R1.a(SourceFile:113) 
	 T.S0.b(SourceFile:56) 
	 T.G0.g(SourceFile:214) 
	 e0.a.g(SourceFile:52) 
	 T.U0.g(SourceFile:258) 
	 e0.a.g(SourceFile:52) 
	 T.A0.a(SourceFile:52) 
	 A6.z.g(SourceFile:1206) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.p0.a(SourceFile:395) 
	 A6.X.g(SourceFile:1216) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.T.a(SourceFile:627) 
	 J0.x1.g(SourceFile:250) 
	 e0.a.g(SourceFile:52) 
	 W.c.a(SourceFile:233) 
	 J0.x1.g(SourceFile:213) 
	 e0.a.g(SourceFile:52) 
	 W.c.O(SourceFile:15) 
	 W.q.p(SourceFile:203) 
	 W.u.k(SourceFile:32) 
	 W.u0.a(SourceFile:43) 
	 W.n.a(SourceFile:5) 
	 W.n.a(SourceFile:5) 
	 W.u.l(SourceFile:9) 
	 W.u.c(SourceFile:3) 
	 B.j0.b(SourceFile:529) 
	 J0.w.setOnViewTreeOwnersAvailable(SourceFile:7) 
	 J0.y1.c(SourceFile:10) 
	 J0.y1.m(SourceFile:19) 
	 androidx.lifecycle.w.a(SourceFile:23) 
	 androidx.lifecycle.x.a(SourceFile:217) 
	 B.j0.b(SourceFile:498) 
	 J0.w.onAttachedToWindow(SourceFile:120) 
	 android.view.View.dispatchAttachedToWindow(View.java:20563) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3577) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3584) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3584) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3584) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3584) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2611) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2141) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8568) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1030) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:840) 
	 android.view.Choreographer.doFrame(Choreographer.java:772) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1002) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loop(Looper.java:268) 
	 android.app.ActivityThread.main(ActivityThread.java:8019) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997) 

### RiMusic version

0.6.47

### Android version

Android 11

### Additional information

Este error no me pasó nunca con la actualización anterior, a penas la actualice a la más reciente se produjo este error

### LINKED ISSUE #3190: Error in the mini player
### Steps to reproduce the bug

Error 1
-When you use the player and change the song by swiping, the player closes abruptly each time and switches to the mini player. 
Error 2
-When I updated the app everything worked normally, but if I wanted to switch from the mini player to the full screen, the app closes completely. 

### Expected behavior

When you launch the app, selecting a music should display the full player, but only launch the mini player. 

### Actual behavior

Instead of the app closing when you click there, it should display the player in full screen. 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/0bd2d562-789f-426b-97b2-d7138c69c2ff

### Logs

2024-08-09T19:42:53.374:	android.content.res.Resources$NotFoundException: File res/Dg.webp from xml type xml resource ID #0x7f0700d4
	 android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1633) 
	 android.content.res.Resources.loadXmlResourceParser(Resources.java:2738) 
	 android.content.res.Resources.loadXmlResourceParser(Resources.java:2711) 
	 android.content.res.Resources.getXml(Resources.java:1517) 
	 a.a.f0(SourceFile:59) 
	 B3.a.i(SourceFile:631) 
	 s7.o.n(SourceFile:717) 
	 a6.b.c(SourceFile:261) 
	 s7.o.t(SourceFile:1339) 
	 E6.l.e(SourceFile:255) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 A6.i.e(SourceFile:198) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 F6.d.g(SourceFile:442) 
	 e0.a.g(SourceFile:52) 
	 O.U.g(SourceFile:170) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 T.R1.a(SourceFile:113) 
	 T.S0.b(SourceFile:56) 
	 T.G0.g(SourceFile:214) 
	 e0.a.g(SourceFile:52) 
	 T.U0.g(SourceFile:258) 
	 e0.a.g(SourceFile:52) 
	 T.A0.a(SourceFile:52) 
	 A6.z.g(SourceFile:1206) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.p0.a(SourceFile:395) 
	 A6.X.g(SourceFile:1216) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.T.a(SourceFile:627) 
	 J0.x1.g(SourceFile:250) 
	 e0.a.g(SourceFile:52) 
	 W.c.a(SourceFile:233) 
	 J0.x1.g(SourceFile:213) 
	 e0.a.g(SourceFile:52) 
	 W.c.O(SourceFile:15) 
	 W.q.p(SourceFile:203) 
	 W.u.k(SourceFile:32) 
	 W.u0.a(SourceFile:43) 
	 W.n.a(SourceFile:5) 
	 W.n.a(SourceFile:5) 
	 W.u.l(SourceFile:9) 
	 W.u.c(SourceFile:3) 
	 B.j0.b(SourceFile:529) 
	 J0.w.setOnViewTreeOwnersAvailable(SourceFile:7) 
	 J0.y1.c(SourceFile:10) 
	 J0.y1.m(SourceFile:19) 
	 androidx.lifecycle.w.a(SourceFile:23) 
	 androidx.lifecycle.x.a(SourceFile:217) 
	 B.j0.b(SourceFile:498) 
	 J0.w.onAttachedToWindow(SourceFile:120) 
	 android.view.View.dispatchAttachedToWindow(View.java:21785) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3678) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3685) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3685) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3685) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3685) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3947) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3225) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11121) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1938) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1946) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1226) 
	 android.view.Choreographer.doFrame(Choreographer.java:1089) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1892) 
	 android.os.Handler.handleCallback(Handler.java:971) 
	 android.os.Handler.dispatchMessage(Handler.java:107) 
	 android.os.Looper.loopOnce(Looper.java:206) 
	 android.os.Looper.loop(Looper.java:296) 
	 android.app.ActivityThread.main(ActivityThread.java:9170) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1018) 
Caused by:	java.io.FileNotFoundException: Corrupt XML binary file
	 android.content.res.AssetManager.nativeOpenXmlAsset(Native Method) 
	 android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:1264) 
	 android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1614) 
	 android.content.res.Resources.loadXmlResourceParser(Resources.java:2738) 
	 android.content.res.Resources.loadXmlResourceParser(Resources.java:2711) 
	 android.content.res.Resources.getXml(Resources.java:1517) 
	 a.a.f0(SourceFile:59) 
	 B3.a.i(SourceFile:631) 
	 s7.o.n(SourceFile:717) 
	 a6.b.c(SourceFile:261) 
	 s7.o.t(SourceFile:1339) 
	 E6.l.e(SourceFile:255) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 A6.i.e(SourceFile:198) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 F6.d.g(SourceFile:442) 
	 e0.a.g(SourceFile:52) 
	 O.U.g(SourceFile:170) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 T.R1.a(SourceFile:113) 
	 T.S0.b(SourceFile:56) 
	 T.G0.g(SourceFile:214) 
	 e0.a.g(SourceFile:52) 
	 T.U0.g(SourceFile:258) 
	 e0.a.g(SourceFile:52) 
	 T.A0.a(SourceFile:52) 
	 A6.z.g(SourceFile:1206) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.p0.a(SourceFile:395) 
	 A6.X.g(SourceFile:1216) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.T.a(SourceFile:627) 
	 J0.x1.g(SourceFile:250) 
	 e0.a.g(SourceFile:52) 
	 W.c.a(SourceFile:233) 
	 J0.x1.g(SourceFile:213) 
	 e0.a.g(SourceFile:52) 
	 W.c.O(SourceFile:15) 
	 W.q.p(SourceFile:203) 
	 W.u.k(SourceFile:32) 
	 W.u0.a(SourceFile:43) 
	 W.n.a(SourceFile:5) 
	 W.n.a(SourceFile:5) 
	 W.u.l(SourceFile:9) 
	 W.u.c(SourceFile:3) 
	 B.j0.b(SourceFile:529) 
	 J0.w.setOnViewTreeOwnersAvailable(SourceFile:7) 
	 J0.y1.c(SourceFile:10) 
	 J0.y1.m(SourceFile:19) 
	 androidx.lifecycle.w.a(SourceFile:23) 
	 androidx.lifecycle.x.a(SourceFile:217) 
	 B.j0.b(SourceFile:498) 
	 J0.w.onAttachedToWindow(SourceFile:120) 
	 android.view.View.dispatchAttachedToWindow(View.java:21785) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3678) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3685) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3685) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3685) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3685) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3947) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3225) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11121) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1938) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1946) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1226) 
	 android.view.Choreographer.doFrame(Choreographer.java:1089) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1892) 
	 android.os.Handler.handleCallback(Handler.java:971) 
	 android.os.Handler.dispatchMessage(Handler.java:107) 
	 android.os.Looper.loopOnce(Looper.java:206) 
	 android.os.Looper.loop(Looper.java:296) 
	 android.app.ActivityThread.main(ActivityThread.java:9170) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1018) 

### RiMusic version

0.6.47

### Android version

Android 13

### Additional information

_No response_

### LINKED ISSUE #3192: Can't change the like button
### Steps to reproduce the bug

Go to the appearance section, look for the appearance section of the like button, then select another style and when you change it, open the player 

### Expected behavior

The appearance of the like button should change to the selection 

### Actual behavior

When you change the appearance of the button and open the player, the application closes and the music stops playing. 

### Screenshots/Screen recordings

_No response_

### Logs

_No response_

### RiMusic version

O.6.47

### Android version

Android 14

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by aneesh1122**
closes #3192
closes #3190
closes #3185

### CODE REVIEW

**Comment by fast4x** [comment]
New custom version 
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by aneesh1122** [comment]
> New custom version https://github.com/fast4x/RiMusic/tree/master/customVersion

Every problem seems to be fixed now

**Comment by fast4x** [comment]
Other depend by geographic location...

**Comment by aneesh1122** [comment]
> Other depend by geographic location...

I tried the modern header and found this strange behaviour. This space is unoccupied I don't know why. I even removed the 'like' button from there but it's still not being occupied

**Comment by Nisselle** [comment]
Cómo hace para que la miniatura se vea así de grande y con difuminado al fondo? Quisiera ponerlo así

**Comment by fast4x** [comment]
Enable background colors -> Blurred cover and set your blur effect level.



Long tap in player/pause button 


set blur level


All settings are in Player appearance

**Comment by aneesh1122** [comment]
> Cómo hace para que la miniatura se vea así de grande y con difuminado al fondo? Quisiera ponerlo así

https://github.com/user-attachments/assets/599d9c27-8f00-49a7-a359-497b21ab2a5f

**Comment by fast4x** [comment]
@aneesh1122 thanks for fix :)

**Comment by aneesh1122** [comment]
> @aneesh1122 thanks for fix :)

You're welcome 😊✌️

**Pull request merged**
