### PR TITLE
Adjust blur and remove Action Bar when no items

### PR DESCRIPTION
**Pull request by bbyeen**
# Before
image
# After
image
#1959

### CODE REVIEW

**Comment by aneesh1122** [comment]
That's too dark and if it's implemented I want  it to be optional please.

Maybe you can implement this #1965. Control blur and dark shade amount on your own

**Comment by aneesh1122** [comment]
I liked what you did with the action bar.

Could you please add an option to make the action bar transparent even when some items are selected?

**Comment by fast4x** [comment]
Nice work thanks. I'm fixing action bar and after I'll merge this. 

Have you planned to add blur controls #1965? 

If not, I'll implement it.

**Comment by fast4x** [comment]
> That's too dark and if it's implemented I want  it to be optional please.
> 
> Maybe you can implement this #1965. Control blur and dark shade amount on your own

all parameters can be personalised...

**Comment by aneesh1122** [comment]
> > That's too dark and if it's implemented I want  it to be optional please.
> > 
> > Maybe you can implement this #1965. Control blur and dark shade amount on your own
> 
> all parameters can be personalised...

That would be perfect. Thanks fast4x

**Comment by bbyeen** [comment]
> I liked what you did with the action bar.
> 
> Could you please add an option to make the action bar transparent even when some items are selected?

This pr only changes behavior of action bar when no option is selected. When you select any option it will be set to default 0.8 opacity.

**Comment by bbyeen** [comment]
> Nice work thanks. I'm fixing action bar and after I'll merge this.
> 
> Have you planned to add blur controls #1965?
> 
> If not, I'll implement it.

Yeah, I can work on it in my free time.

**Comment by aneesh1122** [comment]
> > I liked what you did with the action bar.
> > 
> > Could you please add an option to make the action bar transparent even when some items are selected?
> 
> This pr only changes behavior of action bar when no option is selected. When you select any option it will be set to default 0.8 opacity.

Please add an option to have the transparent action bar even when some items are selected.

**Comment by fast4x** [comment]
> > Nice work thanks. I'm fixing action bar and after I'll merge this.
> > 
> > Have you planned to add blur controls #1965?
> > 
> > If not, I'll implement it.
> 
> Yeah, I can work on it in my free time.

Of course, but before you start dev check ticket, would be possible it's just implemented.

**Comment by fast4x** [comment]
Why have closed this merge?

**Comment by bbyeen** [comment]
> Why have closed this merge?

Sorry I'm just really, really bad at git and did something. Fix with slider is incoming.

**Pull request closed without merging**
