### PR TITLE
double tap to display/hide thumbnail, fixed mini player mode bug, added option to hide progress bar and some minor improvements

### PR DESCRIPTION
**Pull request by aneesh1122**
okay so I implemented double tap on screen to show/hide thumbnail but it's buggy. The thumbnail status won't change until you close and open the player.

https://github.com/fast4x/RiMusic/assets/45353488/23a9d2bf-8c03-477d-8df3-1b5c2133d471

This also needs fast4x magic touch.

btw I managed to fix Mini Player mode changing bug

removed stroke/outline for non blurredcovers backgrouds

implemented transparent timeline bar #2345

added different blur amount for lyrics+no lyrics thumbnail

evenly spaced icons in action bar

expanded lyrics view

added stroke to seekbar durations for better visibility for 0 blur. activates only when nothumbnail is enabled

fixes bug #2367

### CODE REVIEW

**Comment by fast4x** [comment]
Add option for this
implemented transparent timeline bar #2345

**Comment by fast4x** [comment]
Sorry, just added, ok

**Comment by aneesh1122** [comment]
> Sorry, just added, ok

I did not add transparent time for fake audio because I thought it won't look good. should I add that for fake audio timeline too?

**Comment by fast4x** [comment]
Yes, I would add it for consistency

**Comment by aneesh1122** [comment]
> Yes, I would add it for consistency

Alright

**Comment by aneesh1122** [comment]
Could you please add an another blur slider for (isShowingLyrics)?

If the lyrics are off it will have one blur amount and when the lyrics are turned on there will be another blur amount.

**Comment by aneesh1122** [comment]
> btw Could you please add an another blur slider for the condition (isShowingLyrics)?

I implemented it but there are bugs

1)

https://github.com/fast4x/RiMusic/assets/45353488/c567e3f7-2c04-4af2-bb10-320d3f323d72

All the changes are lost when I minimize and then open the player

2)

https://github.com/fast4x/RiMusic/assets/45353488/e88f188b-dfd9-440a-91b8-3f1f900ee79f

I created 2 different sliders for 

(!isShowingLyrics) || (isShowingLyrics) && (showlyricsthumbnail)

and

(isshowinglyrics) && (!showlyricsthumbnail)

but the blur values in both the sliders are same

**Comment by fast4x** [comment]
Nice

**Comment by aneesh1122** [comment]
I am trying to implement a bigger lyrics screen but this is where I'm stuck. This column's height is fixed and I'm not able to make it take as little height as possible


I know it is because of that column because when I remove controls, titles and other elements this is what I have. Now the lyrics are taking all the height available.


So how do I make the column take least height possible?

**Comment by fast4x** [comment]
I don't like it, remove, make not sense because exist full screen lyrics, so is duplication.

**Comment by aneesh1122** [comment]
> I don't like it, remove, make not sense because exist full screen lyrics, so is duplication.

It will be optional

**Comment by fast4x** [comment]
is duplicated, make sense if only full screen or only expanded because it's same

**Comment by aneesh1122** [comment]
> is duplicated, make sense if only full screen or only expanded because it's same

Okay. I'll remove all the codes related to this and do a pull request of remaining things I added.

**Comment by fast4x** [comment]
Thanks

**Comment by aneesh1122** [comment]
> Thanks 

is there any Boolean variable which becomes true only when you are in full screen lyrics and becomes false when you exit full screen lyrics?

**Comment by fast4x** [comment]
I thought, but if all these changes on lyrics connect them to the current full screen button, no need to turn on/off from settings? It would be the same as full lyrics without showing the current full screen... pensavci

**Comment by aneesh1122** [comment]
> I thought, but if all these changes on lyrics connect them to the current full screen button, no need to turn on/off from settings? It would be the same as full lyrics without showing the current full screen... pensavci
> 

People will have choices. Do they want to have a small window for lyrics? Do they want to use the remaining space for lyrics? Do they want to use full screen lyrics?

Options are good as long as it doesn't affect some other options.

**Comment by aneesh1122** [comment]
> I thought, but if all these changes on lyrics connect them to the current full screen button, no need to turn on/off from settings? It would be the same as full lyrics without showing the current full screen... 
> 

Okay I understood you now. Sorry for not understanding before. Yeah you can replace this with current 'full screen lyrics'. This is definitely an improvement.



Innertube does it too. I want RiMusic to do it in a much better way. RiMusic will have lyrics size options, same background as player and much better looking.

**Comment by fast4x** [comment]
Ok, so this will be the new full lyrics feature that replaces the previous one. Please do not delete fulllyrics file in player folder anyway even if it will not be used it is useful to keep it

**Comment by aneesh1122** [comment]
> Ok, so this will be the new full lyrics feature that replaces the previous one. Please do not delete fulllyrics file in player folder anyway even if it will not be used it is useful to keep it

I'm not able to do it now. let's keep it for future.

I've added an option to change player timeline size without changing thumbnail size.

**Comment by aneesh1122** [comment]
btw a preview I created of what I have in my mind. This is how it will look after it gets implemented

Screenshot_2024-06-20-11-29-23-564_it fast4x rimusic debug

**Comment by fast4x** [comment]
So will be available icon for switch to full or normal?

**Comment by aneesh1122** [comment]
> So will be available icon for switch to full or normal?

There will be a toggle in the appearance settings.

If people like it you can later replace it with full screen lyrics.

**Comment by aneesh1122** [comment]
> So will be available icon for switch to full or normal?

I can implement it in the 'maximize' button but you'll have to minimize and reopen the player for changes to take effect.

I don't know how to trigger the UI update with the Boolean variable change.

If you could help me I can fix a lot of bugs since all are somewhat related.

**Comment by fast4x** [comment]
Ok I'll try to fix it

**Comment by aneesh1122** [comment]
> Ok I'll try to fix it

https://github.com/fast4x/RiMusic/assets/45353488/1371129c-00c4-4d0f-8ba7-62644eabc812

This is the best I could do.

**Comment by aneesh1122** [comment]
Looks great even for non blurred backgrounds

**Comment by aneesh1122** [comment]
This is how it can be implemented

1) let's call it 'expanded player'
2) It will be available in the action bar


3) I've removed the 'full screen lyrics' button for people not using thumbnails for lyrics. Those who want to enter new full screen lyrics can do it using the 'expanded Player' icon.

4) old full screen lyrics will still be available for people using thumbnail for lyrics


5) this still needs to be fixed. Please try to fix this.

https://github.com/fast4x/RiMusic/assets/45353488/c2a9ea01-3eb9-4674-a5bf-644fa7dd8fdc

The player UI is not updating after tapping the icon. I have to minimize and then reopen the player to have the expanded player.

**Comment by fast4x** [comment]
I'm not sure if i can fix this with next release, I'm much occupied with my job

**Comment by fast4x** [comment]
Merged, please fix this, it's much compressed 
Screenshot_20240620_220714

**Comment by aneesh1122** [comment]
> I'm not sure if i can fix this with next release, I'm much occupied with my job

it's okay. I did not push the newest changes mentioned above so there won't be any big problems.

> Merged, please fix this, it's much compressed Screenshot_20240620_220714

okay. I'll add some spacers in between

**Comment by fast4x** [comment]
Fixed update expanded player with click

**Comment by aneesh1122** [comment]
> Fixed update expanded player with click

Does it also update the lyrics window size?

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/assets/1484476/0b82a51a-4467-4524-9587-f8831ec4539f

**Comment by aneesh1122** [comment]
> 
> https://github.com/fast4x/RiMusic/assets/1484476/0b82a51a-4467-4524-9587-f8831ec4539f
> 
> 

Dude you are the best. Thanks for fixing this.

The lyrics window height is also changing.

Now only the lyrics window width needs to be fixed.

You'll understand what I'm saying after you set the thumbnail size to smallest and try the new lyrics window.

**Comment by aneesh1122** [comment]
https://github.com/fast4x/RiMusic/assets/45353488/56a50f91-12aa-43ce-a714-2dff86e997c6

Would be perfect if the lyrics window wasn't limited by thumbnail size

**Comment by fast4x** [comment]
I'll look on it after release

**Comment by aneesh1122** [comment]
> I'll look on it after release

Okay

**Pull request merged**
