### PR TITLE
Add new stats icons

### PR DESCRIPTION
**Pull request by ikanakova**

### CODE REVIEW

**Comment by sayyid5416** [comment]
For `stat-all`, it would look better without any icon in between.

**Comment by ikanakova** [comment]
> For `stat-all`, it would look better without any icon in between.

@sayyid5416 You mean like this?:

**Comment by fast4x** [comment]
Amazig work!

**Comment by ikanakova** [comment]
> Amazig work!

Thanks ☺️

**Comment by sayyid5416** [comment]
> > For `stat-all`, it would look better without any icon in between.
> 
> @sayyid5416 You mean like this?: 

@ikanakova Yes, I meant it like that, but PR already merged now 🤷‍♂️

**Comment by fast4x** [comment]
Done.

**Pull request merged**
