### PR TITLE
Query transaction rework

### PR DESCRIPTION
**Pull request by knighthat**
Is it me or [OneColumnApp.kt](https://github.com/fast4x/RiMusic/blob/master/composeApp/src/desktopMain/kotlin/it/fast4x/rimusic/ui/OneColumnApp.kt) and [ThreeColumnsApp.kt](https://github.com/fast4x/RiMusic/blob/master/composeApp/src/desktopMain/kotlin/it/fast4x/rimusic/ui/ThreeColumnsApp.kt) are giving error because [InnerTube#player](https://github.com/fast4x/RiMusic/blob/master/extensions/innertube/src/main/kotlin/it/fast4x/innertube/requests/Player.kt) doesn't have `pipedSession`?

### CODE REVIEW

**Comment by fast4x** [comment]
I don't remember, I'll check it soon

**Comment by knighthat** [comment]
Yea but now it's throwing errors

**Comment by knighthat** [comment]
> > Yea but now it's throwing errors
> 
> How can it throw errors if it is not used?

it's linting error, because `Innertube.Player` with `pipedSession` as a parameter doesn't exist

**Comment by fast4x** [comment]
Also here solve conflict, thanks I'll merge.

**Comment by knighthat** [comment]
can you merge #4603 before this, I made some changes to files listed here, it's best to have the other PR merged then solve conflicts on this PR

**Comment by fast4x** [comment]
Too much conflicts,

**Comment by knighthat** [comment]
> Too much conflicts,

Yeah, because you let it marinated too long. 

Quick question, did you give me write access on #4603 or Github does it automatically? I can't resolve conflicts here like I did on #4603

**Comment by fast4x** [comment]
ok it’s fine so when I have more time I try again to solve conflicts

**Comment by knighthat** [comment]
conflict solved

**Comment by knighthat** [comment]
please don't let this one go out of date

**Comment by fast4x** [comment]
Merged

**Comment by knighthat** [comment]
Thanks

**Comment by fast4x** [comment]
Thanks to you 👍

**Pull request merged**
