### PR TITLE
lyrics color option

### PR DESCRIPTION
**Pull request by aneesh1122**
1) replaced shadows with stroke/outline
2) fixed alignment issues with lyrics
3) fixed stroke/outline issue of non synced lyrics
4) some improvements to 'No thumbnails' mode
5) moved Lyrics size & Translate options to 3 dots menu when thumbnail for lyrics is disabled

I honestly can't think of anything new to add so consider this the last pull request for this week.

Hope you'll like all the new changes.

### CODE REVIEW

**Comment by fast4x** [comment]
Don’t worry, don’t rush things.

**Comment by aneesh1122** [comment]
> Don’t worry, don’t rush things.

I've been using the app with my codes for almost an hour and found no bugs so this will be the final pull request.

If I even change anything I'll do the pull request after your next release so pls go ahead and merge this code.

If you fix the bugs I've talked about in the previous pull request there will be no bugs in my opinion.

**Comment by fast4x** [comment]
Good, actually I can't fix bugs because I'm much busy with my job and piped optimization that have priority. Why do you not try to fix them?

**Comment by aneesh1122** [comment]
> Good, actually I can't fix bugs because I'm much busy with my job and piped optimization that have priority. Why do you not try to fix them?

I tried but I wasn't able to fix them. I tried using mutable for Boolean variables that require UI to get refreshed but I only made it worse.

You've fixed similar bugs in the past like how player background wasn't changing with songs so pls look into this whenever you're free.

I'll then look at your codes to understand what I'm doing wrong.

**Pull request merged**
