### PR TITLE
Backup plan | Fetch from multiple Piped instances and use the fastest response

### PR DESCRIPTION
**Pull request by knighthat**
> Who the F setup API portal and place a bot filter at the front? Like, what human opens their browser and types in API links just to get a ef'ing JSON file to read for fun.

# How it works

When Innertube fails (`LOGIN_REQUIRED`), Piped will be used to fetch streams for the same `videoId`. 

But instead of hitting **1** server multiple times. This algorithm is designed to hit multiple servers and return the fastest (also successful) response.

> Piped instances will be kept until the app exits or `Piped#fetchPipedInstances()` is called to renew the list

# Caching unreachable servers

To boost the performance, when a server returns error (`404`, `500`, `502`, or response isn't in correct format), it'll be blacklisted to avoid getting called again in the future.

> This feature is also kept until the app restarts

# Update Oct 28th 2024

Invidious is now added using the same API (fetch from multiple resources and return first valid response)

App runs pretty normal without the need to log in.

> Still having the same issue where Piped just randomly throw error, I'm thinking putting Invidious before Piped because its stream seems to be more stable than Piped

### CODE REVIEW

**Comment by fast4x** [comment]
Two questions: 
Piped returned ready to play without login?
Can add Invidious streams api? you found it in extensions > Invidious, it work exactly as piped but  with only 3 instances without get it from remote.

**Comment by knighthat** [comment]
Some public instances don't require login, hence the reason why I did the multi-fetching thingy. Also the reason why I have a paragraph at the beginning of PR

 I took the dynamic path so it's expected to work across APIs. I'll have to take a look at Invidious to determine what are next steps

**Comment by fast4x** [comment]
Yes i confirm bot response from all instances that requires login.

**Comment by fast4x** [comment]
If this remains, fetch from piped instances it's useless. 
For this reason I had removed it, at least until it works.

**Comment by knighthat** [comment]
This implementation works for me. Aside from random error, I don't see why it can't be a backup plan, at least until we find a better way

Anyway, if can always test it without merging into main branch by [cherry picking](https://stackoverflow.com/questions/55108304/how-to-merge-a-pull-request-or-commit-from-a-different-repository-using-git) in your local repo

**Comment by fast4x** [comment]
The backup solution is right, but it must be based on a stable system. We do not know if and when it will be back working, so at the moment it is useless to add this logic. Btw it’s a good job, though.

**Comment by knighthat** [comment]
It's not gonna be stable and will never be. We don't have control over the API so we can't rely one node, we must add as many backup plans as we can to **reduce** the severity of the problem. Otherwise, another wave will come and we'll get the same results as we did yesterday and the day before that

I'll continue to develop Invidious on top of this implementation, please keep the PR open. Thank you!

**Comment by fast4x** [comment]
i agree but all piped instances are blocked by anti bot and require login...

**Comment by knighthat** [comment]
@fast4x Some instances don't. That's why I made it to fetch from multiple servers.

**Comment by fast4x** [comment]
Invidious when is used?

**Comment by fast4x** [comment]
Sorry, founded

**Comment by fast4x** [comment]
I've fixed loading audio formats for only audio format.

**Comment by knighthat** [comment]
can you elaborate?

**Comment by fast4x** [comment]
?

**Comment by knighthat** [comment]
> I've fixed loading audio formats for only audio format.

This

**Comment by knighthat** [comment]
I see, I thought you wanted to keep the video for some reason so I didn't filter it out

**Comment by fast4x** [comment]
No, you did a good job.

**Comment by knighthat** [comment]
thanks

**Pull request merged**
