### PR TITLE
Added expanded player to landscape mode & added back button in lyrics (not working)

### PR DESCRIPTION
**Pull request by aneesh1122**
1) I used RiMusic in my PC and saw that the controls are taking so much space so I decided to add expanded player here too. It works only when thumbnail is disabled

https://github.com/fast4x/RiMusic/assets/45353488/aabfa857-c1f9-421c-b3e3-0300d74a6d6e

2) Added back button in landscape lyrics but it's not working. Disabled the code. Look for the code from 1633 to 1645 in Lyrics.kt

### CODE REVIEW

**Comment by fast4x** [comment]
Fixed back button

**Comment by aneesh1122** [comment]
> Fixed back button

Thanks man

**Comment by fast4x** [comment]
Look..
2024-07-09_16h44_01
2024-07-09_16h44_30
2024-07-09_16h44_56

**Comment by aneesh1122** [comment]
Okay. Got it

**Pull request merged**
