### PR TITLE
Added Obtainium Button

### PR DESCRIPTION
**Pull request by DarkCrypt**
Users can now easily install and update RiMusic with Obtainium.

- Added Obtainium PNG
- Added RiMusic install link

### CODE REVIEW

**Comment by DarkCrypt** [comment]
This button is too big in README. How do I match it's size with the others?

**Comment by fast4x** [comment]
```
[<img src="./assets/images/getItAccrescent.png" alt="Accrescent" height="80">](https://accrescent.app/app/it.fast4x.rimusic)

```

**Comment by fast4x** [comment]
this is a sample with other img used

**Comment by DarkCrypt** [comment]
Right, I followed all 5 buttons (they're all the same height) and it's not the same size. Idk why it's different. Maybe I need to use `width` or something? I'll try and figure it out.

**Comment by fast4x** [comment]
I have used width, try to use width and hight

**Comment by fast4x** [comment]
I'll merge and look on it

**Comment by DarkCrypt** [comment]
Thank you!

**Pull request merged**
