### PR TITLE
Updated french language

### PR DESCRIPTION
**Pull request by NEVARLeVrai**
Updated french language, translation problem and improvement

### CODE REVIEW

**Comment by NEVARLeVrai** [comment]
Done i updated

**Comment by NEVARLeVrai** [comment]
if u cloud add me in your credit for french language :)

**Comment by fast4x** [comment]
Of corse!

**Comment by NEVARLeVrai** [comment]
im not sure if i translated everything well, but normally its good

**Comment by fast4x** [comment]
Merged, thanks

**Comment by NEVARLeVrai** [comment]
Np, u added me in the credit ? :)

**Comment by fast4x** [comment]
Of course, I'll update the page in the evening 😉

**Comment by NEVARLeVrai** [comment]
Also some translation are not in ? Like for shapes aspect heavy .... It's not in the file ?

**Comment by fast4x** [comment]
> Also some translation are not in ? Like for shapes settings: normal, heavy .... It's not in the file ?

At this moment it's extra lang file

**Comment by fast4x** [comment]
Added your name

**Comment by NEVARLeVrai** [comment]
> > Also some translation are not in ? Like for shapes settings: normal, heavy .... It's not in the file ?
> 
> At this moment it's extra lang file

Ooh ok, u will add it so I can complete french translation

**Pull request merged**
