### PR TITLE
Fixed modern rotating thumbnail

### PR DESCRIPTION
**Pull request by twistios**
These two lines fix the problem again. The `isSongPlaying && it == state.settledPage` check was already there before and I restored it. So only the recomposition on change of `state.settledPage` is really new.

### CODE REVIEW

**Comment by twistios** [comment]
Seems like have to fix it additionally for CD-animation.

**Comment by twistios** [comment]
If you don't like these extra commits, I can also create a new branch.

**Comment by fast4x** [comment]
in my test this && it == state.settledPage cause stop rotating when dismiss player.

**Comment by fast4x** [comment]
please create new pull request for specific fix...

**Comment by twistios** [comment]
What do you mean with "Dismiss player"?

**Comment by twistios** [comment]
For the condition to work, also the recomposition has to happen.

**Comment by twistios** [comment]
> please create new pull request for specific fix...

The condition is the specific fix.

**Comment by fast4x** [comment]
> What do you mean with "Dismiss player"?

when close and reopen player...

**Comment by fast4x** [comment]
So merge this?

**Comment by fast4x** [comment]
Merged, sorry i was tired.

**Comment by twistios** [comment]
No problem.

**Pull request merged**
