### PR TITLE
action bar discover button fix, fixed bugs with modern player, fixed shuffle problem, fixed thumbnail clipping

### LINKED ISSUE #2968: Show Discover button option bug
### Steps to reproduce the bug

Open settings
Click on player appearance
Disable "show discover button"

I am using player type "essential", but this seems to be the same with modern style.

### Expected behavior

The button should not be shown in the player anymore

### Actual behavior

The setting seems to be not working and the discover button is shown, whether it is enabled or disabled.

### Screenshots/Screen recordings

_No response_

### Logs

_No response_

### RiMusic version

0.6.45

### Android version

Android 14

### Additional information

_No response_

### LINKED ISSUE #2985: Issues with the cover and lyrics
### Steps to reproduce the bug

Activate and disactivate fading edge

### Expected behavior

The lyrics should show

### Actual behavior

I activated the fading edge option and I didn't like it and I removed it, now the cover appears cut off at the bottom and I can't see the lyrics, I've tried everything and it doesn't come off and when I keep the cover pressed, only 2 options appear that don't I know what they are for

### Screenshots/Screen recordings

Screenshot_20240728_090245
Screenshot_20240728_090249

### Logs

_No response_

### RiMusic version

0.6.45 and 0.6.45.1

### Android version

Android 14

### Additional information

_No response_

### LINKED ISSUE #2987: Shuffling interrupts the song playing
### Description

shuffling interrupts the current song playing and shuffles to next song right away

### Suggested Solution

when i tap on shuffle, it shuffles right away. The current song also changes. Please add a shuffle option which on tapping doesn't change the current song and acts after the current song. 

### Alternatives

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by aneesh1122**
closes #2968
closes #2987
closes #2985

### CODE REVIEW

**Comment by fast4x** [comment]
Re added discover button in queue and player, now discover work in only when Youtube Radio is invoked
Available from version 0.6.46

**Comment by aneesh1122** [comment]
> Re added discover button in queue and player, now discover work in only when Youtube Radio is invoked
> Available from version 0.6.46

Thanks dude. Could you please upload a new custom version whenever you get time?

**Comment by fast4x** [comment]
Paste log please

**Comment by aneesh1122** [comment]
> Paste crash log please 

2024-07-30T00:53:22.814:	java.lang.IndexOutOfBoundsException
	 n2.b.h(SourceFile:8) 
	 D2.i0.p(SourceFile:6) 
	 D2.w.p(SourceFile:3) 
	 u2.a0.p(SourceFile:21) 
	 k2.g.b(SourceFile:12) 
	 A0.d.B(SourceFile:1270) 
	 J.l0.d(SourceFile:255) 
	 e0.a.f(SourceFile:44) 
	 E.P.e(SourceFile:199) 
	 W.q.M(SourceFile:438) 
	 W.q.T(SourceFile:137) 
	 W.q.p(SourceFile:244) 
	 W.q.K(SourceFile:32) 
	 W.u.w(SourceFile:22) 
	 W.t0.t(SourceFile:101) 
	 W.q0.b(SourceFile:515) 
	 J0.e0.doFrame(SourceFile:7) 
	 J0.c0.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1503) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1513) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1128) 
	 android.view.Choreographer.doFrame(Choreographer.java:1037) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1481) 
	 android.os.Handler.handleCallback(Handler.java:942) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:211) 
	 android.os.Looper.loop(Looper.java:300) 
	 android.app.ActivityThread.main(ActivityThread.java:8503) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by fast4x** [comment]
would be an index not in list... I'll check it

**Comment by aneesh1122** [comment]
> would be an index not in list... I'll check it

Okay man. Sorry for the trouble.

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by aneesh1122** [comment]
> https://github.com/fast4x/RiMusic/tree/master/customVersion

1) discover is working perfectly now. It even removes songs as soon as new songs are added in the queue. Thanks

2) pause on zero volume is working only when device volume is zero. It doesn't pause when app volume is zero.

3) volume keys to change songs works but if you hold volume keys it will change songs as well as change volume. It should only change songs.

**Comment by fast4x** [comment]
Could you ask someone who has crashed if the custom now works?
I’m at work right now and I can’t do it myself

**Comment by aneesh1122** [comment]
> Could you ask someone who has crashed if the custom now works?
> I’m at work right now and I can’t do it myself 

As far as I know all the crashing problems were solved in the previous custom version.

if I find someone with crash problems I'll tell them to use the custom version.

**Comment by fast4x** [comment]
But this it's an AMAZING NOTICEEEEEEE YEAHHHHHHHHHHHH
Thanks thanks thanks thanks

**Comment by aneesh1122** [comment]
> But this it's an AMAZING NOTICEEEEEEE YEAHHHHHHHHHHHH
> Thanks thanks thanks thanks 

You're welcome dude. Anything to Improve this app :)

**Pull request merged**
