### PR TITLE
Updated French untranslated traduction 

### PR DESCRIPTION
**Pull request by NEVARLeVrai**
Updated untranslated traduction

### CODE REVIEW

**Comment by NEVARLeVrai** [comment]
@fast4x also could u add in language selection follow system ??

**Comment by fast4x** [comment]
Sorry, i don't understand... Explain...

**Comment by NEVARLeVrai** [comment]
> Sorry, i don't understand... Explain...

In the old updates for the choice of language it was automatic it followed the system, as for the theme you has an option follow the system it is possible for the languages ​​to put it back in choise

**Comment by fast4x** [comment]
Unlike themes, the initial language is selected by the system automatically. Once changed by the selector, the system uses that. Would you like to leave the system selection if you set follow the system language?

**Comment by NEVARLeVrai** [comment]
> Unlike themes, the initial language is selected by the system automatically. Once changed by the selector, the system uses that. Would you like to leave the system selection if you set follow the system language?

I didn't understand

**Comment by fast4x** [comment]
The language already follows the system language except if you set it manually. I can’t change this logic...

**Comment by NEVARLeVrai** [comment]
> Unlike themes, the initial language is selected by the system automatically. Once changed by the selector, the system uses that. Would you like to leave the system selection if you set follow the system language?


Hmm yeah by default if it use system follow it's good but u can add it in language selection like that if we want we can always activate it?

**Comment by NEVARLeVrai** [comment]
> Unlike themes, the initial language is selected by the system automatically. Once changed by the selector, the system uses that. Would you like to leave the system selection if you set follow the system language?


Hmm yeah by default if it use system follow it's good but u can add it in language selection like that if we want we can always activate it?

**Comment by NEVARLeVrai** [comment]
> The language already follows the system language except if you set it manually. I can’t change this logic...

Oh I thought we could add the option to the list and that we could activate it manually and that by default it would be activated

**Comment by NEVARLeVrai** [comment]
> The language already follows the system language except if you set it manually. I can’t change this logic...

Oh I thought we could add the option to the list and that we could activate it manually and that by default it would be activated

**Comment by NEVARLeVrai** [comment]
Did u see what I mean ?

**Comment by fast4x** [comment]
Okay, I’ve been thinking, I think I can, but do you think it’s useful?

**Comment by ikanakova** [comment]
I think it should stay as it is - whoever wants to change the language will change it in the settings. That's the same for all the other apps. I think other logic could be confusing and cause problems.

**Comment by NEVARLeVrai** [comment]
> To avoid confusion, you could select it as a language. Example, System language... It could be a simple solution.

YEAH that what i mean

**Comment by fast4x** [comment]
Implemented, available from version 0.6.12 🥇

**Pull request merged**
