### PR TITLE
Adds textoutline for "totalPlayTimes"

### PR DESCRIPTION
**Pull request by twistios**
See examples.

<details><summary>Beggin</summary>
<p>

beggin_with_outline

beggin_no_outline

</p>
</details> 

<details><summary>Comfortably Numb</summary>
<p>

comfortably_numb_with_outline

comfortably_numb_no_outline

</p>
</details> 

This is an example where my recent ideas would have helped. I also found out that merge works reliably with good results while the idea with inferring (and therefore ability not to state all fields) without merge  did NOT actually work.

### CODE REVIEW

**Comment by fast4x** [comment]
Make it optional in player appearance like textoutline for lyrics

**Comment by twistios** [comment]
Does it have to be optional? Currently it gets activated and deactivated with the default textoutline setting, that also affects the controls.

**Comment by fast4x** [comment]
You’re right I was remembering wrong, it's ok in settings

**Comment by aneesh1122** [comment]
good job @twistios. I actually overlooked queue total time because I never use it.

**Comment by fast4x** [comment]
Merged, good work, thanks.

**Pull request merged**
