### PR TITLE
Updated french with new variant

### PR DESCRIPTION
**Pull request by NEVARLeVrai**
i think @fast4x we need a new string name="french" to enable the alternative translation ?   
    
  
 Explained there https://github.com/fast4x/RiMusic/discussions/92

app/src/main/res/values-fr-rFR (with emojies)
app/src/main/res/values-fr (without emojies)

### CODE REVIEW

**Comment by NEVARLeVrai** [comment]
i think @fast4x we need a new <string name="french"> to enable the alternative translation ?

**Comment by fast4x** [comment]
Wait, first I merge, next develop the option inside RiMusic, then I create the linked variables to translate. Okay?

**Comment by NEVARLeVrai** [comment]
> Attention, build in error
>  for resource 'restart_app_please' with error: Invalid unicode escape sequence in string
> 
> Files with and without emoticons, please pay attention, when subito merge.
> Thanks you.

I haven't touched anything, I don't see the problem

**Comment by NEVARLeVrai** [comment]
> Attention, build in error
>  for resource 'restart_app_please' with error: Invalid unicode escape sequence in string
> 
> Files with and without emoticons, please pay attention, when subito merge.
> Thanks you.

I haven't touched anything, I don't see the problem

**Comment by NEVARLeVrai** [comment]
> Wait, first I merge, next develop the option inside RiMusic, then I create the linked variables to translate. Okay?

Ok

**Comment by fast4x** [comment]
It's all ok, new variant added without issue.

**Pull request merged**
