### PR TITLE
added auto sync and  Improved Modern Player

### LINKED ISSUE #2512: Autosync playlists
### Description

Please add an option to sync playlists imported from YouTube or piped automatically whenever you open the playlist.

### Suggested Solution

:)

### Alternatives

_No response_

### Additional Context

_No response_

### LINKED ISSUE #2636: [Feature]: auto sync feature for playlist and auto download music for playlist
### Description

when you start up the app, there should be some kind of auto syncing for playlist for those who frequently update their youtube playlist and same for downloading new music when the playlist is updated so that you acn expect to listen to that song when you are offline

### Suggested Solution

like an optional button in side the playlist or in the settings

### Alternatives

_No response_

### Additional Context

i am one of those who is struggling with many playlist and an auto sync for playlist will be utmost, beneficial,. it can be an optional feature inside the setting for those who doesn't want this feature

### PR DESCRIPTION
**Pull request by aneesh1122**
Implemented #2636
#2512

### CODE REVIEW

**Comment by aneesh1122** [comment]
Now you can see name of song and artists while scrolling in carousel

https://github.com/user-attachments/assets/2c06b5b6-89c0-4fbe-89db-4fe03bf8ce87

**Comment by aneesh1122** [comment]
Wait. Don't merge. This is deleting songs from non-imported playlists

**Comment by aneesh1122** [comment]
I've fixed it. Now you can merge

**Comment by aneesh1122** [comment]
I've fixed it. Now you can merge @fast4x

**Comment by fast4x** [comment]
Thanks for the precision

**Comment by aneesh1122** [comment]
> Thanks for the precision 

While I was trying auto sync I found this problem. Is it possible to improve this? This problem is also in the latest RiMusic release.

https://github.com/user-attachments/assets/1b6cc354-6d92-40d8-9c23-47a00777a6d1

**Comment by fast4x** [comment]
I'll try to improve

**Comment by aneesh1122** [comment]
Okay so this is how it works

https://github.com/user-attachments/assets/25cfae86-1d39-4472-a319-9daf82a55637

**Comment by fast4x** [comment]
> Fixes #2636
> Fixes #2512

Not fixes... implements...

**Comment by aneesh1122** [comment]
> > Fixes #2636
> > Fixes #2512
> 
> Not fixes... implements...

It is required to use 'Fixes' for GitHub to tag issues with the merge.

See, even after merging this pull those issues are still open.

**Comment by fast4x** [comment]
Issue is marked by #......

**Comment by aneesh1122** [comment]
> Issue is marked by #......

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by fast4x** [comment]
So use Resolve or Implemented, fix is related to  an error ...

**Comment by aneesh1122** [comment]
> So use Resolve or Implemented, fix is related to  an error ...

Okay

**Pull request merged**
