### PR TITLE
Updated French

### PR DESCRIPTION
**Pull request by NEVARLeVrai**
Updated emojies add new tanslation and fixed bad translation

### CODE REVIEW

**Comment by fast4x** [comment]
I’m sorry I missed that, okay.

**Comment by fast4x** [comment]
You add new French languages without emoticons?

**Comment by fast4x** [comment]
Attention, build in error for string 'restart_app_please' with error: Invalid unicode escape sequence in string

Fix it please.

**Comment by NEVARLeVrai** [comment]
> You add new French languages without emoticons? 

No I don't know how do it

**Comment by NEVARLeVrai** [comment]
> Attention, build in error for string 'restart_app_please' with error: Invalid unicode escape sequence in string
> 
> Fix it please.

Okay let me fix

**Pull request merged**
