### PR TITLE
Updated french language

### PR DESCRIPTION
**Pull request by NEVARLeVrai**
Updated french language, fixed misunderstanding and spelling conjugation

### CODE REVIEW

**Comment by NEVARLeVrai** [comment]
sorry if I do a lot of pull requests but I correct the mistakes I make I'm not the best in my language lol

**Comment by fast4x** [comment]
No problem, you can push merge when required.

**Comment by fast4x** [comment]
I'm sorry, string service_lifetime have an error, check for other similar errors, correct and push new merge.
Thanks you

**Comment by NEVARLeVrai** [comment]
> I'm sorry, string service_lifetime have an error, check for other similar errors, correct and push new merge. Thanks you

i fixed mb srry

**Pull request merged**
