### PR TITLE
fixed double tap to show thumbnail bug

### PR DESCRIPTION
**Pull request by aneesh1122**
1) added option to disable lyrics outline/stroke #2399
2) disabled expanded player when showlyricsthumbnail is enabled and also for landscape mode #2399
3) fixed double tap to show thumbnail bug
4) added space between timeline and action bar when action bar is not transparent #2399
5) Moved lyrics color and outline to lyrics settings
6) [added fluid rainbow lyrics color](https://github.com/fast4x/RiMusic/pull/2401/commits/6aa737549d742f06da792c6871ebbdbc8b41a825)
7) [added fluid rainbow lyrics outline](https://github.com/fast4x/RiMusic/pull/2401/commits/5e0f5c889d31fd0a988da7b77c807e9f74bdbec1)
8) [added option to have black gradient at bottom when gradient background is chosen] (https://github.com/fast4x/RiMusic/pull/2401/commits/470f4702de4e0de6bf81b5962403160c40ab56f9)
#2432
9) added glow to lyrics

### CODE REVIEW

**Comment by aneesh1122** [comment]
wait. don't merge it now. it seems to be causing some problems. I'll fix the issue and let you know

**Comment by aneesh1122** [comment]
@fast4x now you can merge it

**Comment by aneesh1122** [comment]
I tried to disable expanded player also for landscape mode but I'm not able to do it. I'm either able to disable it for showlyricsthumbnail or isLandscape but not both. This is the condition I'm using. Please tell me what's wrong with it

`if ((expandedplayer && !showlyricsthumbnail) || (expandedplayer && !isLandscape))`

**Comment by aneesh1122** [comment]
Finally managed to disable it also for landscape mode.

Don't worry. Landscape mode has this lyrics view


And it also has old full screen lyrics in case someone is using thumbnail for lyrics

**Comment by aneesh1122** [comment]
Moved lyrics color and outline to lyrics settings

**Comment by aneesh1122** [comment]
I did a fun little experiment. So, do you want to add this?

https://github.com/fast4x/RiMusic/assets/45353488/913e460a-fe94-49d0-8f7c-8dc7c1a136ae

**Comment by aneesh1122** [comment]
What about this one?

https://github.com/fast4x/RiMusic/assets/45353488/c95f34a5-c8a3-40ec-81e7-625fa11ad35e

**Comment by aneesh1122** [comment]
Just to be clear I've deleted the static rainbow and added only the moving rainbow gradient.

Do you guys want me to add both the moving and static rainbow colors?

**Comment by aneesh1122** [comment]
https://github.com/fast4x/RiMusic/assets/45353488/da507380-9081-41b6-a23f-e0ec1e52b031

**Comment by fast4x** [comment]
Merged, thanks for your work

**Pull request merged**
