### PR TITLE
fixes #3465

### LINKED ISSUE #3465: IllegalSeekPositionException when trying to play a song
### Steps to reproduce the bug

Use my database: [rimusic_20240828194610.db.zip](https://github.com/user-attachments/files/16789436/rimusic_20240828194610.db.zip)
1. Import the database
2. Go to "Songs" Menu
3. Select "All"
4. Scroll down far enough
5. Play a song

### Expected behavior

The song should play.

### Actual behavior

The app crashs.

### Screenshots/Screen recordings

_No response_

### Logs

<details><summary>Stack trace</summary>
<p>

````
2024-08-29T00:01:33.939:	androidx.media3.common.IllegalSeekPositionException
	 androidx.media3.exoplayer.ExoPlayerImpl.setMediaSourcesInternal(ExoPlayerImpl.java:2366) 
	 androidx.media3.exoplayer.ExoPlayerImpl.setMediaSources(ExoPlayerImpl.java:644) 
	 androidx.media3.exoplayer.ExoPlayerImpl.setMediaItems(ExoPlayerImpl.java:602) 
	 it.fast4x.rimusic.utils.PlayerKt.forcePlayAtIndex(Player.kt:76) 
	 it.fast4x.rimusic.ui.screens.home.HomeSongsModernKt$HomeSongsModern$24$1$15$6$2$1.invoke(HomeSongsModern.kt:1639) 
	 it.fast4x.rimusic.ui.screens.home.HomeSongsModernKt$HomeSongsModern$24$1$15$6$2$1.invoke(HomeSongsModern.kt:1631) 
	 androidx.compose.foundation.CombinedClickableNodeImpl$clickPointerInput$5.invoke-k-4lQ0M(Clickable.kt:792) 
	 androidx.compose.foundation.CombinedClickableNodeImpl$clickPointerInput$5.invoke(Clickable.kt:778) 
	 androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapGestures$2$1.invokeSuspend(TapGestureDetector.kt:138) 
	 kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
	 kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:175) 
	 kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:164) 
	 kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:466) 
	 kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:500) 
	 kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:489) 
	 kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:364) 
	 androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:719) 
	 androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:598) 
	 androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:620) 
	 androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:1044) 
	 androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:387) 
	 androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:373) 
	 androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:373) 
	 androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:373) 
	 androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:373) 
	 androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:229) 
	 androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:144) 
	 androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:120) 
	 androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1993) 
	 androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1944) 
	 androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1828) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801) 
	 com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:490) 
	 com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1904) 
	 android.app.Activity.dispatchTouchEvent(Activity.java:4377) 
	 androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69) 
	 com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:448) 
	 android.view.View.dispatchPointerEvent(View.java:15919) 
	 android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7021) 
	 android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6815) 
	 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6229) 
	 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6286) 
	 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6252) 
	 android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6417) 
	 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6260) 
	 android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6474) 
	 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6233) 
	 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6286) 
	 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6252) 
	 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6260) 
	 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6233) 
	 android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9211) 
	 android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9162) 
	 android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9131) 
	 android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9337) 
	 android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267) 
	 android.os.MessageQueue.nativePollOnce(Native Method) 
	 android.os.MessageQueue.next(MessageQueue.java:335) 
	 android.os.Looper.loopOnce(Looper.java:162) 
	 android.os.Looper.loop(Looper.java:294) 
	 android.app.ActivityThread.main(ActivityThread.java:8177) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
````

</p>
</details> 

### RiMusic version

0.6.49.2

### Android version

14

### Additional information

I had the problem that the original error was this (the comments are already based on my research):
<details><summary>Original error</summary>
<p>

````
2024-08-28T20:20:11.144:	g5.i  // special java.lang.IllegalStateException: "response" "cachedResponseText" "Bad response: " ". Text: \""
	 u2.B.j0(SourceFile:63) // j0(Ljava/util/ArrayList;IJZ)V
	 d6.b.M(SourceFile:31)
	 L6.k0.a(SourceFile:130)
	 w.A.b(SourceFile:18)
	 y.f1.u(SourceFile:334)
	 g7.a.i(SourceFile:9)
	 z7.C.B(SourceFile:79)
	 z7.g.s(SourceFile:105)
	 z7.g.E(SourceFile:33)
	 z7.g.i(SourceFile:17)
	 C0.L.A0(SourceFile:51)
	 C0.L.K(SourceFile:32)
	 w.j.K(SourceFile:111)
	 C0.h.h(SourceFile:157)
	 C0.h.h(SourceFile:136)
	 C0.h.h(SourceFile:136)
	 C0.h.h(SourceFile:136)
	 C0.h.h(SourceFile:136)
	 B2.c.E(SourceFile:36)
	 C0.x.c(SourceFile:142)
	 J0.y.K(SourceFile:81)
	 J0.y.m(SourceFile:383)
	 J0.y.dispatchTouchEvent(SourceFile:76)
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
	 com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:776)
	 com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1967)
	 android.app.Activity.dispatchTouchEvent(Activity.java:4548)
	 j.x.dispatchTouchEvent(SourceFile:3)
	 com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:734)
	 android.view.View.dispatchPointerEvent(View.java:16489)
	 android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:8602)
	 android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:8353)
	 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7682)
	 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7739)
	 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7705)
	 android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7908)
	 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7713)
	 android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7965)
	 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7686)
	 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7739)
	 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7705)
	 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7713)
	 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7686)
	 android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:11250)
	 android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:11119)
	 android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:11075)
	 android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:11384)
	 android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:337)
	 android.os.MessageQueue.nativePollOnce(Native Method)
	 android.os.MessageQueue.next(MessageQueue.java:335)
	 android.os.Looper.loopOnce(Looper.java:187)
	 android.os.Looper.loop(Looper.java:319)
	 android.app.ActivityThread.main(ActivityThread.java:8919)
	 java.lang.reflect.Method.invoke(Native Method)
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
````

</p>
</details> 

One might know that the crash logs are somewhat obfuscated in the release version. In this case even the Error was obfuscated.
When I tried to reproduce it on my phone, I got the problem that not only this crash happens but also one in the "misc" settings so I was not able to copy the crash log to the clipboard. Even logcat did not show any output about the crash, it seemed like the app just closed itself for no reason. Then I copied the database to my PC and there imported it into the emulator where I was able to get the crash log without obfuscation.

### PR DESCRIPTION
**Pull request by twistios**
fixes #3465 but also changes behaviour.
Currently it takes the items 0 to limit. New variant is index to index+limit (with some checks).

### CODE REVIEW

**Comment by twistios** [comment]
I also have alternative ideas.

These are all ideas
1. New variant (this commit): the queue starts with the element at the index and has maximal 'limit' amount of songs.
2. Centered: the commit is in the center of the queue (half of 'limit' before, half after).
2.1 hard center: it tries to have exactly 'limit' amount of songs
2.2 soft center: like hard center but only if index > limit/2
3. End of queue: kind of the opposite of the idea of the commit
3.1 normal variant
3.2 "guarantee variant" tries to have "limit" amount of songs
5. Windowed: the song is somewhere in the queue.
4.1 "extension variant": probably the most compatible with the original. Mostly like "end queue variant" but if end of songs list is reached, it is such that it maximizes the number of songs (end at end and then 'limit' amount of songs before it).

There are also different solutions, what happens if the number of songs is smaller then limit. Either like currently it takes all songs or alternatively be compatible with the strategy.
These options could be provided as a setting.

**Comment by twistios** [comment]
@fast4x what do you think? Should I had all options? What about base behaviour?

**Comment by fast4x** [comment]
I'll look into when possible

**Comment by twistios** [comment]
I want to implement the options.

<details><summary>Have some preview</summary>
<p>

````
val queueLimit = QueueSelection.START_OF_QUEUE
                                        val itemsRange = if (items.size < maxSongsInQueue.number) items.indices
                                            else when (queueLimit){
                                                QueueSelection.DEFAULT -> 0..<maxSongsInQueue.number.toInt()
                                                QueueSelection.START_OF_QUEUE ->
                                                    index..<min(index+maxSongsInQueue.number.toInt(), items.size)
//                                                QueueSelection.SOFT_CENTERED -> TODO()
//                                                QueueSelection.HARD_CENTERED -> TODO()
//                                                QueueSelection.END_OF_QUEUE -> TODO()
//                                                QueueSelection.END_OF_QUEUE_GUARANTEED -> TODO()
//                                                QueueSelection.WINDOWED -> TODO()
                                            else -> 0..<maxSongsInQueue.number.toInt()
                                        }
                                        val itemsLimited = items.slice(itemsRange)
                                        val playIndex = when {
                                            (queueLimit == QueueSelection.START_OF_QUEUE) -> 0
                                            else -> index
                                        }
                                        binder?.stopRadio()
                                        binder?.player?.forcePlayAtIndex(
                                            itemsLimited.map(SongEntity::asMediaItem),
                                            playIndex
                                        )
````

</p>
</details>

I added a new Enum-class.

**Comment by twistios** [comment]
Ok, maybe some ideas actually do not make much sense. I will see, what actuallly works.

**Comment by twistios** [comment]
The base implementation with four options is added now. Currently the to-be default is activated (it is basically like the original (buggy) implementation for it's valid range.
Selecting the other options is currently todo. Also see the commit message for more details.

**Comment by fast4x** [comment]
Can upload mini video please?

**Comment by twistios** [comment]
For the videos I will use max songs in queue = 50 (so that it is easier to see).

**Comment by twistios** [comment]
<details><summary>END_OF_QUEUE_WINDOWED demo</summary>
<p>
https://github.com/user-attachments/assets/fc7c74df-1b11-40fa-8d09-930b6e1375f5
</p>
</details>

**Comment by fast4x** [comment]
So you set in a fixed way what type of selection to make, it’s not a new entry in the settings, I understand?

**Comment by twistios** [comment]
I will also add a settings item later, the last commit was such that you can see the code already.

**Comment by twistios** [comment]
In theory one could already merge this (as it is currently "backwards-compatible), but the merged code would not contain all added features.

**Comment by twistios** [comment]
For some reason the video does not want to load so I add it again.

**Comment by twistios** [comment]
<details><summary>Details</summary>
<p>

https://github.com/user-attachments/assets/634d3654-6fbe-4950-a491-3ed1ed56ee4d


</p>
</details>

**Comment by twistios** [comment]
<details><summary>START_OF_QUEUE demo</summary>
<p>


https://github.com/user-attachments/assets/13ef340f-6b12-460c-93a6-a940eb5b9642



</p>
</details>

**Comment by fast4x** [comment]
Ok nice solution, thanks I'll merge now

**Comment by fast4x** [comment]
Available from version 0.6.50

**Comment by twistios** [comment]
What about settings?

**Comment by twistios** [comment]
<details><summary>CENTERED demo</summary>
<p>

https://github.com/user-attachments/assets/d83e7f23-0198-48f2-bc76-eaefdc970f19

</p>
</details>

**Comment by twistios** [comment]
<details><summary>END_OF_QUEUE demo</summary>
<p>

https://github.com/user-attachments/assets/c755ba27-a42e-4fe1-9a25-39fd8c75aba0

</p>
</details>

This variant is not very useful for all cases, but I guess someone might try it and like it.

**Comment by fast4x** [comment]
Ok I've merged with one fix in val queueLimit moved outside and changed type to remember.

**Comment by twistios** [comment]
<details><summary>Settings demo</summary>
<p>

rimusic_demo_queue_selection_settings

</p>
</details> 

I already created a demo for the settings part of this.

**Comment by fast4x** [comment]
Don't add for now

**Pull request merged**
