### PR TITLE
Improved Modern Player

### PR DESCRIPTION
**Pull request by aneesh1122**
I was trying to fix the repeating songs problem but I could not fix it. I found some other problems which I've fixed.

### CODE REVIEW

**Comment by fast4x** [comment]
Repeated songs it's fixed, depends by database...

**Comment by aneesh1122** [comment]
> Repeated songs it's fixed, depends by database...

you've fixed it? that's great. could you please upload a new custom version after merging this pull request?

**Comment by fast4x** [comment]
Sorry repeated songs... in home songs... not in queue...

**Comment by aneesh1122** [comment]
> Sorry repeated songs... in home songs... not in queue...

okay. any idea why that is happening? I'll read everything I could about pager but found no solution.

**Comment by fast4x** [comment]
For now not

**Comment by aneesh1122** [comment]
> I can try to fix but how can reproduce bug?

Do exactly what I did in this video

1) play any song
2) put the app in the background
3) change the song using buttons in notification
4) The 3rd song will be played again after the 4th song.

**Comment by fast4x** [comment]
Ah ok Great info! Thanks

**Comment by fast4x** [comment]
Unfortunately it work, bug not reproduced

**Comment by fast4x** [comment]
Ok! Fixed, the actions of next and previous were different between the visual player and the one in the notification area... same with android auto.

**Comment by aneesh1122** [comment]
> Ok! Fixed, the actions of next and previous were different between the visual player and the one in the notification area... same with android auto.

Wow. Thanks man. I didn't think the problem would be with notification buttons because it works fine with essential buttons.

Could you pls upload a new custom version?

**Comment by fast4x** [comment]
Done
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by aneesh1122** [comment]
> Done
> https://github.com/fast4x/RiMusic/tree/master/customVersion

Now the song is getting repeated after the 13th song.

Tap the 'next' button in the notification 14 times. On the 14th time the 3rd song in queue will start playing.

The situation is improved so you're on the right track.

**Comment by aneesh1122** [comment]
> This is crazy, I'll check it again.

https://github.com/user-attachments/assets/3fa184aa-3f20-4ef5-93d1-2b42eaba24f9

In this video you can see that after 'circles'(14th song) it plays 'night changes'(3rd song)

**Pull request merged**
