### PR TITLE
Implemented folders in On Device page

### PR DESCRIPTION
**Pull request by JZITNIK-github**
Just implemented folder in On Device page. User can choose if they want folders or not in the settings. I hope there are not gonna be many bugs.

### CODE REVIEW

**Comment by JZITNIK-github** [comment]
Sorting is not working. Fixing it.

**Comment by fast4x** [comment]
Don’t worry if bugs come out, we’ll fix them, good job.

**Comment by fast4x** [comment]
Crash when click on a folder...
Attached log, it seems relate unique id in lazy...
[log.txt](https://github.com/fast4x/RiMusic/files/14781781/log.txt)

**Comment by fast4x** [comment]
Same crash with list songs without folder, crash on key...

**Comment by JZITNIK-github** [comment]
Ok I'll look at it.

**Comment by JZITNIK-github** [comment]
Oh I know where the problem is. I'll fix it soon.

**Comment by fast4x** [comment]
Perfect

**Comment by sayyid5416** [comment]
@fast4x This should be optional. Earlier it was easy to access all on-device songs at one place.

**Comment by fast4x** [comment]
Can switch mode by Miscellaneous settings

**Pull request merged**
