### PR TITLE
Updated french and mores emojies

### PR DESCRIPTION
**Pull request by NEVARLeVrai**
Updated french more emojies, im testing UI with emojies

### CODE REVIEW

**Comment by NEVARLeVrai** [comment]
if someones for the next versions can tell if its look good

**Comment by ikanakova** [comment]
I think it would be nice if users had a choice of emoji and non-emoji version.

**Comment by NEVARLeVrai** [comment]
> I think it would be nice if users had a choice of emoji and non-emoji version.

yeah youright, im just testing for the next version, and after if i think i will remove. I just want to see how its look like

**Comment by NEVARLeVrai** [comment]
> I think it would be nice if users had a choice of emoji and non-emoji version.

but how we can do 2 versions ?

**Comment by fast4x** [comment]
> > I think it would be nice if users had a choice of emoji and non-emoji version.
> 
> but how i can do 2 versions ?

Actually not possible.

**Comment by ikanakova** [comment]
> I think it would be nice if users had a choice of emoji and non-emoji version.
> 
> but how i can do 2 versions ?
> 
> Actually not possible.

I'll try to study how to do it.

**Comment by fast4x** [comment]
This request have build error on

Failed to flatten XML for resource 'by_tapping_on_the_thumbnail' with error: Invalid unicode escape sequence in string

Fix it please.

**Pull request merged**
