### PR TITLE
some additions and changes

### LINKED ISSUE #2488: Overlapping Artist and Title name
### Steps to reproduce the bug

When play the music, it's overlapping 

### Expected behavior

No overlapping 

### Actual behavior

The name and title of artist is overlapping as shown on the image 

### Screenshots/Screen recordings

PXL_20240626_033726271

### Logs

_No response_

### RiMusic version

0.6.40.1

### Android version

13

### Additional information

Android car player, NWD_K2501(T5)

### LINKED ISSUE #2529: Bottom gradient does not work in landscape mode
### Steps to reproduce the bug

1. Turn on bottom gradient 
2. Play song
3. Enter landscape mode

https://github.com/fast4x/RiMusic/assets/76595855/7bd7a9e5-d436-4460-8c7d-57f6c3c599f1

### Expected behavior

Expected to see bottom gradient both in portrait and landscape modes if enabled

### Actual behavior

Bottom gradient doesn't work in landscape mode

### Screenshots/Screen recordings

_No response_

### Logs

_No response_

### RiMusic version

0.6.41

### Android version

Android 13

### Additional information

I suppose this bug could affect Android Auto users as normally they use app in landscape mode

### PR DESCRIPTION
**Pull request by aneesh1122**
1. added 'show thumbnail for visualizer' option
2. transferred all the thumbnail related options under 'showthumbnail'. Disabling 'showthumbnail' will hide all the thumbnail options
3. bottom spacer condition changed to playerPlayButtonType != PlayerPlayButtonType.Disabled
4. added extra padding option for android head unit. fixes #2488
5. removed gradient from landscape mode and added a constant dark shade. fixes #2529

I haven't found any bugs. If I do I'll try to fix it or revert back the changes.

### CODE REVIEW

**Comment by fast4x** [comment]
With it **added 'show thumbnail for visualizer' option** 
visualizer is showing with and without thumbnail?
It's important that visualizer is available independently by show thumbnail setting...

**Comment by fast4x** [comment]
Visualizer must be available with or without thumbnail show.

When show thumbnail is disabled, visualizer with is same of player page ..

**Comment by aneesh1122** [comment]
> With it **added 'show thumbnail for visualizer' option** 
> visualizer is showing with and without thumbnail?
> It's important that visualizer is available independently by show thumbnail setting...

https://github.com/fast4x/RiMusic/assets/45353488/bdca4122-a43b-4a49-ba4d-25b3cb23ccaa

https://github.com/fast4x/RiMusic/assets/45353488/1fdef021-28f8-42d7-8f72-b8f8c238ce5c

**Comment by aneesh1122** [comment]
https://github.com/fast4x/RiMusic/assets/45353488/ecc7b604-6984-47be-b304-0b487b6f21fa

**Comment by fast4x** [comment]
Nice, thanks for details.

**Comment by aneesh1122** [comment]
> Nice, thanks for details.

I loved the new visualizer designs. Could you please fix the pixelated thumbnails from 34-36 visualizers?

btw the visualizer thumbnail doesn't change when the song changes.

**Pull request merged**
