### PR TITLE
DEMO | Better SongItem

### PR DESCRIPTION
**Pull request by knighthat**
# Description

This push aims to fix some minor bugs, i.e. miss alignment in playlist songs. Furthermore, it also removes unwanted elements such as download button on local songs.

UnusualGap

# Implemented

### No download on local songs

Download button will no longer be visible on local songs

NoDownloadButtonForLocal

### More accessible select checkbox & drag anchor

Previously, drag anchor and checkbox are designed/placed in a way that is really hard to interact on smaller screen. Especially, checkbox expanded the height of SongItem, this is a very bad UX.

This push includes a small change to the mechanism, where checkbox and drag anchor can only be enabled one at the time, and the location of both is not interfere with the song. In other words, this push made it more accessible to those who have bigger finger that are using smaller phones.

[Single_Action.webm](https://github.com/user-attachments/assets/47612e07-3eb5-4b9d-a1e0-42160950d0cc)

### Individual download state

> It's harder to see because the process is fairly quick and because songs are downloaded simultaneously. In the future I'll consider changing the process to download in sequence to preserve data. 

https://github.com/user-attachments/assets/aad4fbbe-c3f5-4899-b1ca-6e639201d8c9

# Planned

- Custom left/right swipe
- Fix thumbnail not cached properly (will post clip(s) later)

> More will be updated later

### CODE REVIEW

**Comment by fast4x** [comment]
@knighthat please, do not rewrite the code on pieces that work. These days i am fixing errors on unexpected errors.
So i won’t merge this code, btw Thanks again.

**Comment by knighthat** [comment]
Firstly, the code was literally copy & paste with comments on top. I didn't want to touch the old SongItem because I was afraid that it would break what's working.

Secondly, you failed to acknowledge my last PRs which mentioned about potential bugs and errors (hardening the foundation instead of keep pushing new changes). Instead of fixing it, you keep applying patches, this will only fix whatever is showing instead of fixing the root cause.

I'm disappointed that you keep this happening while simultaneously denying my attempts to help. Have a good day!

**Comment by fast4x** [comment]
I assure you that I appreciate your work, you are also very good. I’m sorry that you get angry.

**Comment by knighthat** [comment]
I'm not angry, just disappointed

**Pull request closed without merging**
