### PR TITLE
New Modern Player. More details Inside

### PR DESCRIPTION
**Pull request by aneesh1122**
1) new modern player
2) added option to not blur background when lyrics are disabled
3) fixed 'expandedlyrics' preference issues
4) added new layout for player artists selection dialog

Problems:
1) You can't align first page with alignment/arrangement commands. You have to provide padding amount for the first page. I tried to find out thumbnail dimensions to give padding values suitable for every device but I was not able to. Therefore I added a custom slider which controls padding. everyone can set the padding according to their wish.

https://github.com/user-attachments/assets/93ed4dab-e124-4838-b338-31ff68e7bc76

2) play a song and put the app in background or turn off the display. wait for the next song to play and let it play for 10-15 secs. Open the player directly now. The song starts from the beginning.

https://github.com/user-attachments/assets/efbb79a1-70e8-4b64-878c-1fcf52a428af

3) It has problem with radio. It crashes when a song's radio is started. Start radio and change to the next song. Crash. Works fine from quick picks.

https://github.com/user-attachments/assets/0a49d593-b934-4bb4-a936-25818c544491

4) previous song starts playing when exit from lyrics in landscape mode

https://github.com/user-attachments/assets/9346349d-a839-45b2-8948-f16ebfa7a66d

### CODE REVIEW

**Comment by aneesh1122** [comment]
@fast4x try it out and let me know what you think.

**Comment by fast4x** [comment]
Beautifull work, it's nice effect.
I've implemented artist image loading, must improved but it work.
Please update repo...
https://github.com/user-attachments/assets/e2914f20-8f58-4420-bb8a-673c37c67b06

**Comment by aneesh1122** [comment]
> Please update repo...

thanks.

btw to know the real beauty of fading effect, do this

1) set thumbnail size to expanded
2) use background blur background and set the blur to maximum.
3) play 'these walls' by dua lipa

now see the results.

**Comment by aneesh1122** [comment]
btw I was wondering, if modern player has already loaded next thumbnails, why does background cover still loads cover again when the song is changed?

**Comment by fast4x** [comment]
Because it acts as if it has not realized that the image is already cached. I tried various ways but nothing.

**Comment by aneesh1122** [comment]
> Because it acts as if it has not realized that the image is already cached. I tried various ways but nothing.

maybe because the value of "data" keeps changing according to the index of current media. if it had a fixed value then it would have been possible I think

**Comment by aneesh1122** [comment]
Found a bug

Sometimes it loads automatically, sometimes you have to manually enter artist page to load it in dialog.


https://github.com/user-attachments/assets/14843332-1465-48c7-80ca-dfc4f31e4a96

**Comment by aneesh1122** [comment]
One more observation. It will always load thumbnail automatically for specific artists.

For Example, it will always load the thumbnail automatically for 'Miley Cyrus' and 'marshmello' but it never loads automatically for 'Beyoncé'

**Comment by fast4x** [comment]
Maybe occur if artist it's just saved in the database. If you try again after show artist page, thumbnail load without problems.

How to enable carousel like in video, I'm not found how... ahahah 😂

**Comment by aneesh1122** [comment]
> If you try again after show artist page, thumbnail load without problems

Yeah. The photos in the artist page loads just fine. I'm sure you did a quick job and you can definitely make it perfect.

For carousel, go to settings and enable carousel. There you can also find different thumbnail sizes for carousel. In the player, hold on the thumbnail to open the custom slider where you can adjust spacing and offset from the top.

**Comment by aneesh1122** [comment]
> Maybe occur if artist it's just saved in the database. If you try again after show artist page, thumbnail load without problems

The 'id' which the artist page uses shouldn't be different from 'id' used by artist selection dialogue. Right?

**Comment by aneesh1122** [comment]
@fast4x I was trying to fix problems 2 and I couldn't do it. I know the basic idea of how to fix it.

This is my code


Explanation:
When you open the app and it scrolls to the current playing song because of 1st launched effect, it should check the position of played duration. If it's more than 0 secs then it should set change = false.

In the second launched effect It should use this check value and change songs only if change = true.

**Pull request merged**
