### PR TITLE
Optimized website and added loading screen

### PR DESCRIPTION
**Pull request by JZITNIK-github**
I optimized the website by reducing size of the images. You can't see the difference in quality but the images are way smaller. Also I added some loading screen so users with slow internet don't stare at blank screen while the page is loading. If you want different loader just let me know.

### CODE REVIEW

**Comment by JZITNIK-github** [comment]
Btw fast4x if you own domain rimusic.xyz you should point it to the github page not just redirect so users can be on rimusic.xyz not fast4x.github.io/RiMusic. 

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

**Comment by fast4x** [comment]
Yesterday I tried the custom domain but it was error a check dns, try again today

**Comment by fast4x** [comment]
I've tryed now, successfully confirmed custom domain and certificate ssl.

**Comment by JZITNIK-github** [comment]
> I've tryed now, successfully confirmed custom domain and certificate ssl.

Yeah, website works for me. Perfect

**Comment by fast4x** [comment]
Thanks, soon i add a special thanks for you in acknowledgement.

**Comment by JZITNIK-github** [comment]
> Thanks, soon i add a special thanks for you in acknowledgement

Thank you so much

**Comment by JZITNIK-github** [comment]
Btw are you planing on creating new Crowdin project for the website or it will just stay in the repo?

**Comment by fast4x** [comment]
I had thought about it but on Crowdin only one free project is allowed. I’m considering creating something in house hosting on the domain RiMusic.xyz

**Comment by JZITNIK-github** [comment]
> I had thought about it but on Crowdin only one free project is allowed. I’m considering creating something in house hosting on the domain RiMusic.xyz

I didn't knew that crowdin supports only one project. On their pricing page they're saying `Unlimited public projects`. https://crowdin.com/pricing

**Comment by fast4x** [comment]
It would be nice to have a solution at home, but it is very complicated.

**Comment by fast4x** [comment]
Yes in a subdomain of rimusic.xyz

**Comment by JZITNIK-github** [comment]
I would host it but my electricity is really unreliable. Do you know any crowdin alternative that you could host? And exposing it would be kinda easy using Cloudflare tunnels.

**Comment by fast4x** [comment]
This https://www.doc3.com/ but I haven’t had time to read it well. Try to understand yourself if you can.

**Comment by JZITNIK-github** [comment]
Yeah I'll look into that.

**Comment by JZITNIK-github** [comment]
From what i understood doc3 only supports one project at the time. I've also looked at [weblate](https://weblate.org/cs/) but it is self-host only.

**Comment by JZITNIK-github** [comment]
Btw @fast4x the website is down for like 3 minutes after someone commits even when it doesn't affect the website. It would be probably good to make it so it rebuilds the website only when folder `docs` is changed or something like that.

**Comment by fast4x** [comment]
I'll check configuration soon

**Pull request merged**
