### PR TITLE
modified expanded player

### PR DESCRIPTION
**Pull request by aneesh1122**
Fixed Spacing

### CODE REVIEW

**Comment by aneesh1122** [comment]
I hope the spacing is fine now?

**Comment by fast4x** [comment]
> I hope the spacing is fine now?

i try now

**Comment by fast4x** [comment]
Now lyrics exoand button in action bar have any effect when click, anything change...

**Comment by aneesh1122** [comment]
> Now lyrics exoand button in action bar have any effect when click, anything change...

It will change after you minimise and reopen the player

**Comment by fast4x** [comment]
Ahhh ok it's a bug that I'll fix... ok sorry

**Comment by aneesh1122** [comment]
> Ahhh ok it's a bug that I'll fix... ok sorry

You need a list of bugs?

**Comment by fast4x** [comment]
ok make simple list

**Comment by aneesh1122** [comment]
> ok make simple list 

https://github.com/fast4x/RiMusic/pull/2321#issuecomment-2171045020

**Comment by aneesh1122** [comment]
This one is not a huge problem but it has the similar problem as 'expand player' button

When the blurred cover background is chosen and double tapped, the thumbnail should appear but it appears only after you minimize and open the player.

**Pull request merged**
