### PR TITLE
fixed "lyrics are limited by thumbnail size" #2451

### PR DESCRIPTION
**Pull request by aneesh1122**
after pulling hairs for almost a week FINALLY I DID IT. I proudly present you

now lyrics will always be full screen no matter what your thumbnail size is

https://github.com/fast4x/RiMusic/assets/45353488/3c6a843e-7f19-40e1-995d-4aa1513823be

### CODE REVIEW

**Comment by fast4x** [comment]
Great

**Comment by DavidDiaz377** [comment]
How to put it without blurring the cover background? I want to have it just like in the video!

**Comment by aneesh1122** [comment]
> How to put it without blurring the cover background? I want to have it just like in the video!

https://github.com/fast4x/RiMusic/issues/2488#issuecomment-2190702196

**Comment by DavidDiaz377** [comment]
You are amazing, thank you!

**Comment by aneesh1122** [comment]
> You are amazing, thank you!
> 

You're welcome. Feel free to ask if you need any more help

**Pull request merged**
