### PR TITLE
Modified "Show next songs in player"

### LINKED ISSUE #1302: Improved next songs in player
### Description

In my opinion, the current layout for the next song in player is too cluttered

### Suggested Solution

Change the layout of the next song in player

Something like this
Untitled90_20240330100626

• Since there is a lot of empty space below the play/pause button, it should be moved there
• It doesn't need to show two songs
• Add `Up Next` text so the users know what it is, or perhaps a new icon

### Alternatives

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by aneesh1122**
Fixes #1302

### CODE REVIEW

**Comment by fast4x** [comment]
What is the result of these implementatios?

**Comment by aneesh1122** [comment]
> What is the result of these implementations?

https://github.com/fast4x/RiMusic/assets/45353488/47caee4e-74dd-4269-a921-bf7bbc87e66b

**Comment by fast4x** [comment]
Please do not make changes on player, lyrics and thumbnails linked until the next release.

**Comment by aneesh1122** [comment]
> Please do not make changes on player, lyrics and thumbnails linked until the next release.

Okay. Looks like something big is coming 😅

**Comment by fast4x** [comment]
No, I made some arrangements and it was complicated to merge everything, something could blow up.

**Comment by aneesh1122** [comment]
> No, I made some arrangements and it was complicated to merge everything, something could blow up.

Okay

**Comment by fast4x** [comment]
For example, the blur level is now maintained even if you turn lyrics or visualizers on. Before, even if you removed it, it was reinserted...

**Comment by aneesh1122** [comment]
> For example, the blur level is now maintained even if you turn lyrics or visualizers on. Before, even if you removed it, it was reinserted...

I made it that way. Whenever you turn on lyrics or visualizer when showthumbnail = false, it will add a constant blurstrength of 25 and it cannot be changed.

**Comment by fast4x** [comment]
Using it, I don’t like it because it changes what I set before. Example, if I remove the blur, I don’t have to review it if I use lyrics or visualizer. Why? Because if I removed it before, it means that I prefer the background with the cover image and above I see the visualizer and the text directly in the background not blurred.

This way, you can configure the lyrics text with all the effects you have developed or show your preferite visualizer over your preferite cover.
It's very nice.

**Comment by aneesh1122** [comment]
> Using it, I don’t like it because it changes what I set before. Example, if I remove the blur, I don’t have to review it if I use lyrics or visualizer. Why? Because if I removed it before, it means that I prefer the background with the cover image and above I see the visualizer and the text directly in the background not blurred.
> 
> This way, you can configure the lyrics text with all the effects you have developed or show your preferite visualizer over your preferite cover.
> It's very nice.

People will complain about visibility that's why I added blur for lyrics. Even I like to see the album cover without blur but when I turn on lyrics I want to focus more on lyrics so blur was a good idea.



You can barely see anything here so blur is necessary.

**Comment by fast4x** [comment]
ok

**Comment by aneesh1122** [comment]
> 
> 
> Not good for you?

The highlighted line is perfectly visible but other lines are not. Especially the top and bottom lines.

Let's do it this way. Let's remove the constant blur and add a blur which can be controlled. You can set it to zero and others who want can set it to other values.

**Comment by fast4x** [comment]
To avoid adding another parallel blur control we use the same then.

https://github.com/fast4x/RiMusic/assets/1484476/df92cfa8-8359-4702-9c30-5ae884d3f5b5

**Comment by aneesh1122** [comment]
> To avoid adding another parallel blur control we use the same then.
> 
> https://github.com/fast4x/RiMusic/assets/1484476/df92cfa8-8359-4702-9c30-5ae884d3f5b5
> 
> 

Will this blur amount also apply when isShowingLyrics = false?

I want something like this

https://github.com/fast4x/RiMusic/assets/45353488/c051cc92-7d30-4027-9ef8-076b23b137c3


When isShowingLyrics = false, blurstrength = 0

**Comment by fast4x** [comment]
It's applied always

**Comment by aneesh1122** [comment]
> It's applied always

Pls let blurstrength = 0 when 'showthumbnail' is disabled and lyrics are not on.

When I disable the 'showthumbnail' I want to see the cover without any blur. When I activate the lyrics I want to see the lyrics so the background should be blurred.

**Comment by aneesh1122** [comment]
> oookkkk I'll recove it like before but only for lyrics...

use this code

.transformations(
                listOf(
                  if (showthumbnail) {
                      BlurTransformation(
                          scale = 0.5f,
                          radius = blurStrength.toInt(),
                          //darkenFactor = blurDarkenFactor
                      )
                  }
                   else
                    BlurTransformation(
                        scale = 0.5f,
                        //radius = blurStrength2.toInt(),
                        radius = if (isShowingLyrics) blurStrength.toInt() else 0,
                        //darkenFactor = blurDarkenFactor
                    )
                )
            )

**Comment by aneesh1122** [comment]
> oookkkk I'll recove it like before but only for lyrics...

use this code

`
.transformations(
                listOf(
                  if (showthumbnail) {
                      BlurTransformation(
                          scale = 0.5f,
                          radius = blurStrength.toInt(),
                          //darkenFactor = blurDarkenFactor
                      )
                  }
                   else
                    BlurTransformation(
                        scale = 0.5f,
                        //radius = blurStrength2.toInt(),
                        radius = if (isShowingLyrics) blurStrength.toInt() else 0,
                        //darkenFactor = blurDarkenFactor
                    )
                )
            )
`

**Comment by aneesh1122** [comment]
> > oookkkk I'll recove it like before but only for lyrics...
> 
> use this code
> 
> ```
> .transformations(
>                 listOf(
>                   if (showthumbnail) {
>                       BlurTransformation(
>                           scale = 0.5f,
>                           radius = blurStrength.toInt(),
>                           //darkenFactor = blurDarkenFactor
>                       )
>                   }
>                    else
>                     BlurTransformation(
>                         scale = 0.5f,
>                         //radius = blurStrength2.toInt(),
>                         radius = if (isShowingLyrics) blurStrength.toInt() else 0,
>                         //darkenFactor = blurDarkenFactor
>                     )
>                 )
>             )
> ```

this way you can have control over lyrics blur when isShowingLyrics and have no blur for !showthumbnail && !isShowingLyrics

**Comment by fast4x** [comment]
ok

**Comment by fast4x** [comment]
Done, for visualizer not applied blur


`else
                    BlurTransformation(
                        scale = 0.5f,
                        //radius = blurStrength2.toInt(),
                        radius = **if (isShowingLyrics && !isShowingVisualizer) 25 else 0,**
                        //darkenFactor = blurDarkenFactor
                    )`

**Comment by aneesh1122** [comment]
> Done, for visualizer not applied blur
> 
> 
> else
>                     BlurTransformation(
>                         scale = 0.5f,
>                         //radius = blurStrength2.toInt(),
>                         radius = **if (isShowingLyrics && !isShowingVisualizer) 25 else 0,**
>                         //darkenFactor = blurDarkenFactor
>                     )
> 

1) have you changed the condition for visualizer? Earlier the condition was (isShowingEqualizer). Have you changed it to (isShowingVisualizer)?

2) !isShowingVisualizer is not really required there because whenever you turn on lyrics isShowingVisualizer turns off automatically

**Comment by fast4x** [comment]
it work, stop...

**Comment by fast4x** [comment]
!isShowingVisualizer is not really required there because whenever you turn on lyrics isShowingVisualizer turns off automatically...
for now...

**Comment by aneesh1122** [comment]
> for now

okay

**Comment by aneesh1122** [comment]
@fast4x How is this 'show next songs in player'? I've even added the marquee to it.

https://github.com/fast4x/RiMusic/assets/45353488/94cedb3d-c231-4325-b4a8-11ea1c11778b

**Comment by fast4x** [comment]
Simple it show prior and next songs... Implement it after new release...

**Comment by aneesh1122** [comment]
I keep getting this error in Android Music whenever I pull from github

`POST git-upload-pack (327 bytes) POST git-upload-pack (953 bytes) 6185 bytes of body are still expected fetch-pack: unexpected disconnect while reading sideband packet early EOF fetch-pack: invalid index-pack output`

Any idea how I can fix this?

**Comment by fast4x** [comment]
It seems that while downloading the content, it disconnects creating a partial download.

Try to make a new clone of the repo...

**Comment by fast4x** [comment]
If new clone not work, I'll try to delete a bundletool file from repo...

**Comment by aneesh1122** [comment]
My internet is a little unstable right now. I'll try it again after it gets stable.

Btw I can give you the changed codes which will fix the 'explicit' icon getting behind the title. You'll have to add it manually.

**Comment by fast4x** [comment]
wait and fix you

**Pull request merged**
