### PR TITLE
bypass youtube when it comes to audio playback

### PR DESCRIPTION
**Pull request by knighthat**
I'm looking for better implementation. But this is good enough for now

### CODE REVIEW

**Comment by fast4x** [comment]
Isn't necessary because all work well with login, included listen and download.
Piped, Invidious and more, actually don't work.
Thanks for patience.

**Comment by aneesh1122** [comment]
> Isn't necessary because all work well with login, included listen and download.
> Piped, Invidious and more, actually don't work.
> Thanks for patience.

Keep this pull request for Foss version if it's working

**Comment by knighthat** [comment]
Wdym `all work well with login`? I'm looking into Piped because this is the fastest backup plan while we're figuring out how to bypass this blocking

**Comment by aneesh1122** [comment]
> Wdym `all work well with login`? I'm looking into Piped because this is the fastest backup plan while we're figuring out how to bypass this blocking

Yt login has been implemented. There will be 2 versions from now on, Foss and full, like in Innertunes.

Thanks for fixing this bug. It will help in the Foss version. The full version is able to play and download songs without any issue.

Although the next release will only have the full version, next week's release will most probably have both the Foss and full version.

**Comment by fast4x** [comment]
> Wdym `all work well with login`? I'm looking into Piped because this is the fastest backup plan while we're figuring out how to bypass this blocking

Yep, in my devices now all work with login without issues. In the future i don't know... so this merge will be do later.

**Comment by fast4x** [comment]
> How do you access account?

In next version there's a login similar piped in miscellaneous settings, after release will be improved.

**Comment by SureshTimma** [comment]
Can I sync all music from YouTube music to RiMusic or vice versa by YTM login?

**Comment by aneesh1122** [comment]
> Can I sync all music from YouTube music to RiMusic or vice versa by YTM login?

No

**Comment by fast4x** [comment]
> Can I sync all music from YouTube music to RiMusic or vice versa by YTM login?

There's no hurry.

**Comment by knighthat** [comment]
moved to #4166

**Pull request closed without merging**
