### PR TITLE
added check if currentVisualizer is too large

### PR DESCRIPTION
**Pull request by twistios**
Without this, there would be a problem if the number of visualizers is reduced one day.

### CODE REVIEW

**Comment by twistios** [comment]
(it also makes it easier for testing)

**Comment by aneesh1122** [comment]
use this

`if (currentVisualizer < 0 || currentVisualizer > visualizersList.lastIndex) currentVisualizer = 0`

use as less code as possible

**Comment by twistios** [comment]
> use this
> 
> `if (currentVisualizer < 0 || currentVisualizer > visualizersList.lastIndex) currentVisualizer = 0`
> 
> use as less code as possible

Done

**Comment by fast4x** [comment]
Actually it work, what effect has your **if**..
https://github.com/user-attachments/assets/b58fe6bf-c3f9-4d8a-a4d2-46a47264650b

**Comment by twistios** [comment]
Maybe I missunderstand the code but it seems to me that there will be an error if `currentVisualizer` is set to 37 (for example possible if a new visualizer was added), then one visualizer is removed in a new version and then there will be a crash/... if you want to start the app after the update (because 37 does not exist anymore).

**Comment by fast4x** [comment]
But in release this not happen... it work without any issue

**Comment by twistios** [comment]
I actually did not test that there will be a bug but now I can prove it.

First I was not able to reproduce it, but my code base already contained the fix (the old version of it) :smile: 

Screenshot from 2024-07-13 14-07-33

rimusic_visualizer_37

(the new visualizer number 1 is the one that I am currently working on)

https://github.com/user-attachments/assets/3a34e34f-24c7-4dfa-b840-e0825ad58cd7

<details><summary>The crash that will happen</summary>
<p>

````
2024-07-13 14:12:00.972 29531-29531 AndroidRuntime          it.fast4x.rimusic.debug              E  FATAL EXCEPTION: main
                                                                                                    Process: it.fast4x.rimusic.debug, PID: 29531
                                                                                                    java.lang.ArrayIndexOutOfBoundsException: length=36; index=36
                                                                                                    	at java.util.Arrays$ArrayList.get(Arrays.java:4210)
                                                                                                    	at it.fast4x.rimusic.extensions.nextvisualizer.NextVisualizerKt$NextVisualizer$3$2.invoke(NextVisualizer.kt:196)
                                                                                                    	at it.fast4x.rimusic.extensions.nextvisualizer.NextVisualizerKt$NextVisualizer$3$2.invoke(NextVisualizer.kt:167)
                                                                                                    	at androidx.compose.ui.viewinterop.ViewFactoryHolder$updateBlock$1.invoke(AndroidView.android.kt:375)
                                                                                                    	at androidx.compose.ui.viewinterop.ViewFactoryHolder$updateBlock$1.invoke(AndroidView.android.kt:375)
                                                                                                    	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2441)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:502)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:258)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
                                                                                                    	at androidx.compose.ui.viewinterop.AndroidViewHolder$runUpdate$1.invoke(AndroidViewHolder.android.kt:185)
                                                                                                    	at androidx.compose.ui.viewinterop.AndroidViewHolder$runUpdate$1.invoke(AndroidViewHolder.android.kt:179)
                                                                                                    	at androidx.compose.ui.viewinterop.AndroidViewHolder.onAttachedToWindow(AndroidViewHolder.android.kt:276)
                                                                                                    	at android.view.View.dispatchAttachedToWindow(View.java:23227)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3698)
                                                                                                    	at android.view.ViewGroup.addViewInner(ViewGroup.java:5552)
                                                                                                    	at android.view.ViewGroup.addView(ViewGroup.java:5328)
                                                                                                    	at android.view.ViewGroup.addView(ViewGroup.java:5268)
                                                                                                    	at android.view.ViewGroup.addView(ViewGroup.java:5240)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.addAndroidView(AndroidComposeView.android.kt:1117)
                                                                                                    	at androidx.compose.ui.viewinterop.AndroidViewHolder$layoutNode$1$3.invoke(AndroidViewHolder.android.kt:376)
                                                                                                    	at androidx.compose.ui.viewinterop.AndroidViewHolder$layoutNode$1$3.invoke(AndroidViewHolder.android.kt:375)
                                                                                                    	at androidx.compose.ui.node.LayoutNode.attach$ui_release(LayoutNode.kt:510)
                                                                                                    	at androidx.compose.ui.node.LayoutNode.attach$ui_release(LayoutNode.kt:500)
                                                                                                    	at androidx.compose.ui.node.LayoutNode.attach$ui_release(LayoutNode.kt:500)
                                                                                                    	at androidx.compose.ui.node.LayoutNode.insertAt$ui_release(LayoutNode.kt:316)
                                                                                                    	at androidx.compose.ui.node.UiApplier.insertBottomUp(UiApplier.android.kt:31)
                                                                                                    	at androidx.compose.ui.node.UiApplier.insertBottomUp(UiApplier.android.kt:21)
                                                                                                    	at androidx.compose.runtime.changelist.Operation$PostInsertNodeFixup.execute(Operation.kt:619)
                                                                                                    	at androidx.compose.runtime.changelist.Operations.executeAndFlushAllPendingOperations(Operations.kt:309)
                                                                                                    	at androidx.compose.runtime.changelist.FixupList.executeAndFlushAllPendingFixups(FixupList.kt:50)
                                                                                                    	at androidx.compose.runtime.changelist.Operation$InsertSlotsWithFixups.execute(Operation.kt:550)
                                                                                                    	at androidx.compose.runtime.changelist.Operations.executeAndFlushAllPendingOperations(Operations.kt:309)
                                                                                                    	at androidx.compose.runtime.changelist.ChangeList.executeAndFlushAllPendingChanges(ChangeList.kt:81)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:984)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:1013)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:678)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:578)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1687)
2024-07-13 14:12:00.974 29531-29531 AndroidRuntime          it.fast4x.rimusic.debug              E  	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:1069)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8919)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@7d3dbb0, androidx.compose.ui.platform.MotionDurationScaleImpl@c445a29, StandaloneCoroutine{Cancelling}@14911ae, AndroidUiDispatcher@a13bb4f]
````

</p>
</details>

**Comment by fast4x** [comment]
It's normal this crash, you have removed control...

**Pull request closed without merging**
