### PR TITLE
Search results are clickable and editable now

### PR DESCRIPTION
**Pull request by KyNarec**
It always annoyed me that after I searched for a specific song and i had a typo I had to rewrite my whole search query again.
I made it so that you can click on your search query, then the search screen opens up again with your query already inserted so that you do not have to rewrite the whole query.
I wanted to mention that I did not find a open issue with a similar suggestion.

# After
[Screen_recording_20241007_225326.webm](https://github.com/user-attachments/assets/5010df94-1dff-4950-9b62-2481280767ad)

### CODE REVIEW

**Comment by fast4x** [comment]
Hi thanks, but this is just implemented. Also check better your merge before send, there are a lot of bin files.

**Comment by KyNarec** [comment]
Is it wrong how I implemented it, or is it already implemented? Otherwise can I just send anouther pull request withiut the bin files?

**Comment by fast4x** [comment]
https://github.com/user-attachments/assets/efbb5b5b-055a-4354-b269-8a6562cbe95f

look

**Comment by KyNarec** [comment]
But I find this not being intuitive and I also questioned multiple RiMusic users and they preferred my approach, because they found it more intuitive

**Comment by KyNarec** [comment]
I could also make it toggleable in the settings...

**Comment by fast4x** [comment]
But your approach it's same as me...

**Comment by KyNarec** [comment]
The user only needs to tab here:
image

**Pull request closed without merging**
