### PR TITLE
Updated french language

### PR DESCRIPTION
**Pull request by NEVARLeVrai**
Updated french language, and added improvements

### CODE REVIEW

**Comment by NEVARLeVrai** [comment]
I forgot a capital letter and a text

**Comment by NEVARLeVrai** [comment]
fix

**Comment by NEVARLeVrai** [comment]
Also add this in translation file mean system, dark ect... what is written in English if possible

**Comment by fast4x** [comment]
Option theme, at this moment isn't possible to translate

**Comment by fast4x** [comment]
For the future, \ before ' is required.
Example: **d'album** became **d\'album**
I'll fix it in this merge

**Comment by NEVARLeVrai** [comment]
This d\'album like this ?

**Comment by fast4x** [comment]
Yes without space.
Merged, i have fixed \' in this merge

**Pull request merged**
