### PR TITLE
 improved fav icon visibility, fixed mini queue swiping, hidden horizontal swipe for modern player

### LINKED ISSUE #3067: [Feature]: improve the ui color vs bg color contrast
### Description

It really hard to see the ui maybe there should be more clear contrast.
Most often I can't notice if i have added a music to the favorite or not
Here is an example 
Screenshot_2024-08-03-00-13-01-785_it fast4x rimusic
Screenshot_2024-08-03-00-13-04-340_it fast4x rimusic

### Suggested Solution

Please improve the contrast

### Alternatives

The contrast or ui looks fine or better on the notification bar

### Additional Context

_No response_

### LINKED ISSUE #3080: Next song queue scroll reset when >1 songs displayed
### Steps to reproduce the bug

- `settings` Enable Show next song queue
- `settings` Set Songs number to show more than 1
- `player` play a song, then try scroll on next song queue

### Expected behavior

Scroll just fine like when using Set Songs number to show = 1

### Actual behavior

Scroll position reset to initial position when Set Songs number to show > 1

### Screenshots/Screen recordings

_No response_

### Logs

_No response_

### RiMusic version

0.6.46

### Android version

Android 11

### Additional information

_No response_

### LINKED ISSUE #3090: Disable horizontal swipe doesn't work when…
### Steps to reproduce the bug

Background colors>blurred song cover
Disable show thumbnail
Enable "disable horizontal swipe"
Open any song
Swipe left or right

### Expected behavior

Since "disable horizontal swipe" is enabled player ui should not behave in contradiction.

### Actual behavior

Horizontal swipe works regardless of "disable horizontal swipe" setting when blurred song cover is enabled and show thumbnail is disabled.

### Screenshots/Screen recordings

_No response_

### Logs

_No response_

### RiMusic version

0.6.46

### Android version

Android 13

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by aneesh1122**
closes #3090
closes #3080
closes #3067

### CODE REVIEW

**Comment by shahriarlabib000** [comment]
Wow that was quick! Thank you very much. When will i be able to download the version with changes?

**Comment by aneesh1122** [comment]
> Wow that was quick! Thank you very much. When will i be able to download the version with changes?

Next friday

**Comment by fast4x** [comment]
@aneesh1122 best RiMusic developer

**Comment by aneesh1122** [comment]
> @aneesh1122 best RiMusic developer 

Thanks :)

**Comment by aneesh1122** [comment]
hey @fast4x, could you please apply .distinct() to queue? I tried a number of ways but I was not able to delete duplicate songs from queue.

Discover works great but there are a lot of duplicate songs.

**Comment by fast4x** [comment]
Yes, under development

**Comment by aneesh1122** [comment]
> Yes, under development 

Okay :)

**Comment by shahriarlabib000** [comment]
Update available?

**Comment by aneesh1122** [comment]
> Update available?

Download the latest update?

**Comment by shahriarlabib000** [comment]
Ahh found it . I was looking in fdroid

**Comment by shahriarlabib000** [comment]
Omg blur is gone noo 😭

**Comment by aneesh1122** [comment]
> Omg blur is gone noo 😭

Disable `No Blur when Lyrics is Disabled` in settings.

**Comment by shahriarlabib000** [comment]
Thank you so much

**Pull request merged**
