### PR TITLE
added shadow to modern controls disabled button according to the shape

### PR DESCRIPTION
**Pull request by aneesh1122**
Screenshot_20240626_225958
Screenshot_20240626_225946

### CODE REVIEW

**Comment by aneesh1122** [comment]
Wait. Don't merge now. I'm making the shadows bigger for next/previous buttons

**Comment by fast4x** [comment]
So the modern buttons no longer have the box?

**Comment by aneesh1122** [comment]
> So the modern buttons no longer have the box?

Only disabled buttons don't have shadows. Rest of the buttons are unaffected

**Comment by aneesh1122** [comment]
https://github.com/fast4x/RiMusic/assets/45353488/78d6c6a6-debd-42fe-a19a-b82dc174eaee

**Comment by fast4x** [comment]
nice

**Pull request merged**
