### PR TITLE
bug_report.yml | Notify user about YT blocking audio stream | Section to upload video

### PR DESCRIPTION
**Pull request by knighthat**
YT is at it again with the LOGIN_REQUIRED. I added a section to let people know about this problem and let them know that they don't have to open a ticket for this problem.

Furthermore, I also added a section where user can submit a short video

### CODE REVIEW

**Comment by twistios** [comment]
It seems that it not really is blocked as it sometimes works fine. But only after update/switching between songs.

**Comment by knighthat** [comment]
That's literally how they make you think it's our fault. By making the service unpleasant instead of not working 100%. 

If you want to see it for youself. You can install Android Studio, clone our source code and run it in debug mode. Most of the time when the player crash is due to `LOGIN_REQUIRED` error

**Comment by twistios** [comment]
I have already contributed (even if it were small contributions) to this app. And yes, also I have seen that it says "LOGIN_REQUIRED" as reason for some errors.

**Comment by twistios** [comment]
I am also pretty sure that it is related to them changing something but it is not blocked but only less reliable as before.

**Comment by fast4x** [comment]
Be quiet please, new version is released, streaming now is more stable, download for now not.
I'm rewrite download feature in another way

**Comment by ParasyteGS** [comment]
Hi, the new version has another problem now a compatible audio format could not be found, this is solved if I press the play button again, I think the song can be reloaded in case of this mistake

**Comment by fast4x** [comment]
Yes this is the problem, song not always reloaded... and stopped by login required api error.

**Comment by knighthat** [comment]
I discovered some tweaks that may reduce the chance of being block. But it's so unstable and complicated, I'll stay low for a couple days to test it more

**Comment by fast4x** [comment]
yes better solution, I'll try to rewrite part of playerservice for test in another way. Much complicated...

**Pull request merged**
