### PR TITLE
Fixed disable horizontal swipe and show embedded name

### PR DESCRIPTION
**Pull request by JZITNIK-github**
Just fixed disabling horizontal swipe in the player and implemented shoring embedded name in the on device songs. If no embedded name is found, the file name is displayed as before.

### CODE REVIEW

**Comment by fast4x** [comment]
Hi, thanks, horizontal swipe Is Just fixed, remove it please.

**Comment by fast4x** [comment]
Every Friday i commit with release new version

**Comment by JZITNIK-github** [comment]
Oh, so that means that you fixed it but not pushed it to the repo yet? Sorry I'm bit confused.

**Comment by fast4x** [comment]
Exactly, you can make fixes or develop what you like, I just ask you to check if the ticket has a label implemented or fixed, or to be sure, you can comment on the ticket that interests you so that I can tell you if I’m working...
I push commit every Friday when release new version...

**Comment by JZITNIK-github** [comment]
Oh, ok got it. I didn't even saw the issue i just found the bug when i was using the app. I tried to search for the issue but there is a lot of issues and i probably missed it. I'll create a new PR without my first commit.

**Comment by fast4x** [comment]
Thanks you for your work, your name Will be in app and in project page.

**Comment by JZITNIK-github** [comment]
Thank you. If you want help with anything, tag me and I'll help.

**Comment by fast4x** [comment]
Thanks you!

**Pull request closed without merging**
