### PR TITLE
New landscape layout

### PR DESCRIPTION
**Pull request by aneesh1122**
https://github.com/fast4x/RiMusic/assets/45353488/6ed93af5-cac0-4630-933c-3803a5cc5ce3

### CODE REVIEW

**Comment by aneesh1122** [comment]
What do you think about this layout? I had to work a lot on this one

**Comment by aneesh1122** [comment]
What do you think about this layout? I had to work a lot on this one @fast4x

**Comment by fast4x** [comment]
Is amazing, why not try to add in player?

**Comment by aneesh1122** [comment]
> Is amazing, why not try to add in player?

In portrait mode? There isn't enough space.

In landscape mode there was a lot of empty space so I decided to fill up the places.

This will look good only on big screens like PC, tablet, android auto etc

**Comment by fast4x** [comment]
I'll try to implement similar with minus space..

**Comment by aneesh1122** [comment]
> I'll try to implement similar with minus space..

Okay, before that could you pls add animations to it?

Only the middle thumbnail has animation.

I tried to add animations but couldn't do it

**Comment by fast4x** [comment]
ok I'll try

**Comment by aneesh1122** [comment]
> ok I'll try

what do you think about #2667 ? This will look great with the new layout.

**Comment by fast4x** [comment]
is related...

**Comment by aneesh1122** [comment]
> is related...

yeah. If it's implemented in the new landscape layout it will look great. Horizontal pager require pagecount value and I don't know how to get the queue number. I was also getting a lot of errors so after trying for a few hours I gave up.

**Pull request merged**
