### PR TITLE
Fixed issue #267 "Null artist on search".

### PR DESCRIPTION
**Pull request by locxter**
Fixed issue #267 "Null artist on search". See the issue for more information

### CODE REVIEW

**Comment by locxter** [comment]
Please test it yourself, but it worked flawlessly for me :)

**Comment by locxter** [comment]
Other than that it works fine though and hasn't had a single hick-up in the last hour of extensive usage

**Comment by fast4x** [comment]
Thanks for your collaboration.

**Comment by fast4x** [comment]
Available from version 0.6.16

**Pull request merged**
