### PR TITLE
Updated french and emojies

### PR DESCRIPTION
**Pull request by NEVARLeVrai**
Updated french and emojies

### CODE REVIEW

**Comment by fast4x** [comment]
It would be better to translate the normal French file also on Crowdin .

**Comment by NEVARLeVrai** [comment]
> It would be better to translate the normal French file also on Crowdin .

Already did on the crowdin but u didn't merge it :/

**Comment by fast4x** [comment]
From Crowdin not, merge this

**Comment by NEVARLeVrai** [comment]
> From Crowdin not, merge this

When new update come?

**Comment by NEVARLeVrai** [comment]
I did it didn't worked

**Comment by fast4x** [comment]
Let’s see next time if it works

**Comment by fast4x** [comment]
Hello, if you make a small change on Crowdin, let’s see if it arrives..

**Comment by NEVARLeVrai** [comment]
> Hello, if you make a small change on Crowdin, let’s see if it arrives..

Also when new ri music update come?

**Comment by fast4x** [comment]
I've tested a little modify in french on Crowdin and it's ok, arrived and merged.

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/pull/193

**Pull request merged**
