### PR TITLE
New and improved icons

### PR DESCRIPTION
**Pull request by ikanakova**

### CODE REVIEW

**Comment by fast4x** [comment]
@ikanakova alcum icon it's so?
Screenshot_20240327_143804

**Comment by fast4x** [comment]
Screenshot_20240327_144235

**Comment by ikanakova** [comment]
> @ikanakova album icon it's so?

Seems OK to me. It's a rectangular album (which should change with color) with a disc cutout in the middle (which should be in the background color).

**Comment by fast4x** [comment]
Ok, thanks for confirmation.

**Pull request merged**
