### PR TITLE
Implement blur and darkness slider adjustment.

### PR DESCRIPTION
**Pull request by bbyeen**
Long press on background to open blur slider.

image
#1965 #1959

### CODE REVIEW

**Comment by aneesh1122** [comment]
Thanks man

**Comment by fast4x** [comment]
Merged but darker function not work, disabled for now.
Implemented without darker slider and fixed any bug.

**Comment by aneesh1122** [comment]
> Merged but darker function not work, disabled for now.
> Implemented without darker slider and fixed any bug.

Any idea why it is not working? I was looking forward to this specific function 😅

**Comment by fast4x** [comment]
At the moment I do not know, I can not devote more time, thanks to @bbyeen however there is already control over the blur

**Comment by aneesh1122** [comment]
> At the moment I do not know, I can not devote more time, thanks to @bbyeen however there is already control over the blur

Okay fast4x. Please keep it in your 'to do list' at least and try to implement whenever you get time.

**Pull request merged**
