### PR TITLE
Create strings.xml

### PR DESCRIPTION
**Pull request by siggi1984**
add russian language

### CODE REVIEW

**Review by fast4x — CHANGES_REQUESTED** [review]
Hi, i cannot perform this merge, because the file must be created in the app\src\main\res\values-ru\strings.xml folder
Please move it. 
Thank you

**Comment by fast4x** [comment]
Wow amazing!, thank

**Comment by siggi1984** [comment]
stupid question on my part how can I create the folder "app\src\main\resvalues-ru\". I can not get it to work. Or could you create the folder and then I put the file in it.

**Comment by fast4x** [comment]
Ok don't worry, I created the folder and inserted your file. Thank.
So I cancel the merge.
To create the folder, you can create it directly in the file manager and copy the file into it.
Or if you use Android studio, you can right-click on the ...res folder and click on the "Android Resource Directory" menu item, name directory value in values_ru, select Local, select country code and press ok.

**Pull request closed without merging**
