### PR TITLE
Updated StatsForNerds displaying in player V2

### PR DESCRIPTION
**Pull request by twistios**
- fixed StatsForNerds not working in modern player with thumbnail enabled

### CODE REVIEW

**Comment by twistios** [comment]
StatsForNerds (bottom version) also works for essential player. It does not get shown if thumbnail is enabled in essential player.

**Comment by twistios** [comment]
Thumbnail-StatsForNerds is always enabled if essential.

**Comment by fast4x** [comment]
Do you have tested better it?

**Comment by twistios** [comment]
> Do you have tested better it?

What do you mean with "tested better"?

**Comment by fast4x** [comment]
have tried new code? it work?

**Comment by twistios** [comment]
Landscape mode does not work correctly but this is a known issue as far as I know.
Will add some pictures as demo.

**Comment by aneesh1122** [comment]
wait, you need to hide stats for nerds in settings too. do this

if (showThumbnail && playerType == PlayerType.Essential)

add this condition in appearancesettings for stats for nerds

**Comment by twistios** [comment]
`if (!(showthumbnail && playerType == PlayerType.Essential))`

**Comment by aneesh1122** [comment]
> `if (!(showthumbnail && playerType == PlayerType.Essential))`

yeah this will work too. try it yourself to see if everything's working fine.

**Comment by twistios** [comment]
<details><summary>Essential No thumbnail</summary>
<p>

rimusic_statsForNerdDemo1

</p>
</details> 

<details><summary>Essential thumbnail</summary>
<p>

rimusic_statsForNerdsDemo2

</p>
</details> 

<details><summary>Modern no thumbnail</summary>
<p>

rimusic_statsForNerdsDemo3

</p>
</details> 

<details><summary>Modern thumbnail</summary>
<p>

rimusic_statsForNerdsDemo4

</p>
</details>

**Comment by twistios** [comment]
<details><summary>Settings</summary>
<p>

rimusic_statsForNerds_settings_1

rimusic_statsForNerds_settings_2

</p>
</details>

**Comment by fast4x** [comment]
I can merge?

**Comment by twistios** [comment]
It was fine to merge it I think. The code was fixing what I should and landscape still has problems as before.

**Pull request merged**
