### PR TITLE
Added Modern Queue

### LINKED ISSUE #2103: [Feature]: Transparent queue page
### Description

Player and queue page

### Suggested Solution

looks cool

### Alternatives

_No response_

### Additional Context

added a dark shade with 50% opacity and blurred the player a bit to improve the visibility

### PR DESCRIPTION
**Pull request by aneesh1122**
closes #2103

I have used [haze](https://github.com/chrisbanes/haze) to blur player

https://github.com/user-attachments/assets/411fd3c2-34ed-4927-a62c-eb0b9140b318

### CODE REVIEW

**Comment by fast4x** [comment]
Have you checked apk size with haze?

**Comment by aneesh1122** [comment]
> Have you checked apk size with haze?

9.49 mb. Your apk will be lower I guess cuz your release apk size is always smaller than my release apk

**Comment by fast4x** [comment]
Ok

**Comment by twistios** [comment]
https://github.com/chrisbanes/haze/issues/140
It might be that haze does not properly support pre-android 12.

**Comment by aneesh1122** [comment]
> https://github.com/chrisbanes/haze/issues/140
> It might be that haze does not properly support pre-android 12.

Yeah it doesn't. It won't blur if its pre-android 12.

They can still have the transparent background though.

**Pull request merged**
