### PR TITLE
Update QuickPicks.kt

### PR DESCRIPTION
**Pull request by SureshTimma**
changed No of rows of songs in quick picks from 2 to 3. 
removed new albums section

### CODE REVIEW

**Comment by fast4x** [comment]
New albums section is a part of discovery, it's bad to remove this.

**Comment by SureshTimma** [comment]
> New albums section is a part of discovery, it's bad to remove this.

Atleast give toggle to turn on or off!

**Comment by SureshTimma** [comment]
> New albums section is a part of discovery, it's bad to remove this.

Change rows from 2 to 3. Please

**Comment by fast4x** [comment]
Ok

**Comment by fast4x** [comment]
Implemented, available from version 0.6.28

**Comment by fast4x** [comment]
Implemented, available from version 0.6.28

**Comment by fast4x** [comment]
Implemented show/hide time remaining song.
Available from version 0.6.28

**Comment by SureshTimma** [comment]
my request is to use google icons(solid, rounded) which are very best looking, simple and great aligned
@fast4x

**Comment by fast4x** [comment]
RiMusic use Ionicons open source and @ikanakova icons.

**Pull request closed without merging**
