### PR TITLE
added haptic feedback to some important bottom sheets

### LINKED ISSUE #2602: [Feature]: Add haptic feedback (vibration) for long press in contextual action mode on list item
### Description

When performing a long press on a list item to activate the contextual action mode, the application currently does not provide haptic feedback. Adding a brief vibration would enhance the user experience by providing tactile confirmation that the action has been recognized, aligning with common practices in user interface design.

## Steps to Reproduce:

1. Open the application.
2. Perform a long press on a list item to activate the contextual action mode.
    E.g.: over a song to start radio.

## Expected Behavior:

The device should provide a brief vibration (haptic feedback) when the long press is recognized and the contextual action mode is activated.

## Actual Behavior:

No haptic feedback is provided.

## Motivation

The addition of haptic feedback serves to:

1. Improve user experience by providing tactile confirmation of actions.
2. Align with best practices observed in popular applications where haptic feedback enhances usability.

### Suggested Solution

Implement haptic feedback (vibration) when the user performs a long press to activate the contextual action mode. This can be achieved using Android's `Vibrator` API to trigger a short vibration upon recognition of the long press gesture.

### Alternatives

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by aneesh1122**
added haptic feedback to long click bottom sheet at quick picks, songs, playlists, albums, artists and long tap to open queue from mini player

fixes #2602

### CODE REVIEW

**Comment by fast4x** [comment]
include also #890 

Thanks @aneesh1122

**Comment by aneesh1122** [comment]
> include also #890 
> 
> Thanks @aneesh1122 

Haptic is not included in swipe actions 😅

You've added new swipe gestures in the next update so I'll add it when the next update is out.

**Comment by fast4x** [comment]
Of course... swipe it's in my repo... and availble from next version

**Comment by aneesh1122** [comment]
> Of course... swipe it's in my repo... and availble from next version

check out my latest pull request. I've added haptic to mini player swipe

**Pull request merged**
