### PR TITLE
only take audio formats

### PR DESCRIPTION
**Pull request by knighthat**
As discussed in [this post](https://github.com/fast4x/RiMusic/pull/4166#issuecomment-2443556816). I've gone ahead and add a filter to make sure all formats are audio only.

### CODE REVIEW

**Comment by fast4x** [comment]
There is no reason for this commit, have just  fixed. Thanks.
Also I've fixed another bug in fetching instances without data connection.

**Comment by fast4x** [comment]
Yep i've fixed both

**Comment by knighthat** [comment]
thanks

**Comment by knighthat** [comment]
Hi, did you push it to upstream? I can't find it in the code base and video formats are still being used

**Pull request closed without merging**
