### PR TITLE
added haptic feedback to mini player swipe and search results bottom sheet

### PR DESCRIPTION
**Pull request by aneesh1122**
added haptic feedback to mini player swipe gesture and search results longclick bottom sheet

### CODE REVIEW

**Comment by fast4x** [comment]
Man, in the speed of the day I hadn’t even noticed all the changes you made on the player, they’re really nice. Using RiMusic during the day I really like the version without thumbnail and blur of the cover. Congratulations.

**Comment by aneesh1122** [comment]
> Man, in the speed of the day I hadn’t even noticed all the changes you made on the player, they’re really nice. Using RiMusic during the day I really like the version without thumbnail and blur of the cover. Congratulations.

Thanks man. As I said before, you are the Inspiration behind me learning kotlin. You must be the only dev out there who updates his app weekly and works on it unconditionally.

I've used many music apps but always felt like something is missing. RiMusic had a lot of things I liked so I just added some additional things to make it perfect. Whenever I think of something which should be added I try to add it.

I know nothing about coding so whatever I add I first learn how to implement it.

There are things I couldn't fix like picking the correct dominant color but I'll help you fix whatever bugs I can.

There are some ungrateful people but what can I say about them. They are everywhere and you have to tolerate them. I won't do any of his requests though.

**Comment by fast4x** [comment]
A suggestion for you:
There are some ungrateful people but what can I say about them. They are everywhere and you have to tolerate them. I won't do any of his requests though.

There’s no reason to repeat it, ok? Please.

**Comment by aneesh1122** [comment]
> A suggestion for you:
> There are some ungrateful people but what can I say about them. They are everywhere and you have to tolerate them. I won't do any of his requests though.
> 
> There’s no reason to repeat it, ok? Please.

Believe me, I try not to argue but that guy really got on my nerves. I actually had to work very hard to implement his requests but he wasn't being thankful. He acted as if he was paying me to do things.

All I asked him to do was be grateful. He could have simply thanked me and end the matter there. He continued arguing with me even though he contributed nothing and I actually implemented his requests.

**Comment by fast4x** [comment]
All this does you credit, for this reason you have to get away from nervousness and look ahead. Forget and focus on yourself.

**Comment by aneesh1122** [comment]
> All this does you credit, for this reason you have to get away from nervousness and look ahead. Forget and focus on yourself.

Yeah. I'll try to ignore people like him from now on. Had to give him something before ignoring him though. Sorry for that 😅

**Comment by aneesh1122** [comment]
Could you please look into #2592? I tried it myself but I'm not able to understand how dark is differing from light. I even changed .coerceAtMost values but even that didn't change anything.

**Comment by fast4x** [comment]
Yes, but after other priorities...

**Comment by aneesh1122** [comment]
> Yes, but after other priorities...

sure. thanks

**Pull request merged**
