### PR TITLE
automatically build & deploy custom version every week

### PR DESCRIPTION
**Pull request by knighthat**
This makes CI/CD a little bit less heavy. Update of Custom Version is more predictable

### Requirements

RELEASE_TOKEN secret with `read & write` permissions to `actions` and `content` of fine-grained token

Screenshot_20241008_132042

### Demo

Screenshot_20241008_130937

### CODE REVIEW

**Comment by knighthat** [comment]
I can change it to Friday if you want.

**Comment by fast4x** [comment]
set Tuesday

**Comment by knighthat** [comment]
schedule set

**Comment by fast4x** [comment]
Sorry, i not have experience with RELEASE TOKEN, how to set your requirement?

**Comment by fast4x** [comment]
Here configured release_token secret in repo for actions and result for first run...
2024-10-09_16h56_23
2024-10-09_16h56_43

**Comment by knighthat** [comment]
# Create TOKEN

1. Click on your avatar on the top-right of github page
2. Then, click on `settings` 

  <details> 
    <summary>Illustration</summary>
     
  </details>

3. Go to `Developer Settings`

  <details> 
    <summary>Illustration</summary>
     
  </details>

4. Choose `Fine-grained tokens` from `Personal access tokens` dropdown menu
5. Generate new token

  <details> 
    <summary>Illustration</summary>
     
  </details>

6. Fill the form
  * Token name: Anything you want
  * Expiration: After this date, you'll have renew it (usually 30-60 days is ok)
  * Repository: Should limit to fast4x/RiMusic repository only
  * Permission (you might have to click on `Repository permissions` to get all permissions): Change permissions of `Actions` and `Contents` to `Read and write`

  <details> 
    <summary>Illustration</summary>
     
  </details>

7. `Generate token` at the bottom of the form
8. Copy token

  <details> 
    <summary>Illustration</summary>
     
  </details>

# Set `RELEASE_TOKEN`

1. Go back to [RiMusic repository](https://github.com/fast4x/RiMusic)
2. Click on `Settings` at the top bar
3. Select `Actions` from `Secrets and variables` drop-down menu
4. `New repository secret`
  <details> 
    <summary>Illustration</summary>
     
  </details>
5. Name the secret `RELEASE_TOKEN` (mandatory)
6. Paste the token to the bottom box
7. `Add secret`
  <details> 
    <summary>Illustration</summary>
     
  </details>

# Test secrete key

Start this [workflow](https://github.com/fast4x/RiMusic/actions/workflows/weekly-deploy-customversion.yml) manually. If everything runs OK and new tag + build are created then the key is setup correctly

**Comment by fast4x** [comment]
Thank you for the assistance and patience in telling me what to do. It worked perfectly, I think you are a genius. Thanks!!!!!!!!!

**Comment by knighthat** [comment]
@fast4x Congratulations! I see that you have successfully pushed a pre-release. From now on, it'll be pushed automatically on Tuesday.

I'll have to fix the logo's link. You'll hear  back from me in a few hours

**Pull request merged**
