### PR TITLE
added textoutline for "SelectorArtistsDialog"

### PR DESCRIPTION
**Pull request by twistios**
See examples. 

<details><summary>Light mode</summary>
<p>

goodboys_no_outline
goodboys_outline

</p>
</details> 

<details><summary>Dark mode</summary>
<p>

don_diabolo_no_outline
don_diabolo_outline

</p>
</details> 

I used the same colors as everywhere else so if you don't like it with light mode then it is not my fault.

@aneesh1122 you also forgot this menu. :smile:
I think the same is also true for the visualizer controls.

### CODE REVIEW

**Comment by twistios** [comment]
There is also a bug that the artist image does not load unless you have been on the artist page already.

**Comment by twistios** [comment]
There is also an `Suspicious indentation` in the file `Dialog.kt`.

    Suspicious indentation: This is indented but is not continuing the previous expression (val colorPaletteMode...) (Previous statement here)

I can also fix this directly or not if you don't like me to @fast4x.

**Comment by aneesh1122** [comment]
Good job but there's one problem though. This outline will appear only if you have the song cover as background(That's how I've coded it)

I think you should remove the text outline and add a gradient and make it permanent.

**Comment by twistios** [comment]
Nope. Seems like I accidentally made it work with that also or do you mean something else? @aneesh1122 
Screenshot_20240806_100942

**Comment by twistios** [comment]
Ah, I see. It is one of these settings that stay activated even if the settings option is gone. And because I have activated it with background cover, it still was active.

**Comment by aneesh1122** [comment]
> Ah, I see. It is one of these settings that stay activated even if the settings option is gone. And because I have activated it with background cover, it still was active.
> So the toggle is gone in that case.

Yeah. So If someone wants to deactivate it they have to change the player background to Album cover again.

So just remove the outline and add a small gradient at the bottom and make it permanent.

**Comment by twistios** [comment]
I think that this should rather be a change in the settings as the text outline stays enabled also at the other places.

**Comment by aneesh1122** [comment]
> I think that this should rather be a change in the settings as the text outline stays enabled also at the other places.

I don't think anything should be changed in settings because text outline is added only for album cover background. It doesn't make sense anywhere else because there's no text visibility problems so text outline option should be visible only when cover background is chosen.

If you really want text outline so bad then remove the condition of textoutline and make it permanent.

**Pull request merged**
