### PR TITLE
fixed some problems of downloaded tab and caches

### PR DESCRIPTION
**Pull request by twistios**
- also now hidden downloaded songs are now always shown
- downloaded songs are now also removed from Download manager (previously was not so when deleting all via data settings, deleted downloads where still shown as downloaded but are actually not)

### CODE REVIEW

**Comment by twistios** [comment]
Current problems: 
- Eye icon is still there for downloads tab
- downloads storage usage does not update after deleting all downloaded songs (if one does not exist the menu first)

**Comment by twistios** [comment]
> downloads storage usage does not update after deleting all downloaded songs (if one does not exist the menu first)

This can be easily fixed, but not fully. Because the "deleted" state does not get reset, so it can happen only once while in that menu

**Comment by twistios** [comment]
Another problem is that the number potentially does not update, if it is changed by new data.

**Comment by twistios** [comment]
> Another problem is that the number potentially does not update, if it is changed by new data.

Solved

**Comment by twistios** [comment]
Eye problem remains, but otherwise these changes should be ok. Hope it does not break with the other changes.

**Comment by fast4x** [comment]
merged

**Pull request merged**
