### PR TITLE
prevents now playing song from getting deleted in discover mode

### PR DESCRIPTION
**Pull request by aneesh1122**
I don't know how you did coding for player. Try to do something similar to this

### CODE REVIEW

**Comment by fast4x** [comment]
Please don't push modification in player and queue before new release... thanks :)

**Comment by aneesh1122** [comment]
> Please don't push modification in player and queue before new release... thanks :)

okay. this code is working fine?

**Comment by fast4x** [comment]
I can't add this because code it's totally rewritten.

**Comment by aneesh1122** [comment]
> I can't add this because code it's totally rewritten.

I thought as much that's why I asked. It's okay. when the update is out I'll look at the code

**Comment by fast4x** [comment]
Excuse me, i'have been added fix in new code... thanks
2024-07-18_18h23_40

**Comment by aneesh1122** [comment]
> Excuse me, i'have been added fix in new code... thanks 2024-07-18_18h23_40

it's working properly?

**Comment by fast4x** [comment]
Yes, it work.
I've fixed another error with crash in queue if current item is last in queue...

**Comment by aneesh1122** [comment]
> Yes, it work.
> I've fixed another error with crash in queue if current item is last in queue...

That's great.

Btw is it possible to make discover work only with radio? I tried to do it but was not able to.

**Comment by fast4x** [comment]
Of course but after new release... I'll work on it.

**Comment by aneesh1122** [comment]
> Of course but after new release... I'll work on it.

Ofcourse. I'm also working on something. I'm sure you'll like it.

**Comment by fast4x** [comment]
😜😋

**Comment by aneesh1122** [comment]
> 😜😋

https://github.com/user-attachments/assets/29adcfcd-39aa-4994-b95f-d7a49a2c007d

**Comment by fast4x** [comment]
I like it 😜😋

**Comment by aneesh1122** [comment]
> I like it 😜😋

it's not over yet. There are things I tried to Implement but I couldn't. I want songs to be changed when I swipe the thumbnail. The method I tried is not working fine. will you Implement it?

**Comment by aneesh1122** [comment]
https://github.com/user-attachments/assets/57fa4d3a-a96b-43fe-aacc-3f2a5a7b72be

**Comment by fast4x** [comment]
Yes I'll try to solve

**Comment by aneesh1122** [comment]
hey @fast4x  could you please fix the bug with playlist indicator?

**Comment by fast4x** [comment]
Remind me what the problem was please

**Comment by aneesh1122** [comment]
> Remind me what the problem was please

Pay attention to add to playlist icon

Uploading WsaClient_wWcDueaH4p.mp4…

It is not updating in real time. Need to change screens to update the icon

**Comment by fast4x** [comment]
Improved available from version 0.6.45

**Comment by aneesh1122** [comment]
> Improved available from version 0.6.45

Thanks man :)

**Comment by aneesh1122** [comment]
I'm trying something with player artists selection page

https://github.com/user-attachments/assets/c1d4a348-4762-484c-b86c-29c192b9b751

I've managed to do everything except getting artist images. how I can do it?

**Comment by fast4x** [comment]
change 
data(artistPage?.thumbnail?.url?.resize(120....

with 

data(values[it]. thumbnail.url....

get thumbnail inside pager...

**Comment by aneesh1122** [comment]
> change data(artistPage?.thumbnail?.url?.resize(120....
> 
> with
> 
> data(values[it]. thumbnail.url....
> 
> get thumbnail inside pager...

I did this
`.data(values[it].thumbnail.url.resize(1200, 1200))`

it was throwing an error because it was not available in info.kt.

so I added it in info.kt

```
data class Info(
    val id: String,
    val name: String?,
    val size: Int = 0,
    val thumbnail: Thumbnail, //added my me
)
```

Now it's giving this error at the time of making apk
`Cannot figure out how to read this field from a cursor`

**Comment by aneesh1122** [comment]
Will you try to solve this? I'll leave this code like this. Just need to add Images.

**Comment by fast4x** [comment]
Yes you are right, another solution can be to launch database and get url...

**Comment by fast4x** [comment]
Do not change the Info class ..

**Comment by aneesh1122** [comment]
> Do not change the Info class ..

Okay.

**Comment by aneesh1122** [comment]
> retrieving the data from the database

**Pull request merged**
